### ISSUE TITLE
Custom streams in DOMDocument::xinclude

### ISSUE THREAD

**Issue by fpoirotte** [facebook/hhvm#2436]
Hi,

It seems HHVM's DOMDocument::xinclude() does not support custom streams, while the same method does in the original PHP.

Reproduce code (full code available at https://gist.github.com/fpoirotte/10534101):
```
// Assuming variablestream.php contains the VariableStream class
// defined in http://php.net/manual/en/stream.streamwrapper.example-1.php
include('variablestream.php');

// Necessary for at least Zend PHP's DOM extension
// which seems to call stat() for xincludes.
class VariableStream2 extends VariableStream
{
    function url_stat($path, $flags)
    {
        $url = parse_url($path);
        $varname = $url["host"];
        return array(
            'size' => strlen($GLOBALS[$varname])
        );
    }
}

stream_wrapper_register("var2", "VariableStream2")
    or die("Failed to register protocol");

$myvar = "<included>data</included>";

$doc = new DOMDocument();
$doc->loadXML(
'<?xml version="1.0" encoding="UTF-8" ?>
<root xmlns:xi="http://www.w3.org/2001/XInclude">
    <xi:include href="var2://myvar"/>
</root>'
);
// The LIBXML_NOBASEFIX constant is missing from both
// Zend PHP & HHVM. See also https://bugs.php.net/bug.php?id=65968.
$doc->xinclude(1 << 18 /* LIBXML_NOBASEFIX */);
var_dump($doc->saveXML());
```

Expected result / Zend PHP result:
```
string(127) "<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xi="http://www.w3.org/2001/XInclude">
    <included>data</included>
</root>
"
```

Actual result:
```
I/O warning : failed to load external entity "var2://myvar"
/tmp/:3: element include: XInclude error : could not load var2://myvar, and no fallback was found
string(135) "<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xi="http://www.w3.org/2001/XInclude">
    <xi:include href="var2://myvar"/>
</root>
"
```

AFAICT, custom streams support could be added globally to extensions using libxml2 by using the ```xmlRegisterInputCallbacks``` function to hook into libxml2 I/O.

Regards,
François

**Comment by bantu** [comment]
I am seeing this in ownCloud (master at bedc4664e41b542eae15b1038b22ace817fc447f)
```
hphp/runtime/vm/func-inl.h:73: void HPHP::Func::validate() const: Assertion `this && m_magic == kMagic`
```

```
www-data@leonard:/home/www-data/projects/owncloud/core/tests$ php /usr/bin/phpunit lib/streamwrappers.php
PHPUnit 4.0.14 by Sebastian Bergmann.

Configuration read from /home/www-data/projects/owncloud/core/tests/phpunit.xml.dist

...

Time: 669 ms, Memory: 12.00Mb

OK (3 tests, 20 assertions)
```

```
www-data@leonard:/home/www-data/projects/owncloud/core/tests$ hhvm --php -v
HipHop VM 3.5.0-dev~nightly.2015.01.08 (dbg)
Compiler: heads/master-0-gcfbb62942298f079c6f7d028c4ec860fa4905f01
Repo schema: b6f1c41c3118cfe074fdcd012a3c93bc1d548a9a
Extension API: 20140829
```

```
www-data@leonard:/home/www-data/projects/owncloud/core/tests$ hhvm /usr/bin/phpunit lib/streamwrappers.php
PHPUnit 4.0.14 by Sebastian Bergmann.

Configuration read from /home/www-data/projects/owncloud/core/tests/phpunit.xml.dist

.terminate called after throwing an instance of 'HPHP::Object'
hhvm: /tmp/tmp.Y3BaCQNtZH/hphp/runtime/vm/func-inl.h:73: void HPHP::Func::validate() const: Assertion `this && m_magic == kMagic' failed.
Aborted (core dumped)
```

```
www-data@leonard:/home/www-data/projects/owncloud/core/tests$ gdb hhvm
GNU gdb (Ubuntu 7.8-1ubuntu4) 7.8.0.20141001-cvs
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from hhvm...done.
(gdb) r /usr/bin/phpunit lib/streamwrappers.php
Starting program: /usr/bin/hhvm /usr/bin/phpunit lib/streamwrappers.php
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe53ff700 (LWP 2386)]
[Thread 0x7fffe53ff700 (LWP 2386) exited]
PHPUnit 4.0.14 by Sebastian Bergmann.

Configuration read from /home/www-data/projects/owncloud/core/tests/phpunit.xml.dist

.terminate called after throwing an instance of 'HPHP::Object'

Program received signal SIGABRT, Aborted.
0x00007ffff016dd27 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff016dd27 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff016f418 in __GI_abort () at abort.c:89
#2  0x00007ffff0a7a05d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff0a77ed6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff0a76ed9 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff0a776da in __gxx_personality_v0 () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff050c033 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#7  0x00007ffff050c557 in _Unwind_Resume () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#8  0x0000000000f372bc in HPHP::UserFile::flushImpl(bool) ()
#9  0x0000000000f37340 in HPHP::UserFile::close() ()
#10 0x0000000000f3752b in HPHP::UserFile::~UserFile() ()
#11 0x0000000000f3a4a5 in HPHP::UserFile::~UserFile() ()
#12 0x0000000000f3e272 in HPHP::ResourceData::release() ()
#13 0x0000000003e000f4 in ?? ()
#14 0x0000000007adc507 in ?? ()
#15 0x0000000007adc4e2 in ?? ()
#16 0x000000000228389f in enterTCHelper () at /tmp/tmp.Y3BaCQNtZH/hphp/runtime/vm/jit/translator-asm-helpers.S:66
#17 0x0000000002283913 in HPHP::jit::x64::BackEnd::enterTCHelper(unsigned char*, HPHP::jit::TReqInfo&) ()
#18 0x0000000002282f82 in HPHP::jit::MCGenerator::enterTC(unsigned char*, void*) ()
#19 0x000000000118e72c in HPHP::ExecutionContext::enterVMAtCurPC() ()
#20 0x000000000228289e in HPHP::ExecutionContext::enterVM(HPHP::ActRec*, HPHP::ExecutionContext::StackArgsState, HPHP::Resumable*, HPHP::ObjectData*) ()
#21 0x000000000228214f in HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags) ()
#22 0x0000000000eac5fe in HPHP::ObjectData::o_invoke(HPHP::String const&, HPHP::Variant const&, bool) ()
#23 0x0000000001904b4e in HPHP::f_hphp_invoke_method(HPHP::Variant const&, HPHP::String const&, HPHP::String const&, HPHP::Variant const&) ()
#24 0x0000000003e6e056 in ?? ()
#25 0x000000000228389f in enterTCHelper () at /tmp/tmp.Y3BaCQNtZH/hphp/runtime/vm/jit/translator-asm-helpers.S:66
#26 0x0000000002283913 in HPHP::jit::x64::BackEnd::enterTCHelper(unsigned char*, HPHP::jit::TReqInfo&) ()
#27 0x0000000002282f82 in HPHP::jit::MCGenerator::enterTC(unsigned char*, void*) ()
#28 0x000000000118e72c in HPHP::ExecutionContext::enterVMAtCurPC() ()
#29 0x000000000228289e in HPHP::ExecutionContext::enterVM(HPHP::ActRec*, HPHP::ExecutionContext::StackArgsState, HPHP::Resumable*, HPHP::ObjectData*) ()
#30 0x000000000228214f in HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags) ()
#31 0x00000000022c9f04 in HPHP::ExecutionContext::invokeUnit(HPHP::TypedValue*, HPHP::Unit const*) ()
#32 0x0000000000e1464c in HPHP::invoke_file_impl(HPHP::Variant&, HPHP::String const&, bool, char const*) ()
#33 0x00000000022c9dfd in HPHP::invoke_file(HPHP::String const&, bool, char const*) ()
#34 0x0000000000e17b08 in HPHP::include_impl_invoke(HPHP::String const&, bool, char const*) ()
#35 0x0000000000fdaf18 in HPHP::hphp_invoke(HPHP::ExecutionContext*, std::string const&, bool, HPHP::Array const&, HPHP::VRefParamValue const&, std::string const&, std::string const&, bool&, std::string&, bool, bool, bool) ()
#36 0x0000000000fdb217 in HPHP::hphp_invoke_simple(std::string const&, bool) ()
#37 0x0000000000fe30af in HPHP::execute_program_impl(int, char**) ()
#38 0x0000000000fe3dab in HPHP::execute_program(int, char**) ()
#39 0x0000000000e003ca in main ()
(gdb)
```

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
