### ISSUE TITLE
segfault after some time of work 

### ISSUE THREAD

**Issue by oprudkyi** [facebook/hhvm#3297]
```
./hphp/hhvm/hhvm --version
HipHop VM 3.3.0-dev (dbg)
Compiler: heads/master-0-g0e110b0f53d7b8903af61530cf6c5844c7a8f17d
Repo schema: bfeccaa74423bb93ef5b97cb64768a7fcd0bd1d0
```
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x2aab191ff940 (LWP 23145)]
0x00000000023a83f4 in std::_Hashtable<HPHP::StringData*, std::pair<HPHP::StringData* const, HPHP::Unit*>, std::allocator<std::pair<HPHP::StringData* const, HPHP::Unit*> >, std::__detail::_Select1st, HPHP::string_data_same, HPHP::string_data_hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_find_before_node (this=0x2aaab1ce7a30, __n=0, 
    __k=@0x2aab191fb558: 0x2aaaecc10700, __code=1629322656) at /root/hhvm/build/gcc49/lib/gcc/x86_64-unknown-linux-gnu/4.9.0/../../../../include/c++/4.9.0/bits/hashtable.h:1388
1388	/root/hhvm/build/gcc49/lib/gcc/x86_64-unknown-linux-gnu/4.9.0/../../../../include/c++/4.9.0/bits/hashtable.h: No such file or directory.
(gdb) bt
#0  0x00000000023a83f4 in std::_Hashtable<HPHP::StringData*, std::pair<HPHP::StringData* const, HPHP::Unit*>, std::allocator<std::pair<HPHP::StringData* const, HPHP::Unit*> >, std::__detail::_Select1st, HPHP::string_data_same, HPHP::string_data_hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_find_before_node (this=0x2aaab1ce7a30, __n=0, 
    __k=@0x2aab191fb558: 0x2aaaecc10700, __code=1629322656) at /root/hhvm/build/gcc49/lib/gcc/x86_64-unknown-linux-gnu/4.9.0/../../../../include/c++/4.9.0/bits/hashtable.h:1388
#1  0x00000000023a7c3e in std::_Hashtable<HPHP::StringData*, std::pair<HPHP::StringData* const, HPHP::Unit*>, std::allocator<std::pair<HPHP::StringData* const, HPHP::Unit*> >, std::__detail::_Select1st, HPHP::string_data_same, HPHP::string_data_hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_find_node (this=0x2aaab1ce7a30, __bkt=0, 
    __key=@0x2aab191fb558: 0x2aaaecc10700, __c=1629322656) at /root/hhvm/build/gcc49/lib/gcc/x86_64-unknown-linux-gnu/4.9.0/../../../../include/c++/4.9.0/bits/hashtable.h:590
#2  0x00000000023a79e2 in std::_Hashtable<HPHP::StringData*, std::pair<HPHP::StringData* const, HPHP::Unit*>, std::allocator<std::pair<HPHP::StringData* const, HPHP::Unit*> >, std::__detail::_Select1st, HPHP::string_data_same, HPHP::string_data_hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::find (this=0x2aaab1ce7a30, 
    __k=@0x2aab191fb558: 0x2aaaecc10700) at /root/hhvm/build/gcc49/lib/gcc/x86_64-unknown-linux-gnu/4.9.0/../../../../include/c++/4.9.0/bits/hashtable.h:1238
#3  0x00000000023a7751 in std::unordered_map<HPHP::StringData*, HPHP::Unit*, HPHP::string_data_hash, HPHP::string_data_same, std::allocator<std::pair<HPHP::StringData* const, HPHP::Unit*> > >::find (this=0x2aaab1ce7a30, 
    __x=@0x2aab191fb558: 0x2aaaecc10700) at /root/hhvm/build/gcc49/lib/gcc/x86_64-unknown-linux-gnu/4.9.0/../../../../include/c++/4.9.0/bits/unordered_map.h:574
#4  0x00000000023a4a0d in HPHP::lookupUnit (path=0x2aaaecc10680, currentDir=0x3dfa77b "", initial_opt=0x2aab191fb607) at /root/hhvm/hhvm/hphp/runtime/base/unit-cache.cpp:417
#5  0x0000000002232802 in HPHP::invoke_file_impl (res=..., path=..., once=true, currentDir=0x3dfa77b "") at /root/hhvm/hhvm/hphp/runtime/base/builtin-functions.cpp:736
#6  0x0000000002232901 in HPHP::invoke_file (s=..., once=true, currentDir=0x3dfa77b "") at /root/hhvm/hhvm/hphp/runtime/base/builtin-functions.cpp:752
#7  0x00000000022329d4 in HPHP::include_impl_invoke (file=..., once=true, currentDir=0x3dfa77b "") at /root/hhvm/hhvm/hphp/runtime/base/builtin-functions.cpp:763
#8  0x00000000022ff3bb in HPHP::hphp_invoke (context=0x2aaab1ce7800, cmd=..., func=false, funcParams=..., funcRet=..., reqInitFunc=..., reqInitDoc=..., error=@0x2aab191fb97f: false, errorMsg=..., once=true, warmupOnly=false, 
    richErrorMsg=false) at /root/hhvm/hhvm/hphp/runtime/base/program-functions.cpp:1736
#9  0x00000000024af75f in HPHP::HttpRequestHandler::executePHPRequest (this=0x2aaaf1214ac0, transport=0x2aaaecf91b10, reqURI=..., sourceRootInfo=..., cachableDynamicContent=false)
    at /root/hhvm/hhvm/hphp/runtime/server/http-request-handler.cpp:379
#10 0x00000000024aed17 in HPHP::HttpRequestHandler::handleRequest (this=0x2aaaf1214ac0, transport=0x2aaaecf91b10) at /root/hhvm/hhvm/hphp/runtime/server/http-request-handler.cpp:289
#11 0x0000000002518f19 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl (this=0x2aaadb70d740, job=..., abort=false) at /root/hhvm/hhvm/hphp/runtime/server/server-worker.h:103
#12 0x000000000251883a in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJob (this=0x2aaadb70d740, job=...) at /root/hhvm/hhvm/hphp/runtime/server/server-worker.h:57
#13 0x00000000025105ce in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start (this=0x2aaadb70d740) at /root/hhvm/hhvm/hphp/util/job-queue.h:466
#14 0x0000000002511a1d in HPHP::AsyncFunc<HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits> >::run_ (obj=0x2aaab994d200) at /root/hhvm/hhvm/hphp/util/async-func.h:205
#15 0x00000000037633a7 in HPHP::AsyncFuncImpl::threadFuncImpl (this=0x2aaab994d200) at /root/hhvm/hhvm/hphp/util/async-func.cpp:131
#16 0x0000000003762f99 in HPHP::AsyncFuncImpl::ThreadFunc (obj=0x2aaab994d200) at /root/hhvm/hhvm/hphp/util/async-func.cpp:51
#17 0x00002aaaaf95f77d in start_thread () from /lib64/libpthread.so.0
#18 0x0000003c996d325d in clone () from /lib64/libc.so.6
#19 0x0000000000000000 in ?? ()
```

**Comment by paulbiss** [comment]
Closing due to inactivity.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
