### ISSUE TITLE
hhvm gets stuck traversing cyclic linked list in fclose

### ISSUE THREAD

**Issue by Nikerabbit** [facebook/hhvm#3363]
I'm running hhvm-fastcgi with nginx. After a while due to unknown reason it stops servering requests and uses 100% of one cpu core. This is a virtual server running Ubuntu.

Config is at https://github.com/wikimedia/translatewiki/tree/8e9e869fb8944af1b2784a27fe92a578a43352e7/puppet/modules/hhvm/files

Version: HipHop VM 3.3.0-dev (rel) compiled by Wikimedia.

Backtrace from the stuck hhvm process:

```
[New LWP 4130]
[New LWP 4128]
[New LWP 4085]
[New LWP 4061]
[New LWP 4058]
[New LWP 4050]
[New LWP 4049]
[New LWP 4048]
[New LWP 4047]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185

Thread 10 (Thread 0x7f5bfbbff700 (LWP 4047)):
#0  0x00007f5c056e1a23 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
No locals.
#1  0x00007f5c0a08c563 in ?? () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
No symbol table info available.
#2  0x00007f5c0a078905 in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
No symbol table info available.
#3  0x0000000001670a8b in apache::thrift::async::TEventBase::loop ()
No symbol table info available.
#4  0x00000000016712b2 in apache::thrift::async::TEventBase::loopForever ()
No symbol table info available.
#5  0x000000000167ed2a in facebook::proxygen::WorkerThread::runLoop ()
No symbol table info available.
#6  0x000000000167efc8 in std::thread::_Impl<std::_Bind_simple<facebook::proxygen::WorkerThread::start()::{lambda()#1} ()> >::_M_run() ()
No symbol table info available.
#7  0x00007f5c05f79bf0 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#8  0x00007f5c061d4182 in start_thread (arg=0x7f5bfbbff700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7f5bfbbff700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140033042413312, -4561996467737880372, 0, 0, 140033042414016, 140033042413312, 4469680919584020684, 4469968146131818700}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#9  0x00007f5c056e138d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.

Thread 9 (Thread 0x7f5bf3bff700 (LWP 4048)):
#0  __lll_lock_wait_private () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:95
No locals.
#1  0x00007f5c05663951 in _L_lock_423 () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#2  0x00007f5c05661bb8 in __GI__IO_link_in (fp=fp@entry=0x7f5bb7b9bd00) at genops.c:105
        __self = 0x7f5bf3bff700
        _buffer = {__routine = 0x7f5c05661860 <flush_cleanup>, __arg = 0x0, __canceltype = 0, __prev = 0x0}
        _avail = 1
#3  0x00007f5c05660a32 in _IO_new_file_init (fp=fp@entry=0x7f5bb7b9bd00) at fileops.c:150
No locals.
#4  0x00007f5c056552e3 in __fopen_internal (filename=0x7f5bd4cae968 "/www/translatewiki.net/w/includes/mime.types", mode=0x7f5bd4cab088 "rb", is32=1) at iofopen.c:86
        new_f = 0x7f5bb7b9bd00
#5  0x00000000009ffac5 in HPHP::PlainFile::open ()
No symbol table info available.
#6  0x0000000000946f5f in HPHP::FileStreamWrapper::open ()
No symbol table info available.
#7  0x00000000009689a9 in HPHP::File::Open ()
No symbol table info available.
#8  0x0000000000f1ee39 in HPHP::f_fopen ()
No symbol table info available.
#9  0x0000000000f20661 in HPHP::f_file_get_contents ()
No symbol table info available.
#10 0x0000000004263fe7 in ?? ()
No symbol table info available.
#11 0x0000000000e3966e in enterTCHelper ()
No symbol table info available.
#12 0x0000000000d90129 in HPHP::JIT::X64::BackEnd::enterTCHelper ()
No symbol table info available.
#13 0x0000000000dc75ac in HPHP::JIT::MCGenerator::enterTC ()
No symbol table info available.
#14 0x0000000000c2226e in HPHP::ExecutionContext::enterVM ()
No symbol table info available.
#15 0x0000000000c224dc in HPHP::ExecutionContext::invokeFunc ()
No symbol table info available.
#16 0x0000000000c22710 in HPHP::ExecutionContext::invokeUnit ()
No symbol table info available.
#17 0x00000000009ef7e1 in HPHP::invoke_file(HPHP::String const&, bool, char const*) ()
No symbol table info available.
#18 0x00000000009f1dd2 in HPHP::include_impl_invoke ()
No symbol table info available.
#19 0x000000000093814d in HPHP::hphp_invoke ()
No symbol table info available.
#20 0x0000000000b04807 in HPHP::HttpRequestHandler::executePHPRequest ()
No symbol table info available.
#21 0x0000000000b05ac8 in HPHP::HttpRequestHandler::handleRequest ()
No symbol table info available.
#22 0x0000000000b39569 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl ()
No symbol table info available.
#23 0x0000000000b397a8 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJob ()
No symbol table info available.
#24 0x0000000000b38708 in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start ()
No symbol table info available.
#25 0x0000000001528197 in HPHP::AsyncFuncImpl::ThreadFunc ()
No symbol table info available.
#26 0x00007f5c061d4182 in start_thread (arg=0x7f5bf3bff700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7f5bf3bff700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140032908195584, -4561996467737880372, 0, 0, 140033073383000, 140032908195584, 4469663327397976268, 4469968146131818700}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#27 0x00007f5c056e138d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.

Thread 8 (Thread 0x7f5bedbff700 (LWP 4049)):
#0  __lll_lock_wait_private () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:95
No locals.
#1  0x00007f5c05663951 in _L_lock_423 () at genops.c:1320
No symbol table info available.
#2  0x00007f5c05661bb8 in __GI__IO_link_in (fp=fp@entry=0x7f5bb7b9ba80) at genops.c:105
        __self = 0x7f5bedbff700
        _buffer = {__routine = 0x7f5c05661860 <flush_cleanup>, __arg = 0x0, __canceltype = 0, __prev = 0x0}
        _avail = 1
#3  0x00007f5c05660a32 in _IO_new_file_init (fp=fp@entry=0x7f5bb7b9ba80) at fileops.c:150
No locals.
#4  0x00007f5c056552e3 in __fopen_internal (filename=0x7f5bb64a7218 "/www/translatewiki.net/w/serialized/normalize-ar.ser", mode=0x7f5bb6496758 "rb", is32=1) at iofopen.c:86
        new_f = 0x7f5bb7b9ba80
#5  0x00000000009ffac5 in HPHP::PlainFile::open ()
No symbol table info available.
#6  0x0000000000946f5f in HPHP::FileStreamWrapper::open ()
No symbol table info available.
#7  0x00000000009689a9 in HPHP::File::Open ()
No symbol table info available.
#8  0x0000000000f1ee39 in HPHP::f_fopen ()
No symbol table info available.
#9  0x0000000000f20661 in HPHP::f_file_get_contents ()
No symbol table info available.
#10 0x0000000003ef8c20 in ?? ()
No symbol table info available.
#11 0x0000000000e3966e in enterTCHelper ()
No symbol table info available.
#12 0x0000000000d90129 in HPHP::JIT::X64::BackEnd::enterTCHelper ()
No symbol table info available.
#13 0x0000000000dc75ac in HPHP::JIT::MCGenerator::enterTC ()
No symbol table info available.
#14 0x0000000000c2226e in HPHP::ExecutionContext::enterVM ()
No symbol table info available.
#15 0x0000000000c224dc in HPHP::ExecutionContext::invokeFunc ()
No symbol table info available.
#16 0x0000000000c22710 in HPHP::ExecutionContext::invokeUnit ()
No symbol table info available.
#17 0x00000000009ef7e1 in HPHP::invoke_file(HPHP::String const&, bool, char const*) ()
No symbol table info available.
#18 0x00000000009f1dd2 in HPHP::include_impl_invoke ()
No symbol table info available.
#19 0x000000000093814d in HPHP::hphp_invoke ()
No symbol table info available.
#20 0x0000000000b04807 in HPHP::HttpRequestHandler::executePHPRequest ()
No symbol table info available.
#21 0x0000000000b05ac8 in HPHP::HttpRequestHandler::handleRequest ()
No symbol table info available.
#22 0x0000000000b39569 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl ()
No symbol table info available.
#23 0x0000000000b397a8 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJob ()
No symbol table info available.
#24 0x0000000000b38708 in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start ()
No symbol table info available.
#25 0x0000000001528197 in HPHP::AsyncFuncImpl::ThreadFunc ()
No symbol table info available.
#26 0x00007f5c061d4182 in start_thread (arg=0x7f5bedbff700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7f5bedbff700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140032807532288, -4561996467737880372, 0, 0, 140033073383000, 140032807532288, 4469632541072398540, 4469968146131818700}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#27 0x00007f5c056e138d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.

Thread 7 (Thread 0x7f5be8fff700 (LWP 4050)):
#0  __lll_lock_wait_private () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:95
No locals.
#1  0x00007f5c056638dd in _L_lock_121 () at genops.c:1320
No symbol table info available.
#2  0x00007f5c05661953 in __GI__IO_un_link (fp=0x7f5bb7b9d880) at genops.c:66
        __self = 0x7f5be8fff700
        _buffer = {__routine = 0x7f5c05661860 <flush_cleanup>, __arg = 0x0, __canceltype = 0, __prev = 0x0}
        _avail = 1
        f = <optimized out>
#3  0x00007f5c05654975 in _IO_new_fclose (fp=0x7f5bb7b9d880) at iofclose.c:55
        status = <optimized out>
#4  0x0000000000a006d4 in HPHP::PlainFile::~PlainFile ()
No symbol table info available.
#5  0x0000000000f2068d in HPHP::f_file_get_contents ()
No symbol table info available.
#6  0x0000000003ef8c20 in ?? ()
No symbol table info available.
#7  0x0000000000e3966e in enterTCHelper ()
No symbol table info available.
#8  0x0000000000d90129 in HPHP::JIT::X64::BackEnd::enterTCHelper ()
No symbol table info available.
#9  0x0000000000dc75ac in HPHP::JIT::MCGenerator::enterTC ()
No symbol table info available.
#10 0x0000000000c2226e in HPHP::ExecutionContext::enterVM ()
No symbol table info available.
#11 0x0000000000c224dc in HPHP::ExecutionContext::invokeFunc ()
No symbol table info available.
#12 0x0000000000c22710 in HPHP::ExecutionContext::invokeUnit ()
No symbol table info available.
#13 0x00000000009ef7e1 in HPHP::invoke_file(HPHP::String const&, bool, char const*) ()
No symbol table info available.
#14 0x00000000009f1dd2 in HPHP::include_impl_invoke ()
No symbol table info available.
#15 0x000000000093814d in HPHP::hphp_invoke ()
No symbol table info available.
#16 0x0000000000b04807 in HPHP::HttpRequestHandler::executePHPRequest ()
No symbol table info available.
#17 0x0000000000b05ac8 in HPHP::HttpRequestHandler::handleRequest ()
No symbol table info available.
#18 0x0000000000b39569 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl ()
No symbol table info available.
#19 0x0000000000b397a8 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJob ()
No symbol table info available.
#20 0x0000000000b38708 in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start ()
No symbol table info available.
#21 0x0000000001528197 in HPHP::AsyncFuncImpl::ThreadFunc ()
No symbol table info available.
#22 0x00007f5c061d4182 in start_thread (arg=0x7f5be8fff700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7f5be8fff700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140032727840512, -4561996467737880372, 0, 0, 140033073383000, 140032727840512, 4469639687897979084, 4469968146131818700}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#23 0x00007f5c056e138d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.

Thread 6 (Thread 0x7f5bd33ff700 (LWP 4058)):
#0  __lll_lock_wait_private () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:95
No locals.
#1  0x00007f5c056638dd in _L_lock_121 () at genops.c:1320
No symbol table info available.
#2  0x00007f5c05661953 in __GI__IO_un_link (fp=0x7f5bb7b9d880) at genops.c:66
        __self = 0x7f5bd33ff700
        _buffer = {__routine = 0x7f5c05661860 <flush_cleanup>, __arg = 0x0, __canceltype = 0, __prev = 0x0}
        _avail = 1
        f = <optimized out>
#3  0x00007f5c05654975 in _IO_new_fclose (fp=0x7f5bb7b9d880) at iofclose.c:55
        status = <optimized out>
#4  0x0000000000a006d4 in HPHP::PlainFile::~PlainFile ()
No symbol table info available.
#5  0x0000000000f2068d in HPHP::f_file_get_contents ()
No symbol table info available.
#6  0x0000000003ef8c20 in ?? ()
No symbol table info available.
#7  0x0000000000e3966e in enterTCHelper ()
No symbol table info available.
#8  0x0000000000d90129 in HPHP::JIT::X64::BackEnd::enterTCHelper ()
No symbol table info available.
#9  0x0000000000dc75ac in HPHP::JIT::MCGenerator::enterTC ()
No symbol table info available.
#10 0x0000000000c2226e in HPHP::ExecutionContext::enterVM ()
No symbol table info available.
#11 0x0000000000c224dc in HPHP::ExecutionContext::invokeFunc ()
No symbol table info available.
#12 0x0000000000c22710 in HPHP::ExecutionContext::invokeUnit ()
No symbol table info available.
#13 0x00000000009ef7e1 in HPHP::invoke_file(HPHP::String const&, bool, char const*) ()
No symbol table info available.
#14 0x00000000009f1dd2 in HPHP::include_impl_invoke ()
No symbol table info available.
#15 0x000000000093814d in HPHP::hphp_invoke ()
No symbol table info available.
#16 0x0000000000b04807 in HPHP::HttpRequestHandler::executePHPRequest ()
No symbol table info available.
#17 0x0000000000b05ac8 in HPHP::HttpRequestHandler::handleRequest ()
No symbol table info available.
#18 0x0000000000b39569 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl ()
No symbol table info available.
#19 0x0000000000b397a8 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJob ()
No symbol table info available.
#20 0x0000000000b38708 in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start ()
No symbol table info available.
#21 0x0000000001528197 in HPHP::AsyncFuncImpl::ThreadFunc ()
No symbol table info available.
#22 0x00007f5c061d4182 in start_thread (arg=0x7f5bd33ff700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7f5bd33ff700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140032362936064, -4561996467737880372, 0, 0, 140033073383000, 140032362936064, 4469591859142170828, 4469968146131818700}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#23 0x00007f5c056e138d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.

Thread 5 (Thread 0x7f5bcdbff700 (LWP 4061)):
#0  __lll_lock_wait_private () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:95
No locals.
#1  0x00007f5c056638dd in _L_lock_121 () at genops.c:1320
No symbol table info available.
#2  0x00007f5c05661953 in __GI__IO_un_link (fp=0x7f5bee442780) at genops.c:66
        __self = 0x7f5bcdbff700
        _buffer = {__routine = 0x7f5c05661860 <flush_cleanup>, __arg = 0x0, __canceltype = 0, __prev = 0x0}
        _avail = 1
        f = <optimized out>
#3  0x00007f5c05654975 in _IO_new_fclose (fp=0x7f5bee442780) at iofclose.c:55
        status = <optimized out>
#4  0x0000000000a01665 in HPHP::PlainFile::sweep ()
No symbol table info available.
#5  0x0000000000a209a6 in HPHP::Sweepable::SweepAll ()
No symbol table info available.
#6  0x00000000009c3a88 in HPHP::MemoryManager::sweep ()
No symbol table info available.
#7  0x0000000000938b93 in HPHP::hphp_session_exit ()
No symbol table info available.
#8  0x0000000000b05ae5 in HPHP::HttpRequestHandler::handleRequest ()
No symbol table info available.
#9  0x0000000000b39569 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl ()
No symbol table info available.
#10 0x0000000000b397a8 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJob ()
No symbol table info available.
#11 0x0000000000b38708 in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start ()
No symbol table info available.
#12 0x0000000001528197 in HPHP::AsyncFuncImpl::ThreadFunc ()
No symbol table info available.
#13 0x00007f5c061d4182 in start_thread (arg=0x7f5bcdbff700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7f5bcdbff700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140032270661376, -4561996467737880372, 0, 0, 140033073383000, 140032270661376, 4469562172328220876, 4469968146131818700}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#14 0x00007f5c056e138d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.

Thread 4 (Thread 0x7f5bdcbff700 (LWP 4085)):
#0  0x00007f5c05661a08 in __GI__IO_un_link (fp=0x7f5bf334d700) at genops.c:78
        _buffer = {__routine = 0x7f5c05661860 <flush_cleanup>, __arg = 0x0, __canceltype = 0, __prev = 0x0}
        _avail = 1
        f = 0x7f5bb7b9c268
#1  0x00007f5c05654975 in _IO_new_fclose (fp=0x7f5bf334d700) at iofclose.c:55
        status = <optimized out>
#2  0x0000000000a01665 in HPHP::PlainFile::sweep ()
No symbol table info available.
#3  0x0000000000a209a6 in HPHP::Sweepable::SweepAll ()
No symbol table info available.
#4  0x00000000009c3a88 in HPHP::MemoryManager::sweep ()
No symbol table info available.
#5  0x0000000000938b93 in HPHP::hphp_session_exit ()
No symbol table info available.
#6  0x0000000000b05ae5 in HPHP::HttpRequestHandler::handleRequest ()
No symbol table info available.
#7  0x0000000000b39569 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl ()
No symbol table info available.
#8  0x0000000000b397a8 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJob ()
No symbol table info available.
#9  0x0000000000b38708 in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start ()
No symbol table info available.
#10 0x0000000001528197 in HPHP::AsyncFuncImpl::ThreadFunc ()
No symbol table info available.
#11 0x00007f5c061d4182 in start_thread (arg=0x7f5bdcbff700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7f5bdcbff700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140032522319616, -4561996467737880372, 0, 0, 140033073383000, 140032522319616, 4469595157677054156, 4469968146131818700}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#12 0x00007f5c056e138d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.

Thread 3 (Thread 0x7f5bd7fff700 (LWP 4128)):
#0  __lll_lock_wait_private () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:95
No locals.
#1  0x00007f5c05663951 in _L_lock_423 () at genops.c:1320
No symbol table info available.
#2  0x00007f5c05661bb8 in __GI__IO_link_in (fp=fp@entry=0x7f5bd838b600) at genops.c:105
        __self = 0x7f5bd7fff700
        _buffer = {__routine = 0x7f5c05661860 <flush_cleanup>, __arg = 0x0, __canceltype = 0, __prev = 0x0}
        _avail = 1
#3  0x00007f5c05660a32 in _IO_new_file_init (fp=fp@entry=0x7f5bd838b600) at fileops.c:150
No locals.
#4  0x00007f5c056552e3 in __fopen_internal (filename=0x7f5bb78a7668 "/www/translatewiki.net/w/serialized/normalize-ar.ser", mode=0x7f5bb789c738 "rb", is32=1) at iofopen.c:86
        new_f = 0x7f5bd838b600
#5  0x00000000009ffac5 in HPHP::PlainFile::open ()
No symbol table info available.
#6  0x0000000000946f5f in HPHP::FileStreamWrapper::open ()
No symbol table info available.
#7  0x00000000009689a9 in HPHP::File::Open ()
No symbol table info available.
#8  0x0000000000f1ee39 in HPHP::f_fopen ()
No symbol table info available.
#9  0x0000000000f20661 in HPHP::f_file_get_contents ()
No symbol table info available.
#10 0x0000000003ef8c20 in ?? ()
No symbol table info available.
#11 0x0000000000e3966e in enterTCHelper ()
No symbol table info available.
#12 0x0000000000d90129 in HPHP::JIT::X64::BackEnd::enterTCHelper ()
No symbol table info available.
#13 0x0000000000dc75ac in HPHP::JIT::MCGenerator::enterTC ()
No symbol table info available.
#14 0x0000000000c2226e in HPHP::ExecutionContext::enterVM ()
No symbol table info available.
#15 0x0000000000c224dc in HPHP::ExecutionContext::invokeFunc ()
No symbol table info available.
#16 0x0000000000c22710 in HPHP::ExecutionContext::invokeUnit ()
No symbol table info available.
#17 0x00000000009ef7e1 in HPHP::invoke_file(HPHP::String const&, bool, char const*) ()
No symbol table info available.
#18 0x00000000009f1dd2 in HPHP::include_impl_invoke ()
No symbol table info available.
#19 0x000000000093814d in HPHP::hphp_invoke ()
No symbol table info available.
#20 0x0000000000b04807 in HPHP::HttpRequestHandler::executePHPRequest ()
No symbol table info available.
#21 0x0000000000b05ac8 in HPHP::HttpRequestHandler::handleRequest ()
No symbol table info available.
#22 0x0000000000b39569 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl ()
No symbol table info available.
#23 0x0000000000b397a8 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJob ()
No symbol table info available.
#24 0x0000000000b38708 in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start ()
No symbol table info available.
#25 0x0000000001528197 in HPHP::AsyncFuncImpl::ThreadFunc ()
No symbol table info available.
#26 0x00007f5c061d4182 in start_thread (arg=0x7f5bd7fff700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7f5bd7fff700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140032442627840, -4561996467737880372, 0, 0, 140033073383000, 140032442627840, 4469584712316590284, 4469968146131818700}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#27 0x00007f5c056e138d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.

Thread 2 (Thread 0x7f5bdbbff700 (LWP 4130)):
#0  __lll_lock_wait_private () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:95
No locals.
#1  0x00007f5c05663951 in _L_lock_423 () at genops.c:1320
No symbol table info available.
#2  0x00007f5c05661bb8 in __GI__IO_link_in (fp=fp@entry=0x7f5bb7ba1c00) at genops.c:105
        __self = 0x7f5bdbbff700
        _buffer = {__routine = 0x7f5c05661860 <flush_cleanup>, __arg = 0x0, __canceltype = 0, __prev = 0x0}
        _avail = 1
#3  0x00007f5c05660a32 in _IO_new_file_init (fp=fp@entry=0x7f5bb7ba1c00) at fileops.c:150
No locals.
#4  0x00007f5c056552e3 in __fopen_internal (filename=0x7f5bb70fed38 "/www/translatewiki.net/w/cache/translate_messageindex.cdb", mode=0x7f5bfc844f38 "rb", is32=1) at iofopen.c:86
        new_f = 0x7f5bb7ba1c00
#5  0x00000000009ffac5 in HPHP::PlainFile::open ()
No symbol table info available.
#6  0x0000000000946f5f in HPHP::FileStreamWrapper::open ()
No symbol table info available.
#7  0x00000000009689a9 in HPHP::File::Open ()
No symbol table info available.
#8  0x0000000000f1ee39 in HPHP::f_fopen ()
No symbol table info available.
#9  0x0000000003f09f82 in ?? ()
No symbol table info available.
#10 0x0000000000e3966e in enterTCHelper ()
No symbol table info available.
#11 0x0000000000d90129 in HPHP::JIT::X64::BackEnd::enterTCHelper ()
No symbol table info available.
#12 0x0000000000dc75ac in HPHP::JIT::MCGenerator::enterTC ()
No symbol table info available.
#13 0x0000000000c2226e in HPHP::ExecutionContext::enterVM ()
No symbol table info available.
#14 0x0000000000c224dc in HPHP::ExecutionContext::invokeFunc ()
No symbol table info available.
#15 0x0000000000c22710 in HPHP::ExecutionContext::invokeUnit ()
No symbol table info available.
#16 0x00000000009ef7e1 in HPHP::invoke_file(HPHP::String const&, bool, char const*) ()
No symbol table info available.
#17 0x00000000009f1dd2 in HPHP::include_impl_invoke ()
No symbol table info available.
#18 0x000000000093814d in HPHP::hphp_invoke ()
No symbol table info available.
#19 0x0000000000b04807 in HPHP::HttpRequestHandler::executePHPRequest ()
No symbol table info available.
#20 0x0000000000b05ac8 in HPHP::HttpRequestHandler::handleRequest ()
No symbol table info available.
#21 0x0000000000b39569 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl ()
No symbol table info available.
#22 0x0000000000b397a8 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJob ()
No symbol table info available.
#23 0x0000000000b38708 in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start ()
No symbol table info available.
#24 0x0000000001528197 in HPHP::AsyncFuncImpl::ThreadFunc ()
No symbol table info available.
#25 0x00007f5c061d4182 in start_thread (arg=0x7f5bdbbff700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7f5bdbbff700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140032505542400, -4561996467737880372, 0, 0, 140033073383000, 140032505542400, 4469610550839843020, 4469968146131818700}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#26 0x00007f5c056e138d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.

Thread 1 (Thread 0x7f5bf43ff700 (LWP 4040)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
No locals.
#1  0x0000000000b215a8 in HPHP::HttpServer::runOrExitProcess ()
No symbol table info available.
#2  0x000000000093d2cd in HPHP::execute_program_impl(int, char**) ()
No symbol table info available.
#3  0x000000000093e146 in HPHP::execute_program ()
No symbol table info available.
#4  0x0000000000833a69 in main ()
No symbol table info available.
Saved corefile /resources/nike/hhvm-dumps/hhvm.1407242104.translatewiki.net.4040.core
```

**Comment by Nikerabbit** [comment]
This is probably dupe of #5528

**Comment by Orvid** [comment]
The related issue was closed. Closing this one.
