### ISSUE TITLE
pure virtual method called after fastcgi connection was deleted

### ISSUE THREAD

**Issue by damenjs** [facebook/hhvm#3759]
when parsing fastcgi message in HPHP::FastCGISession::handleBeginRequest, i got a terminated message "pure virtual method called", this is my stack:

```
#0  0x00007fffeefef3e9 in raise () from /home/work/local/hhvm/lib64/libc-2.18.so
#1  0x00007fffeeff07e8 in abort () from /home/work/local/hhvm/lib64/libc-2.18.so
#2  0x00007fffef8dfcb5 in __gnu_cxx::__verbose_terminate_handler () at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007fffef8dde26 in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:38
#4  0x00007fffef8dde53 in std::terminate () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:48
#5  0x00007fffef8de92f in __cxxabiv1::__cxa_pure_virtual () at ../../../../libstdc++-v3/libsupc++/pure.cc:50
#6  0x000000000263a0ce in HPHP::FastCGISession::beginTransaction (this=0x7fffe66bc580, request_id=1)
    at /mnt/huda/dev_hhvm/public/hhvm/hhvm-src-301/hhvm-HHVM-3.0.1/hphp/runtime/server/fastcgi/fastcgi-session.cpp:761
#7  0x0000000002638ce1 in HPHP::FastCGISession::handleBeginRequest (this=0x7fffe66bc580, role=HPHP::FastCGISession::RESPONDER, flags=HPHP::FastCGISession::KEEP_CONN)
    at /mnt/huda/dev_hhvm/public/hhvm/hhvm-src-301/hhvm-HHVM-3.0.1/hphp/runtime/server/fastcgi/fastcgi-session.cpp:507
#8  0x0000000002638860 in HPHP::FastCGISession::parseBeginRequest (this=0x7fffe66bc580, cursor=..., available=@0x7fffeb374ac8: 3656)
    at /mnt/huda/dev_hhvm/public/hhvm/hhvm-src-301/hhvm-HHVM-3.0.1/hphp/runtime/server/fastcgi/fastcgi-session.cpp:450
#9  0x000000000263845c in HPHP::FastCGISession::parseRecordBody (this=0x7fffe66bc580, cursor=..., available=@0x7fffeb374b20: 3664)
    at /mnt/huda/dev_hhvm/public/hhvm/hhvm-src-301/hhvm-HHVM-3.0.1/hphp/runtime/server/fastcgi/fastcgi-session.cpp:354
#10 0x00000000026380af in HPHP::FastCGISession::onIngress (this=0x7fffe66bc580, chain=0x7fffe6634748)
    at /mnt/huda/dev_hhvm/public/hhvm/hhvm-src-301/hhvm-HHVM-3.0.1/hphp/runtime/server/fastcgi/fastcgi-session.cpp:272
#11 0x000000000264a714 in HPHP::FastCGIConnection::readDataAvailable (this=0x7fffe66bc480, len=4072)
    at /mnt/huda/dev_hhvm/public/hhvm/hhvm-src-301/hhvm-HHVM-3.0.1/hphp/runtime/server/fastcgi/fastcgi-server.cpp:115
#12 0x00000000039c56c0 in apache::thrift::async::TAsyncSocket::handleRead (this=0x7fffe5abc940)
    at /mnt/huda/dev_hhvm/public/hhvm/hhvm-src-301/hhvm-HHVM-3.0.1/hphp/third_party/thrift/lib/cpp/async/TAsyncSocket.cpp:1265
#13 0x00000000039c50cc in apache::thrift::async::TAsyncSocket::ioReady (this=0x7fffe5abc940, events=2)
    at /mnt/huda/dev_hhvm/public/hhvm/hhvm-src-301/hhvm-HHVM-3.0.1/hphp/third_party/thrift/lib/cpp/async/TAsyncSocket.cpp:1166
#14 0x00000000039c9175 in apache::thrift::async::TAsyncSocket::IoHandler::handlerReady (this=0x7fffe5abca30, events=2)
    at /mnt/huda/dev_hhvm/public/hhvm/hhvm-src-301/hhvm-HHVM-3.0.1/hphp/third_party/thrift/lib/cpp/async/TAsyncSocket.h:509
#15 0x00000000037821c7 in apache::thrift::async::TEventHandler::libeventCallback (fd=33, events=2, arg=0x7fffe5abca30)
    at /mnt/huda/dev_hhvm/public/hhvm/hhvm-src-301/hhvm-HHVM-3.0.1/hphp/third_party/thrift/lib/cpp/async/TEventHandler.cpp:152
```

I guess that after fastcgi connection was deleted there would be something wrong to call newSessionHandler.
Expect your reply, thanks!

**Comment by jwatzman** [comment]
I am fairly confident that this is fixed by e13ca7d910554bd455980be1cac65d888d71a931 which will start showing up in nightly builds dated 2015.02.03, as well as in 3.6.0, 3.5.1, and 3.3.4 whenever those come out. I'm going to close this now; please reopen if you can repro in any of those versions.
