### ISSUE TITLE
HHVM-3.3.0 InvalidArgumentException

### ISSUE THREAD

**Issue by ratnayake** [facebook/hhvm#3797]
I was using hhvm-3.2.0 symfony framworked website was work fine then today morning I updated into hhvm-3.3.0 from apt-get now I'm getting fllowing error on hhvm log

```
Fatal error: Uncaught exception 'InvalidArgumentException' with message '[ERROR 3067] Element '{http://www.w3.org/2001/XMLSchema}import': Failed to parse the XML resource 
'file:////home/ubuntu/www/www.oo.se/symfony/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/schema/dic/services/services-1.0.xsd'. 
(in in_memory_buffer - line 8, column 0)' in /home/ubuntu/www/www.oo.se/symfony/vendor/symfony/symfony/src/Symfony/Component/Config/Util/XmlUtils.php:96\nStack trace:\n#0 /home/ubuntu/www/www.oo.se/symfony/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php(215): Symfony\\Component\\Config\\Util\\XmlUtils::loadFile()\n#1 /home/ubuntu/www/www.oo.se/symfony/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php(42): Symfony\\Component\\DependencyInjection\\Loader\\XmlFileLoader->parseFile()\n#2 /home/ubuntu/www/www.oo.se/symfony/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php(42): Symfony\\Component\\DependencyInjection\\Loader\\XmlFileLoader->load()\n#3 /home/ubuntu/www/www.oo.se/symfony/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php(50): Symfony\\Bundle\\FrameworkBundle\\DependencyInjection\\FrameworkExtension->load()\n#4 /home/ubuntu/www/www.oo.se/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\\Component\\DependencyInjection\\Compiler\\MergeExtensionConfigurationPass->process()\n#5 /home/ubuntu/www/www.oo.se/symfony/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(118): Symfony\\Component\\HttpKernel\\DependencyInjection\\MergeExtensionConfigurationPass->process()\n#6 /home/ubuntu/www/www.oo.se/symfony/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(617): Symfony\\Component\\DependencyInjection\\Compiler\\Compiler->compile()\n#7 /home/ubuntu/www/www.oo.se/symfony/app/bootstrap.php.cache(2460): Symfony\\Component\\DependencyInjection\\ContainerBuilder->compile()\n#8 /home/ubuntu/www/www.oo.se/symfony/app/bootstrap.php.cache(2239): Symfony\\Component\\HttpKernel\\Kernel->initializeContainer()\n#9 /home/ubuntu/www/www.oo.se/index.php(33): Symfony\\Component\\HttpKernel\\Kernel->boot()\n#10 {main}\n\nNext exception 'Symfony\\Component\\DependencyInjection\\Exception\\InvalidArgumentException' with message 'Unable to parse file "/home/ubuntu/www/www.oo.se/symfony/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/../Resources/config/web.xml".' in /home/ubuntu/www/www.oo.se/symfony/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php:217\nStack trace:\n#0 /home/ubuntu/www/www.oo.se/symfony/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php(42): Symfony\\Component\\DependencyInjection\\Loader\\XmlFileLoader->parseFile()\n#1 /home/ubuntu/www/www.oo.se/symfony/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php(42): Symfony\\Component\\DependencyInjection\\Loader\\XmlFileLoader->load()\n#2 /home/ubuntu/www/www.oo.se/symfony/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php(50): Symfony\\Bundle\\FrameworkBundle\\DependencyInjection\\FrameworkExtension->load()\n#3 /home/ubuntu/www/www.oo.se/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\\Component\\DependencyInjection\\Compiler\\MergeExtensionConfigurationPass->process()\n#4 /home/ubuntu/www/www.oo.se/symfony/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(118): Symfony\\Component\\HttpKernel\\DependencyInjection\\MergeExtensionConfigurationPass->process()\n#5 /home/ubuntu/www/www.oo.se/symfony/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(617): Symfony\\Component\\DependencyInjection\\Compiler\\Compiler->compile()\n#6 /home/ubuntu/www/www.oo.se/symfony/app/bootstrap.php.cache(2460): Symfony\\Component\\DependencyInjection\\ContainerBuilder->compile()\n#7 /home/ubuntu/www/www.oo.se/symfony/app/bootstrap.php.cache(2239): Symfony\\Component\\HttpKernel\\Kernel->initializeContainer()\n#8 /home/ubuntu/www/www.oo.se/index.php(33): Symfony\\Component\\HttpKernel\\Kernel->boot()\n#9 {main}
```

when i revert it to HHVM-3.2.0  it's works fine

**Comment by ctrl-f5** [comment]
still having this issue on 3.5.0 on ubuntu 14.04
adding `hhvm.libxml.ext_entity_whitelist = file,http` to php.ini and server.ini solved the problem.

**Comment by SeerUK** [comment]
This issue is not related to you having to whitelist certain protocols. That is a documented security feature of HHVM. This issue turned out to be caused by HHVM not using the config file unless it was explicitly told to do so in every command.

See: 
https://github.com/facebook/hhvm/blob/3445a26e54faba5828eb6b8f6e74e52b472cf282/hphp/doc/inconsistencies#L131-L134

**Comment by csvan** [comment]
Barring any of the fixes mentioned in this thread, this is still an issue on HHVM 3.7.1, given vanilla installs of both Symfony and HHVM.

**Comment by fredemmott** [comment]
Sorry, please could you explain what you think the issue with HHVM is? You're describing intentional behavior, and describing the documented solution.
