### ISSUE TITLE
Segfault when all stats are enabled under high load

### ISSUE THREAD

**Issue by GeniusDex** [facebook/hhvm#3846]
After starting hhvm with the admin interface enabled (available via nginx on localhost:8123), i enabled all statistics:

```
curl http://localhost:8123/stats-on
curl http://localhost:8123/stats-web
curl http://localhost:8123/stats-mem
curl http://localhost:8123/stats-mcc
curl http://localhost:8123/stats-sql
curl http://localhost:8123/stats-mutex
```

Then i started ab (apache-bench) on a single resource, and within 30 seconds a segfault occurs, usually after only a few seconds. gdb on hhvm-dbg gives the following backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f30623ff700 (LWP 18639)]
0x0000000000b6f883 in std::__detail::_Map_base<HPHP::SharedString, std::pair<HPHP::SharedString const, long>, std::allocator<std::pair<HPHP::SharedString const, long> >, std::__detail::_Select1st, HPHP::shared_string_eq, HPHP::shared_string_hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true>, true>::operator[](HPHP::SharedString&&) ()
(gdb) bt
#0  0x0000000000b6f883 in std::__detail::_Map_base<HPHP::SharedString, std::pair<HPHP::SharedString const, long>, std::allocator<std::pair<HPHP::SharedString const, long> >, std::__detail::_Select1st, HPHP::shared_string_eq, HPHP::shared_string_hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true>, true>::operator[](HPHP::SharedString&&) ()
#1  0x0000000000b69231 in HPHP::ServerStats::Log(std::string const&, long) ()
#2  0x0000000000b6966c in HPHP::server_stats_log_mutex(std::string const&, long) ()
#3  0x000000000158bd25 in HPHP::LockProfiler::~LockProfiler() ()
#4  0x0000000000b863fd in HPHP::FastCGIServer::handleRequest(std::shared_ptr<HPHP::FastCGITransport>) ()
#5  0x0000000000b86632 in HPHP::FastCGIConnection::handleRequest(int) ()
#6  0x0000000000b83aa7 in HPHP::FastCGITransport::onHeadersComplete() ()
#7  0x0000000000b7abe8 in HPHP::FastCGITransaction::onParams(std::unique_ptr<folly::IOBuf, std::default_delete<folly::IOBuf> >) ()
#8  0x0000000000b7fea0 in HPHP::FastCGISession::parseParams(folly::io::Cursor&, unsigned long&) ()
#9  0x0000000000b80620 in HPHP::FastCGISession::onIngress(folly::IOBuf const*) ()
#10 0x0000000000b87431 in HPHP::FastCGIConnection::readDataAvailable(unsigned long) ()
#11 0x000000000183623c in apache::thrift::async::TAsyncSocket::handleRead() ()
#12 0x000000000183ad96 in apache::thrift::async::TAsyncSocket::IoHandler::handlerReady(unsigned short) ()
#13 0x00007f306d6aeccc in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
#14 0x00000000016f12db in apache::thrift::async::TEventBase::loop() ()
#15 0x00000000016f1b22 in apache::thrift::async::TEventBase::loopForever() ()
#16 0x00000000016f5b0a in facebook::proxygen::WorkerThread::runLoop() ()
#17 0x00000000016f5da8 in std::thread::_Impl<std::_Bind_simple<facebook::proxygen::WorkerThread::start()::{lambda()#1} ()> >::_M_run() ()
#18 0x00007f306a6c4c70 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#19 0x00007f306ab4bb50 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#20 0x00007f3069ec7e6d in clone () from /lib/x86_64-linux-gnu/libc.so.6
#21 0x0000000000000000 in ?? ()
(gdb) 
```

Running HHVM 3.2 on Debian 7.4:

```
root@# hhvm --version
HipHop VM 3.2.0 (rel)
Compiler: tags/HHVM-3.2.0-0-g01228273b8cf709aacbd3df1c51b1e690ecebac8
Repo schema: c52ba40f4a246d35a88f1dfc1daf959851ced8aa
root@# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.4 (wheezy)
Release:        7.4
Codename:       wheezy
```

**Comment by paulbiss** [comment]
Closing due to inactivity.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
