### ISSUE TITLE
"Invalid Cell Type" assertion in test/slow/async/awaitall.php

### ISSUE THREAD

**Issue by rrh** [facebook/hhvm#3919]
I see an "Invalid Cell Type" assertion.

I build using gcc 4.9.1 on what is otherwise a stock ubuntu 14.04 system, populated using instructions at https://github.com/facebook/hhvm/wiki/Building-and-installing-HHVM-on-Ubuntu-14.04 (except that gcc 4.8.3 is removed, and I then apt-get as appropriate to get 4.9.1, which I need for eventual experiments with tsan).

I cmake a Debug build using:
```
 cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_ZEND_COMPAT=ON -DENABLE_MONGO=ON -DENABLE_EZC_TEST=ON .
 ```

This invocation gives a runtime assertion, replayed per the test/run replay instructions:
```
hhvm/hhvm -c test/slow/config.ini -vEval.EnableArgsInBacktraces=true -vRepo.Local.Mode=-- -vRepo.Central.Path=${HOME}/dev/hhvm/verify.hhbc -vEval.Jit=0 -vResourceLimit.CoreFileSize=0 --file test/slow/async/awaitall.php
```
Gives a gdb stack trace of these 15 top frames:
```
#0  0x00007ffff02debb9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff02e1fc8 in __GI_abort () at abort.c:89
#2  0x00007ffff02d7a76 in __assert_fail_base (fmt=0x7ffff0429370 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x3ed818b "!\"Invalid Cell type\"", 
    file=file@entry=0x3ed8068 "/home/rrh/dev/hhvm/hphp/runtime/base/tv-helpers.cpp", line=line@entry=72, 
    function=function@entry=0x3edb1a0 <HPHP::cellIsPlausible(HPHP::TypedValue)::__PRETTY_FUNCTION__> "bool HPHP::cellIsPlausible(HPHP::Cell)") at assert.c:92
#3  0x00007ffff02d7b22 in __GI___assert_fail (assertion=0x3ed818b "!\"Invalid Cell type\"", file=0x3ed8068 "/home/rrh/dev/hhvm/hphp/runtime/base/tv-helpers.cpp", line=72, 
    function=0x3edb1a0 <HPHP::cellIsPlausible(HPHP::TypedValue)::__PRETTY_FUNCTION__> "bool HPHP::cellIsPlausible(HPHP::Cell)") at assert.c:101
#4  0x000000000241afd6 in HPHP::cellIsPlausible (cell=...) at /home/rrh/dev/hhvm/hphp/runtime/base/tv-helpers.cpp:72
#5  0x00000000027ccc2d in HPHP::tvAssertCell (tv=0x6358a70 <HPHP::EmptyArray::s_initializer>) at /home/rrh/dev/hhvm/hphp/runtime/base/tv-helpers.h:311
#6  0x0000000003122ace in HPHP::BaseVector::data (this=0x7fffe481f570) at /home/rrh/dev/hhvm/hphp/runtime/ext/ext_collections.h:288
#7  0x0000000003121a6b in HPHP::c_AwaitAllWaitHandle::FromVector (dependencies=0x7fffe481f570) at /home/rrh/dev/hhvm/hphp/runtime/ext/asio/await_all_wait_handle.cpp:236
#8  0x00000000031213f2 in HPHP::c_AwaitAllWaitHandle::ti_fromvector (dependencies=...) at /home/rrh/dev/hhvm/hphp/runtime/ext/asio/await_all_wait_handle.cpp:139
#9  0x00000000037f1312 in HPHP::tg_18AwaitAllWaitHandle_fromVector (ar=0x7fffdf0bfec0)
    at /home/rrh/dev/hhvm/hphp/runtime/ext_hhvm/../ext/CMakeFiles/hphp_runtime_ext.dir/asio/await_all_wait_handle.cpp.o.ext_hhvm.cpp:137
#10 0x000000000279f4b2 in HPHP::ExecutionContext::iopNativeImpl (this=0x7fffe48066f8, 
    pc=@0x7fffffffca50: 0x7fffe4bce3a8 "\341\016[\341\341\341\341\016[\341\341\016[\341\016[\341\016[\341\016[", '\245' <repeats 234 times>...)
    at /home/rrh/dev/hhvm/hphp/runtime/vm/bytecode.cpp:6808
#11 0x00000000027eac79 in HPHP::ExecutionContext::dispatchImpl<false> (this=0x7fffe48066f8) at /home/rrh/dev/hhvm/hphp/runtime/vm/bytecode.cpp:7446
#12 0x00000000027c872c in HPHP::ExecutionContext::dispatch (this=0x7fffe48066f8) at /home/rrh/dev/hhvm/hphp/runtime/vm/bytecode.cpp:7452
#13 0x000000000277ed61 in HPHP::ExecutionContext::enterVMAtFunc (this=0x7fffe48066f8, enterFnAr=0x7fffdf0bffc0, stk=HPHP::ExecutionContext::Untrimmed)
    at /home/rrh/dev/hhvm/hphp/runtime/vm/bytecode.cpp:1890
#14 0x000000000277f063 in HPHP::ExecutionContext::enterVM (this=0x7fffe48066f8, ar=0x7fffdf0bffc0, stk=HPHP::ExecutionContext::Untrimmed, resumable=0x0, exception=0x0)
    at /home/rrh/dev/hhvm/hphp/runtime/vm/bytecode.cpp:1946
#15 0x000000000277fc5c in HPHP::ExecutionContext::invokeFunc (this=0x7fffe48066f8, retval=0x7fffffffcdd0, f=0x7fffdf9f9e80, args_=..., this_=0x0, cls=0x0, 
    varEnv=0x7fffe48113f0, invName=0x0, flags=HPHP::ExecutionContext::InvokePseudoMain) at /home/rrh/dev/hhvm/hphp/runtime/vm/bytecode.cpp:2111
```

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
