### ISSUE TITLE
Segmentation fault during intensive logging of warnings

### ISSUE THREAD

**Issue by pracj3am** [facebook/hhvm#4029]
Code `array_walk($renamed, 'class_alias'); ` emits warnings `Warning: Class [...] not found in [...]`. After some time is causes that hhvm crashes. HHVM version 3445a26
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd37ff700 (LWP 16378)]
0x00007ffff09dd602 in ?? () from /usr/lib/x86_64-linux-gnu/libjemalloc.so.1
(gdb) bt
#0  0x00007ffff09dd602 in ?? () from /usr/lib/x86_64-linux-gnu/libjemalloc.so.1
#1  0x00007ffff09f992f in ?? () from /usr/lib/x86_64-linux-gnu/libjemalloc.so.1
#2  0x00007ffff09d6172 in malloc () from /usr/lib/x86_64-linux-gnu/libjemalloc.so.1
#3  0x00007fffeef4a2d8 in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007fffeefa9e59 in std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007fffeefaaacb in std::string::_Rep::_M_clone(std::allocator<char> const&, unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007fffeefaab70 in std::string::reserve(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007fffeef86f94 in std::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::overflow(int) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007fffeef8ad45 in std::basic_streambuf<char, std::char_traits<char> >::xsputn(char const*, long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007fffeef822f6 in std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00000000016869d2 in HPHP::Logger::log(HPHP::Logger::LogLevelType, char const*, HPHP::Exception const&, char const*, int) ()
#11 0x0000000000985c05 in HPHP::ExecutionContext::handleError(std::string const&, int, bool, HPHP::ExecutionContext::ErrorThrowMode, std::string const&, bool) ()
#12 0x0000000000a34459 in HPHP::raise_warning(char const*, ...) ()
#13 0x0000000001131a87 in HPHP::f_class_alias(HPHP::String const&, HPHP::String const&, bool) ()
#14 0x0000000000c891b5 in void HPHP::Native::callFunc<false, false>(HPHP::Func const*, void*, HPHP::TypedValue*, HPHP::TypedValue&) ()
#15 0x0000000000c8927f in HPHP::TypedValue* HPHP::Native::functionWrapper<false, false>(HPHP::ActRec*) ()
#16 0x0000000002800686 in ?? ()
#17 0x0000000000f2b05e in enterTCHelper ()
#18 0x0000000000e14909 in HPHP::jit::x64::BackEnd::enterTCHelper(unsigned char*, HPHP::jit::TReqInfo&) ()
#19 0x0000000000dc6dbf in HPHP::jit::MCGenerator::enterTC(unsigned char*, void*) ()
#20 0x0000000000bd445e in HPHP::ExecutionContext::enterVM(HPHP::ActRec*, HPHP::ExecutionContext::StackArgsState, HPHP::Resumable*, HPHP::ObjectData*) ()
#21 0x0000000000bd6111 in HPHP::ExecutionContext::invokeFuncFew(HPHP::TypedValue*, HPHP::Func const*, void*, HPHP::StringData*, int, HPHP::TypedValue const*) ()
#22 0x00000000012a0ea8 in HPHP::walk_func(HPHP::VRefParamValue const&, HPHP::Variant const&, HPHP::Variant const&, void const*) ()
#23 0x00000000009506a3 in HPHP::ArrayUtil::Walk(HPHP::VRefParamValue const&, void (*)(HPHP::VRefParamValue const&, HPHP::Variant const&, HPHP::Variant const&, void const*), void const*, bool, HPHP::hphp_hash_set<void*, HPHP::pointer_hash<void>, std::equal_to<void*> >*, HPHP::Variant const&) ()
#24 0x00000000012a13b3 in HPHP::f_array_walk(HPHP::VRefParamValue const&, HPHP::Variant const&, HPHP::Variant const&) ()
#25 0x00000000028f48b3 in ?? ()
#26 0x0000000000f2b05e in enterTCHelper ()
#27 0x0000000000e14909 in HPHP::jit::x64::BackEnd::enterTCHelper(unsigned char*, HPHP::jit::TReqInfo&) ()
#28 0x0000000000dc6dbf in HPHP::jit::MCGenerator::enterTC(unsigned char*, void*) ()
#29 0x0000000000bd445e in HPHP::ExecutionContext::enterVM(HPHP::ActRec*, HPHP::ExecutionContext::StackArgsState, HPHP::Resumable*, HPHP::ObjectData*) ()
#30 0x0000000000bd46cb in HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags) ()
#31 0x0000000000bd4919 in HPHP::ExecutionContext::invokeUnit(HPHP::TypedValue*, HPHP::Unit const*) ()
#32 0x00000000009730c1 in HPHP::invoke_file(HPHP::String const&, bool, char const*) ()
#33 0x00000000009757b1 in HPHP::include_impl_invoke(HPHP::String const&, bool, char const*) ()
#34 0x0000000000a457b1 in HPHP::hphp_invoke(HPHP::ExecutionContext*, std::string const&, bool, HPHP::Array const&, HPHP::VRefParamValue const&, std::string const&, std::string const&, bool&, std::string&, bool, bool, bool) ()
#35 0x0000000000b64c51 in HPHP::HttpRequestHandler::executePHPRequest(HPHP::Transport*, HPHP::RequestURI&, HPHP::SourceRootInfo&, bool) ()
#36 0x0000000000b65fc8 in HPHP::HttpRequestHandler::handleRequest(HPHP::Transport*) ()
#37 0x0000000000bad4b2 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl(std::shared_ptr<HPHP::FastCGIJob>, bool) ()
#38 0x0000000000badaad in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start() ()
#39 0x000000000167b6a7 in HPHP::AsyncFuncImpl::ThreadFunc(void*) ()
#40 0x00000000009a2e3e in HPHP::start_routine_wrapper(void*) ()
#41 0x00007fffef1fe0a4 in start_thread (arg=0x7fffd37ff700) at pthread_create.c:309
#42 0x00007fffee711c2d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
