### ISSUE TITLE
HHVM in FastCGI mode hangs randomly in an apparent deadlock between the OpenSSL extension and PostgreSQL which also uses OpenSSL

### ISSUE THREAD

**Issue by isegal** [facebook/hhvm#4165]
We are running in production using the nginx-FastCGI-hhvm setup and are experiencing occasional random lockups of hhvm process. It appears to be due to a deadlock from the interaction with openssl. We have collected GDB traces of the hanging threads below. Please let me know if I can help in any way. Unfortunately we do not have exact steps to reproduce due to the random nature, but we are able to collect more GDB information when it does happen, if needed.

Areas of interest and possible theory:

It appears that openssl_random_pseudo_bytes(), which calls openssl, causes the underlying libcrypto to invoke a callback that was established previously by PostgreSQL library as part of the lock portability callbacks for multi-threading of openssl.

Some information on the topic can be found here http://wiki.openssl.org/index.php/Manual:Threads(3)

If HHVM openssl extension does not establish these same callbacks, it may be causing the wrong callbacks to be called.

All worker threads except for one, hang in the following state:
```
Thread 65 (Thread 0x7faa047ff700 (LWP 453)):
 #0  0x00007faa1c1dbf2c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
 #1  0x00007faa1c1d7657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
 #2  0x00007faa1c1d7480 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0

 #3  0x00007faa0ffd4510 in ?? () from /usr/lib/libpq.so.5 <-- **appears to be a callback from openssl to postgres**

 #4  0x00007faa1ef9c9aa in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
 #5  0x00000000010d54e8 in HPHP::f_openssl_random_pseudo_bytes(int, HPHP::VRefParamValue const&) ()
 #6  0x0000000003ebf8b0 in ?? ()
 #7  0x0000000000ebe01e in enterTCHelper ()
 #8  0x0000000000d34a59 in HPHP::jit::x64::BackEnd::enterTCHelper(unsigned char*, HPHP::jit::TReqInfo&) ()
 #9  0x0000000000cdaba5 in HPHP::jit::MCGenerator::enterTC(unsigned char*, void*) ()
 #10 0x0000000000c3de5e in HPHP::ExecutionContext::enterVM(HPHP::ActRec*, HPHP::ExecutionContext::StackArgsState, HPHP::Resumable*, HPHP::ObjectData*) ()
 #11 0x0000000000c3e0cc in HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags) ()
 #12 0x0000000000c3e31a in HPHP::ExecutionContext::invokeUnit(HPHP::TypedValue*, HPHP::Unit const*) ()
 #13 0x0000000000972491 in HPHP::invoke_file(HPHP::String const&, bool, char const*) ()
 #14 0x0000000000974b2a in HPHP::include_impl_invoke(HPHP::String const&, bool, char const*) ()
 #15 0x0000000000a78fc9 in HPHP::hphp_invoke(HPHP::ExecutionContext*, std::string const&, bool, HPHP::Array const&, HPHP::VRefParamValue const&, std::string const&, std::string const&, bool&, std::string&, bool, bool, bool) ()
 #16 0x0000000000b55e74 in HPHP::HttpRequestHandler::executePHPRequest(HPHP::Transport*, HPHP::RequestURI&, HPHP::SourceRootInfo&, bool) ()
 #17 0x0000000000b56fb0 in HPHP::HttpRequestHandler::handleRequestImpl(HPHP::Transport*) ()
 #18 0x0000000000b57ad9 in HPHP::HttpRequestHandler::handleRequest(HPHP::Transport*) ()
 #19 0x0000000000b73bf9 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl(std::shared_ptr<HPHP::FastCGIJob>, bool) ()
 #20 0x0000000000b73e28 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJob(std::shared_ptr<HPHP::FastCGIJob>) ()
 #21 0x0000000000b72d98 in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start() ()
 #22 0x00000000015f9687 in HPHP::AsyncFuncImpl::ThreadFunc(void*) ()
 #23 0x00007faa1c1d5182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
 #24 0x00007faa1b6e1fbd in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

One worker hangs inside this state:
```
Thread 39 (Thread 0x7fa9813ff700 (LWP 539)):
 #0  0x00007faa1c1dbf2c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
 #1  0x00007faa1c1d7657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
 #2  0x00007faa1c1d7480 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0

 #3  0x00007faa0ffd4510 in ?? () from /usr/lib/libpq.so.5 <-- **the same callback as above. This appears to be by-design.**

 #4  0x00007faa1ef9c511 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
 #5  0x00007faa1f2ac79c in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.0.0
 #6  0x00007faa0ffd53bb in ?? () from /usr/lib/libpq.so.5
 #7  0x00007faa0ffc5b76 in PQconnectPoll () from /usr/lib/libpq.so.5
 #8  0x00007faa0ffc6b8e in ?? () from /usr/lib/libpq.so.5
 #9  0x00007faa0ffc7497 in PQconnectdb () from /usr/lib/libpq.so.5
 #10 0x00007faa101f0da2 in HPHP::f_pg_connect(HPHP::String const&, int) () from /etc/hhvm/ext/pgsql.so
 #11 0x0000000000bd8135 in void HPHP::Native::callFunc<false, false>(HPHP::Func const*, void*, HPHP::TypedValue*, HPHP::TypedValue&) ()
 #12 0x0000000000bd81dc in HPHP::TypedValue* HPHP::Native::functionWrapper<false, false>(HPHP::ActRec*) ()
 #13 0x00000000047f6e94 in ?? ()
 #14 0x0000000000ebe01e in enterTCHelper ()
 #15 0x0000000000d34a59 in HPHP::jit::x64::BackEnd::enterTCHelper(unsigned char*, HPHP::jit::TReqInfo&) ()
 #16 0x0000000000cdaba5 in HPHP::jit::MCGenerator::enterTC(unsigned char*, void*) ()
 #17 0x0000000000c3de5e in HPHP::ExecutionContext::enterVM(HPHP::ActRec*, HPHP::ExecutionContext::StackArgsState, HPHP::Resumable*, HPHP::ObjectData*) ()
 #18 0x0000000000c3e0cc in HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags) ()
 #19 0x0000000000c3e31a in HPHP::ExecutionContext::invokeUnit(HPHP::TypedValue*, HPHP::Unit const*) ()
 #20 0x0000000000972491 in HPHP::invoke_file(HPHP::String const&, bool, char const*) ()
 #21 0x0000000000974b2a in HPHP::include_impl_invoke(HPHP::String const&, bool, char const*) ()
 #22 0x0000000000a78fc9 in HPHP::hphp_invoke(HPHP::ExecutionContext*, std::string const&, bool, HPHP::Array const&, HPHP::VRefParamValue const&, std::string const&, std::string const&, bool&, std::string&, bool, bool, bool) ()
 #23 0x0000000000b55e74 in HPHP::HttpRequestHandler::executePHPRequest(HPHP::Transport*, HPHP::RequestURI&, HPHP::SourceRootInfo&, bool) ()
 #24 0x0000000000b56fb0 in HPHP::HttpRequestHandler::handleRequestImpl(HPHP::Transport*) ()
 #25 0x0000000000b57ad9 in HPHP::HttpRequestHandler::handleRequest(HPHP::Transport*) ()
 #26 0x0000000000b73bf9 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl(std::shared_ptr<HPHP::FastCGIJob>, bool) ()
 #27 0x0000000000b73e28 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJob(std::shared_ptr<HPHP::FastCGIJob>) ()
 #28 0x0000000000b72d98 in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start() ()
 #29 0x00000000015f9687 in HPHP::AsyncFuncImpl::ThreadFunc(void*) ()
 #30 0x00007faa1c1d5182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
 #31 0x00007faa1b6e1fbd in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

System info:

HipHop VM 3.3.0 (rel)
Compiler: tags/HHVM-3.3.0-0-g0a3cfb87b8a353fc7e1d15374f4adc413e37aba9
Repo schema: 9a391d9a03e15fccba1cde6d35c05b7cdd380238
Extension API: 20140829

```
Ubuntu 14.04 LTS (Trusty Tahr)

Amazon EC2 instance information:
instance-type: c3.8xlarge
kernel-id: aki-880531cd


Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    32
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Stepping:              4
CPU MHz:               2800.050
BogoMIPS:              5600.10
Hypervisor vendor:     Xen
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
NUMA node0 CPU(s):     0-31


Linux web4c 3.13.0-29-generic #53-Ubuntu SMP Wed Jun 4 21:00:20 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Packages

ii  libpq-dev                              9.3.5-0ubuntu0.14.04.1              amd64        header files for libpq5 (PostgreSQL library)
ii  libpq5                                 9.3.5-0ubuntu0.14.04.1              amd64        PostgreSQL C client library

ii  openssl                                1.0.1f-1ubuntu2.5                   amd64        Secure Sockets Layer toolkit - cryptographic utility

ii  hhvm                                   3.3.1~trusty                        amd64        HHVM virtual machine, runtime, and JIT for the PHP language


ii  nginx                                  1.6.2-2+trusty0                     all          small, powerful, scalable web/proxy server
ii  nginx-common                           1.6.2-2+trusty0                     all          small, powerful, scalable web/proxy server - common files
ii  nginx-full                             1.6.2-2+trusty0                     amd64        nginx web/proxy server (standard version)
```

**Comment by fredemmott** [comment]
cc @simonwelsh - any thoughts on the best way to aaddress this?

**Comment by isegal** [comment]
@fredemmott it turns out that the problem is due to double initialization of libcrypto and libssl.

There is a pull request to the postgres extension that should fix the problem since libpq provides a nice way of avoiding this issue.

https://github.com/PocketRent/hhvm-pgsql/pull/64

We are going to verify this fix in production. I'll keep you posted.

**Comment by isegal** [comment]
Update: PocketRent vendor has merged the pull request. We've been running the patch in production for three weeks now and the deadlock no longer happens.
