### ISSUE TITLE
:x:frag is not an XHPChild

### ISSUE THREAD

**Issue by unok-kun** [facebook/hhvm#4508]
Hack doesn't seem to recognize `:x:frag` as an `XHPChild`, except only in the bracket syntax. These are the command line outputs for different test files:

Simple bracket syntax: works as expected.
```
echo <p>{<x:frag>fsd<b>B</b>sdf</x:frag>}</p>;
```
```
<p>fsd<b>B</b>sdf</p>
```

`:x:frag` as function argument: catchable fatal error.
```
function paragraphize(XHPChild $c): :xhp {
    return <p>{$c}</p>;
}
echo paragraphize(<x:frag>fsd<b>B</b>sdf</x:frag>);
```
```
Catchable fatal error: Argument 1 passed to paragraphize() must implement interface XHPChild, xhp_x__frag given in /var/www/test/1.php on line 7
```

`:x:frag` as XHP attribute type: invalid attribute exception.
```
class :ns:elem extends :x:element {
    attribute XHPChild child;
}
echo <ns:elem child={<x:frag>fsd<b>B</b>sdf</x:frag>} />;
```
```
Notice: Undefined property: xhp_ns__elem::$source in /var/www/includes/xhp/core.php on line 1028
Fatal error: Uncaught exception 'XHPInvalidAttributeException' with message 'Invalid attribute `child` of type `xhp_x__frag` supplied to element `ns:elem`, expected `XHPChild`.' in /var/www/includes/xhp/core.php:587
Stack trace:
#0 /var/www/includes/xhp/core.php(339): xhp_x__composable_element->validateAttributeValue()
#1 /var/www/includes/xhp/core.php(354): xhp_x__composable_element->setAttribute()
#2 /var/www/includes/xhp/core.php(115): xhp_x__composable_element->setAttributes()
#3 /var/www/test/2.php(9): xhp_x__composable_element->__construct()
#4 {main}
```

The typechecker doesn't complain for any of the three cases, even if it's supposed to be a type error.

I'm using a build of HHVM on Fedora from sources checked out from master last week. The `xhp/php-lib` sources were checked out just yesterday.

**Comment by steelbrain** [comment]
I am not sure if this issue is valid any longer as XHP has evolved a lot since this issue was opened.
/cc @fredemmott

**Comment by fredemmott** [comment]
Doesn't seem to be a problem any more; if so, please file an issue at https://github.com/facebook/xhp-lib/issues with more information.

```
fred@hhvm-oss-bench:~/xhp-lib$ hhvm -m debug -v Eval.EnableHipHopSyntax=1
Welcome to HipHop Debugger!
Type "help" or "?" for a complete list of commands.

Note: no server specified, debugging local scripts only.
If you want to connect to a server, launch with "-h" or use:
  [m]achine [c]onnect <servername>

hphpd> require_once('vendor/autoload.php')
require_once('vendor/autoload.php')
hphpd> $x = <div />; $y = <x:frag />
$x = <div />; $y = <x:frag />
hphpd> = $x instanceof XHPChild
= $x instanceof XHPChild
true
hphpd> = $y instanceof XHPChild
= $y instanceof XHPChild
true
```
