### ISSUE TITLE
HHVM 3.3.2 breaks Composer

### ISSUE THREAD

**Issue by dzuelke** [facebook/hhvm#4531]
```
$ hhvm composer.phar 

Fatal error: Uncaught exception 'ErrorException' with message 'Object of class Symfony\Component\Console\Output\NullOutput could not be converted to string' in phar://composer.phar/bin/../src/../vendor/symfony/console/Symfony/Component/Console/Helper/Table.php:388
Stack trace:
#0 phar://composer.phar/bin/../src/../vendor/symfony/console/Symfony/Component/Console/Helper/Table.php(388): Composer\Util\ErrorHandler::handle()
#1 phar://composer.phar/bin/../src/../vendor/symfony/console/Symfony/Component/Console/Helper/Table.php(69): Symfony\Component\Console\Helper\Table::initStyles()
#2 phar://composer.phar/bin/../src/../vendor/symfony/console/Symfony/Component/Console/Helper/TableHelper.php(38): Symfony\Component\Console\Helper\Table->__construct()
#3 phar://composer.phar/bin/../src/../vendor/symfony/console/Symfony/Component/Console/Application.php(955): Symfony\Component\Console\Helper\TableHelper->__construct()
#4 phar://composer.phar/bin/../src/../src/Composer/Console/Application.php(314): Symfony\Component\Console\Application->getDefaultHelperSet()
#5 phar://composer.phar/bin/../src/../vendor/symfony/console/Symfony/Component/Console/Application.php(88): Composer\Console\Application->getDefaultHelperSet()
#6 phar://composer.phar/bin/../src/../src/Composer/Console/Application.php(69): Symfony\Component\Console\Application->__construct()
#7 phar://composer.phar/bin/composer(42): Composer\Console\Application->__construct()
#8 /app/composer.phar(24): include()
#9 {main}
```

Works just fine with 3.3.1 and 3.4.2.

**Comment by Majkl578** [comment]
What version of Composer?
Could you provide simple repro script (or at least something that could be run without setting tons of dependencies)?

**Comment by dzuelke** [comment]
1.0.0-alpha9 has the issue for example, @Majkl578

**Comment by GrahamCampbell** [comment]
You should probably use the latest dev release of composer.

**Comment by dzuelke** [comment]
The latest dev has the same issue.

**Comment by dzuelke** [comment]
And like I said, it works on HHVM 3.4.2 and 3.3.1. Only 3.3.2 seems affected.

**Comment by dzuelke** [comment]
The code in question (the `Table` class in Symfony) is not touching the `NullOutput` object in line 388. Something fishy is going on.

**Comment by dzuelke** [comment]
With 3.3.1:

```
~ $ curl -sS https://getcomposer.org/installer | php
#!/usr/bin/env php
All settings correct for using Composer
Downloading...

Composer successfully installed to: /app/composer.phar
Use it: php composer.phar
~ $ hhvm --version
HipHop VM 3.3.1 (rel)
Compiler: tags/HHVM-3.3.1-0-ge0c98e21167b425dddf1fc9efe78c9f7a36db268
Repo schema: f53e1743f31a2dee70c46aa66fb1b321c3e97c10
Extension API: 20140829
~ $ hhvm composer.phar 
   ______
  / ____/___  ____ ___  ____  ____  ________  _____
 / /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
/ /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /
\____/\____/_/ /_/ /_/ .___/\____/____/\___/_/
                    /_/
Composer version 1.0-dev (ddc1d377d7e07625cc1d0532dbbca881af141ad2) 2015-01-01 20:54:37

Usage:
 [options] command [arguments]

Options:
 --help (-h)           Display this help message.
 --quiet (-q)          Do not output any message.
 --verbose (-v|vv|vvv) Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug.
 --version (-V)        Display this application version.
 --ansi                Force ANSI output.
 --no-ansi             Disable ANSI output.
 --no-interaction (-n) Do not ask any interactive question.
 --profile             Display timing and memory usage information
 --working-dir (-d)    If specified, use the given directory as working directory.

Available commands:
 about            Short information about Composer
 archive          Create an archive of this composer package
 browse           Opens the package's repository URL or homepage in your browser.
 clear-cache      Clears composer's internal package cache.
 clearcache       Clears composer's internal package cache.
 config           Set config options
 create-project   Create new project from a package into given directory.
 depends          Shows which packages depend on the given package
 diagnose         Diagnoses the system to identify common errors.
 dump-autoload    Dumps the autoloader
 dumpautoload     Dumps the autoloader
 global           Allows running commands in the global composer dir ($COMPOSER_HOME).
 help             Displays help for a command
 home             Opens the package's repository URL or homepage in your browser.
 init             Creates a basic composer.json file in current directory.
 install          Installs the project dependencies from the composer.lock file if present, or falls back on the composer.json.
 licenses         Show information about licenses of dependencies
 list             Lists commands
 remove           Removes a package from the require or require-dev
 require          Adds required packages to your composer.json and installs them
 run-script       Run the scripts defined in composer.json.
 search           Search for packages
 self-update      Updates composer.phar to the latest version.
 selfupdate       Updates composer.phar to the latest version.
 show             Show information about packages
 status           Show a list of locally modified packages
 update           Updates your dependencies to the latest version according to composer.json, and updates the composer.lock file.
 validate         Validates a composer.json
```

With 3.4.2:

```
~ $ curl -sS https://getcomposer.org/installer | php
#!/usr/bin/env php
All settings correct for using Composer
Downloading...

Composer successfully installed to: /app/composer.phar
Use it: php composer.phar
~ $ hhvm --version
HipHop VM 3.4.2 (rel)
Compiler: tags/HHVM-3.4.2-0-g40d85d7386b3342ab848fc45c6892433c89ef5b2
Repo schema: 13cba877c4300d1d0481b3f40eb128a5115d4e08
Extension API: 20140829
~ $ hhvm composer.phar 
   ______
  / ____/___  ____ ___  ____  ____  ________  _____
 / /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
/ /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /
\____/\____/_/ /_/ /_/ .___/\____/____/\___/_/
                    /_/
Composer version 1.0-dev (ddc1d377d7e07625cc1d0532dbbca881af141ad2) 2015-01-01 20:54:37

Usage:
 [options] command [arguments]

Options:
 --help (-h)           Display this help message.
 --quiet (-q)          Do not output any message.
 --verbose (-v|vv|vvv) Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug.
 --version (-V)        Display this application version.
 --ansi                Force ANSI output.
 --no-ansi             Disable ANSI output.
 --no-interaction (-n) Do not ask any interactive question.
 --profile             Display timing and memory usage information
 --working-dir (-d)    If specified, use the given directory as working directory.

Available commands:
 about            Short information about Composer
 archive          Create an archive of this composer package
 browse           Opens the package's repository URL or homepage in your browser.
 clear-cache      Clears composer's internal package cache.
 clearcache       Clears composer's internal package cache.
 config           Set config options
 create-project   Create new project from a package into given directory.
 depends          Shows which packages depend on the given package
 diagnose         Diagnoses the system to identify common errors.
 dump-autoload    Dumps the autoloader
 dumpautoload     Dumps the autoloader
 global           Allows running commands in the global composer dir ($COMPOSER_HOME).
 help             Displays help for a command
 home             Opens the package's repository URL or homepage in your browser.
 init             Creates a basic composer.json file in current directory.
 install          Installs the project dependencies from the composer.lock file if present, or falls back on the composer.json.
 licenses         Show information about licenses of dependencies
 list             Lists commands
 remove           Removes a package from the require or require-dev
 require          Adds required packages to your composer.json and installs them
 run-script       Run the scripts defined in composer.json.
 search           Search for packages
 self-update      Updates composer.phar to the latest version.
 selfupdate       Updates composer.phar to the latest version.
 show             Show information about packages
 status           Show a list of locally modified packages
 update           Updates your dependencies to the latest version according to composer.json, and updates the composer.lock file.
 validate         Validates a composer.json
```

With 3.3.2:

```
~ $ curl -sS https://getcomposer.org/installer | php
#!/usr/bin/env php
All settings correct for using Composer
Downloading...

Composer successfully installed to: /app/composer.phar
Use it: php composer.phar
$ hhvm --version
HipHop VM 3.3.2 (rel)
Compiler: tags/HHVM-3.3.2-1-ge4f1fd1fe259695f73b37f74aacaa94bb52a5148
Repo schema: 088a95400e485900d2cbbb73703e2daf179a1d93
Extension API: 20140829
~ $ hhvm composer.phar 

Fatal error: Uncaught exception 'ErrorException' with message 'Object of class Symfony\Component\Console\Output\NullOutput could not be converted to string' in phar://composer.phar/bin/../src/../vendor/symfony/console/Symfony/Component/Console/Helper/Table.php:388
Stack trace:
#0 phar://composer.phar/bin/../src/../vendor/symfony/console/Symfony/Component/Console/Helper/Table.php(388): Composer\Util\ErrorHandler::handle()
#1 phar://composer.phar/bin/../src/../vendor/symfony/console/Symfony/Component/Console/Helper/Table.php(69): Symfony\Component\Console\Helper\Table::initStyles()
#2 phar://composer.phar/bin/../src/../vendor/symfony/console/Symfony/Component/Console/Helper/TableHelper.php(38): Symfony\Component\Console\Helper\Table->__construct()
#3 phar://composer.phar/bin/../src/../vendor/symfony/console/Symfony/Component/Console/Application.php(955): Symfony\Component\Console\Helper\TableHelper->__construct()
#4 phar://composer.phar/bin/../src/../src/Composer/Console/Application.php(325): Symfony\Component\Console\Application->getDefaultHelperSet()
#5 phar://composer.phar/bin/../src/../vendor/symfony/console/Symfony/Component/Console/Application.php(88): Composer\Console\Application->getDefaultHelperSet()
#6 phar://composer.phar/bin/../src/../src/Composer/Console/Application.php(69): Symfony\Component\Console\Application->__construct()
#7 phar://composer.phar/bin/composer(42): Composer\Console\Application->__construct()
#8 /app/composer.phar(25): include()
#9 {main}
```

**Comment by jwatzman** [comment]
A bunch of stuff went into 3.3.2 that probably shouldn't have (some of it my fault, some of it not). Entirely possible we missed a fix for one of those fixes that was fixed in master before it was cut for 3.4. I'll take a look.

**Comment by dzuelke** [comment]
Thanks @jwatzman :)

**Comment by jwatzman** [comment]
I can repro with 3.3.2. I just also got a failure with 3.3.1, but that's likely due to some local issue with incremental builds not quite working right. Doing a rebuild now, and then I'll try to bisect tomorrow.

So no news yet, but am (slowly) looking into it :)

**Comment by jwatzman** [comment]
Pretty sure the missing rev is e9ff7f4f684f0c85b50b9461f06ca551b974100e

**Comment by dzuelke** [comment]
![almost there](http://stream1.gifsoup.com/view5/4659483/almost-there-o.gif)

**Comment by jwatzman** [comment]
Will merge that and start rolling `3.3.3` later this week (probably tomorrow). We're also figuring out how to test our LTS/stable branches better -- master is well-tested, but stable releases are "I ran some tests on my laptop, I guess it looks good, shipit" right now.

**Comment by dzuelke** [comment]
:+1:

**Comment by wjywbs** [comment]
3.3.2 crashes about 25 tests without https://github.com/facebook/hhvm/commit/15ed4a31a73eede73345641b801be0f49d5d1c23. For example, test/quick/traits.php

```
Type: Segmentation fault
Runtime: hhvm
Version: tags/HHVM-3.3.2-0-g9046034b8d82b06e9feb75b72e2b0106a2707c2c
DebuggerCount: 0

Arguments: test/quick/traits.php
ThreadType: CLI

# 0  __restore_rt at sigaction.c:0
# 1  HPHP::deepInitHelper(HPHP::TypedValue*, HPHP::TypedValueAux const*, unsigned long) at ./hhvm/hhvm:0
# 2  HPHP::newInstance(HPHP::Class*) at ./hhvm/hhvm:0
# 3  HPHP::jit::x64::BackEnd::enterTCHelper(unsigned char*, HPHP::jit::TReqInfo&) at ./hhvm/hhvm:0
# 4  HPHP::jit::MCGenerator::enterTC(unsigned char*, void*) at ./hhvm/hhvm:0
# 5  HPHP::ExecutionContext::enterVM(HPHP::ActRec*, HPHP::ExecutionContext::StackArgsState, HPHP::Resumable*, HPHP::ObjectData*) at ./hhvm/hhvm:0
# 6  HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags) at ./hhvm/hhvm:0
# 7  HPHP::ExecutionContext::invokeUnit(HPHP::TypedValue*, HPHP::Unit const*) at ./hhvm/hhvm:0
# 8  HPHP::invoke_file(HPHP::String const&, bool, char const*) at builtin-functions.cpp:0
# 9  HPHP::include_impl_invoke(HPHP::String const&, bool, char const*) at ./hhvm/hhvm:0
# 10 HPHP::hphp_invoke(HPHP::ExecutionContext*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, HPHP::Array const&, HPHP::VRefParamValue const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool, bool, bool) at ./hhvm/hhvm:0
# 11 HPHP::hphp_invoke_simple(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) at ./hhvm/hhvm:0
# 12 HPHP::execute_program_impl(int, char**) at program-functions.cpp:0
# 13 HPHP::execute_program(int, char**) at ./hhvm/hhvm:0
# 14 main at ./hhvm/hhvm:0
# 15 __libc_start_main at /lib64/libc.so.6:0
# 16 _start at ./hhvm/hhvm:0
```

**Comment by jwatzman** [comment]
Interesting -- I was pretty confident I ran quick tests on `3.3.2` before release, but clearly not :( :( Definitely need better process around this. Quick tests do pass with that diff, thankfully.

Waiting on one or two other things, then will roll `3.3.3` with the fix. Again, thanks for the report!

**Comment by JoelMarcey** [comment]
@jwatzman We should pass all `quick` tests before a diff gets pushed to GitHub, so this seems odd. 

That said, not all `slow` tests necessarily pass. I am working on reducing that number which was about 6-12 on my system, depending on the day of the week :/

**Comment by fredemmott** [comment]
@JoelMarcey : the release branches aren't pushed from fbcode to github; they're worked on here directly

**Comment by JoelMarcey** [comment]
@fredemmott Right, but at some point those diffs would have had to go through our internal process, right? These diffs make up the release branches. Unless we are cherry-picking new diffs directly into the release branches.

**Comment by jwatzman** [comment]
Cherry picking individual revs can still cause problems -- for example, the issue here is that a rev that was good when it went in implicitly depended on a bugfix in a rev that didn't get picked (that we didn't even know about).

**Comment by jwatzman** [comment]
`3.3.3` is tagged and will be building over the course of the next few days (trusty should be out shortly, the rest to follow).
