### ISSUE TITLE
Test framework run should remove incomplete downloads

### ISSUE THREAD

**Issue by Stelian** [facebook/hhvm#4584]
When install runs for a new framework, there is a chance that a timeout will be hit due to, for example, github being overloaded. The Framework.php correctly throws a timeout exception, but it should remove all traces of the attempted project, otherwise things will break on a subsequent run.

```
 - Installing symfony/config (2.5.x-dev c7309e3)
    Cloning c7309e33b719433d5cf3845d0b5b9608609d8c8e
exception 'TimeoutException' with message 'Hit timeout reading from proc: /var/www/hhvm/hphp/test/frameworks/../../hhvm/hhvm -v Repo.Local.Mode=-- -v Repo.Central.Path=/tmp/framework-testpYvvRt --config /var/www/hhvm/hphp/test/frameworks/php.ini -v ResourceLimit.SocketDefaultTimeout=30 /var/www/hhvm/hphp/test/frameworks/composer.phar install --dev' in /var/www/hhvm/hphp/test/frameworks/utils.php:414
Stack trace:
#0 /var/www/hhvm/hphp/test/frameworks/utils.php(354): run_install_impl()
#1 /var/www/hhvm/hphp/test/frameworks/Framework.php(902): run_install()
#2 /var/www/hhvm/hphp/test/frameworks/Framework.php(619): Framework->installDependencies()
#3 /var/www/hhvm/hphp/test/frameworks/Framework.php(119): Framework->install()
#4 /var/www/hhvm/hphp/test/frameworks/run.php(129): Framework->__construct()
#5 /var/www/hhvm/hphp/test/frameworks/run.php(679): prepare()
#6 /var/www/hhvm/hphp/test/frameworks/run.php(686): main()
#7 {main}ERROR: Retries exceeded: /var/www/hhvm/hphp/test/frameworks/../../hhvm/hhvm -v Repo.Local.Mode=-- -v Repo.Central.Path=/tmp/framework-testpYvvRt --config /var/www/hhvm/hphp/test/frameworks/php.ini -v ResourceLimit.SocketDefaultTimeout=30 /var/www/hhvm/hphp/test/frameworks/composer.phar install --dev
stelian@home:/var/www/hhvm/hphp/test/frameworks$ hhvm run.php -v silex
Generated INI string: 
Script running...Be patient as some frameworks take a while with a debug build of HHVM
silex already installed.
0 files were blacklisted (auto fail) silex...
0 files were clownylisted (no-op/no run) silex...
0 files were flakeylisted (no-op/no run) silex...
Using phpunit xml file in: /var/www/hhvm/hphp/test/frameworks/framework_downloads/silex/phpunit.xml.dist
General test command for: silex is: /var/www/hhvm/hphp/test/frameworks/../../hhvm/hhvm -v Repo.Local.Mode=-- -v Repo.Central.Path=/tmp/framework-testPgwcqT --config /var/www/hhvm/hphp/test/frameworks/php.ini -c /var/www/hhvm/hphp/test/frameworks/.generated.php.ini /var/www/hhvm/hphp/test/frameworks/vendor/bin/phpunit --debug  -c /var/www/hhvm/hphp/test/frameworks/framework_downloads/silex/phpunit.xml.dist '%test%' 2>&1
Command used to find the test files and tests for silex: /var/www/hhvm/hphp/test/frameworks/../../hhvm/hhvm -v Repo.Local.Mode=-- -v Repo.Central.Path=/tmp/framework-testmmi2Cn --config /var/www/hhvm/hphp/test/frameworks/php.ini TestFinder.php  --framework-name silex --tests-file /var/www/hhvm/hphp/test/frameworks/results/silex.tests --test-files-file /var/www/hhvm/hphp/test/frameworks/results/silex.testfiles --test-path /var/www/hhvm/hphp/test/frameworks/framework_downloads/silex --test-file-pattern "/.*(\.phpt|Test[\d]*\.php|test[\d]*\.php)$/" --config-file /var/www/hhvm/hphp/test/frameworks/framework_downloads/silex/phpunit.xml.dist --test-find-mode reflection
ERROR: Could not get tests for silex
```

**Comment by JoelMarcey** [comment]
Internal diff: D1769670

**Comment by JoelMarcey** [comment]
closed by: https://github.com/facebook/hhvm/commit/518c942fe5b284bde672f824523a975a8b016e4a
