### ISSUE TITLE
COMPILATION ERROR in OSX 10.10

### ISSUE THREAD

**Issue by eriknyk** [facebook/hhvm#5447]
```
$ brew install hhvm --HEAD
```

Output

```
==> Installing hhvm from mcuadros/homebrew-hhvm
==> Cloning https://github.com/facebook/hhvm.git
Updating /Library/Caches/Homebrew/hhvm--git
Synchronizing submodule url for 'folly/src'
Synchronizing submodule url for 'mcrouter/src'
Synchronizing submodule url for 'proxygen/src'
Synchronizing submodule url for 're2/src'
Synchronizing submodule url for 'squangle/src'
Synchronizing submodule url for 'thrift/src'
Synchronizing submodule url for 'webscalesqlclient/webscalesql-5.6'
==> Checking out branch master
==> Downloading https://rawgit.com/mcuadros/homebrew-hhvm/master/patches/head/userland_path.diff
Already downloaded: /Library/Caches/Homebrew/hhvm--patch-cd2be78a9beba55a2deb61915ebc2752c060608fc663d2e93b81f2989d352d5d.diff
==> Patching
patching file hphp/runtime/base/emulate-zend.cpp
patching file hphp/runtime/base/program-functions.cpp
Hunk #1 succeeded at 1365 (offset 20 lines).
==> Cloning https://github.com/hhvm/hhvm-third-party.git
Updating /Library/Caches/Homebrew/hhvm--third-party--git
==> Checking out branch master
==> cmake . -DBOOST_INCLUDEDIR=/usr/local/opt/boost/include -DBOOST_LIBRARYDIR=/usr/local/opt/boost/lib -DCCLIE
==> make -j4
/usr/bin/ar cq libhphp_proxygen.a  CMakeFiles/hphp_proxygen.dir/lib/http/codec/CodecProtocol.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/compress/experimental/hpack9/HPACKCodec.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/compress/experimental/hpack9/HPACKDecoder.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/compress/experimental/hpack9/HPACKEncoder.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/compress/experimental/hpack9/Huffman.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/compress/experimental/hpack9/StaticHeaderTable.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/compress/GzipHeaderCodec.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/compress/HeaderTable.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/compress/HPACKCodec.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/compress/HPACKContext.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/compress/HPACKDecodeBuffer.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/compress/HPACKDecoder.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/compress/HPACKEncodeBuffer.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/compress/HPACKEncoder.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/compress/HPACKHeader.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/compress/Huffman.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/compress/Logging.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/compress/StaticHeaderTable.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/ErrorCode.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/experimental/HTTP2Codec.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/experimental/HTTP2Constants.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/experimental/HTTP2Framer.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/FlowControlFilter.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/HTTP1xCodec.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/HTTPChecks.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/HTTPCodecFilter.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/HTTPSettings.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/SettingsId.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/SPDYCodec.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/SPDYConstants.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/SPDYUtil.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/codec/TransportDirection.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/HTTPConnector.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/HTTPConstants.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/HTTPException.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/HTTPHeaders.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/HTTPMessage.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/HTTPMethod.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/ProxygenErrorEnum.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/RFC2616.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/session/ByteEvents.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/session/ByteEventTracker.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/session/CodecErrorResponseHandler.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/session/HTTP2PriorityQueue.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/session/HTTPDirectResponseHandler.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/session/HTTPDownstreamSession.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/session/HTTPErrorPage.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/session/HTTPEvent.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/session/HTTPSession.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/session/HTTPSessionAcceptor.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/session/HTTPTransaction.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/session/HTTPTransactionEgressSM.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/session/HTTPTransactionIngressSM.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/session/HTTPUpstreamSession.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/session/SimpleController.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/session/TransportFilter.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/Window.cpp.o CMakeFiles/hphp_proxygen.dir/lib/services/RequestWorker.cpp.o CMakeFiles/hphp_proxygen.dir/lib/services/Service.cpp.o CMakeFiles/hphp_proxygen.dir/lib/services/WorkerThread.cpp.o CMakeFiles/hphp_proxygen.dir/lib/utils/AsyncTimeoutSet.cpp.o CMakeFiles/hphp_proxygen.dir/lib/utils/CryptUtil.cpp.o CMakeFiles/hphp_proxygen.dir/lib/utils/Exception.cpp.o CMakeFiles/hphp_proxygen.dir/lib/utils/HTTPTime.cpp.o CMakeFiles/hphp_proxygen.dir/lib/utils/Logging.cpp.o CMakeFiles/hphp_proxygen.dir/lib/utils/ParseURL.cpp.o CMakeFiles/hphp_proxygen.dir/lib/utils/ZlibStreamCompressor.cpp.o CMakeFiles/hphp_proxygen.dir/lib/utils/ZlibStreamDecompressor.cpp.o CMakeFiles/hphp_proxygen.dir/external/http_parser/http_parser_cpp.cpp.o CMakeFiles/hphp_proxygen.dir/lib/http/HTTPCommonHeaders.cpp.o
/usr/bin/ranlib libhphp_proxygen.a
/usr/local/Cellar/cmake/3.2.2/bin/cmake -E cmake_progress_report /usr/local/Cellar/hhvm/HEAD/src/CMakeFiles  19 20 21 22 23
[  5%] Built target hphp_proxygen
make: *** [all] Error 2
/usr/local/Library/Homebrew/build.rb:181:in `dump': can't dump anonymous class #<Module:0x007fca8b1cd808>::Hhvm (TypeError)
	from /usr/local/Library/Homebrew/build.rb:181:in `rescue in <main>'
	from /usr/local/Library/Homebrew/build.rb:167:in `<main>'
Error: Suspicious failure
```

Please Help!

Regards

**Comment by denji** [comment]
You can display a more detailed output of construction:
```
$ brew install hhvm --HEAD --verbose
```

**Comment by fredemmott** [comment]
We don't currently support OSX, and we do not support third-party build/packaging systems. It looks like you want to file an issue here: https://github.com/mcuadros/homebrew-hhvm
