### ISSUE TITLE
Request Hangs and High CPU Usage on HHVM Process

### ISSUE THREAD

**Issue by Ghan04** [facebook/hhvm#5504]
I'm having an issue similar to this one: https://github.com/facebook/hhvm/issues/2069

I have a CentOS 7 VM setup with Nginx + MariaDB 10.0.19 and I'm using fastcgi to pass PHP requests to HHVM, but randomly when I request web pages, the request will hang for 20 seconds or more (and at the same time, the HHVM process goes to 100% CPU usage). After that, it will usually finish processing and return, but occasionally it will throw me a gateway timeout after nginx is finally tired of waiting for a reply from the backend.

I have captured a gdb trace from the hhvm process while a request was hung using the notes in the other issue thread. Let me know if there's way to resolve this or if you need more information.

Thanks!

```
Thread 8 (Thread 0x7f2f84fff700 (LWP 28386)):
#0  0x00007f2f96ba4783 in epoll_wait () from /lib64/libc.so.6
#1  0x00007f2f985a7803 in epoll_dispatch () from /lib64/libevent-2.0.so.5
#2  0x00007f2f985933ea in event_base_loop () from /lib64/libevent-2.0.so.5
#3  0x000000000272a296 in folly::EventBase::loopBody(int) ()
#4  0x000000000272c7f9 in folly::EventBase::loopForever() ()
#5  0x00000000022177aa in proxygen::WorkerThread::runLoop() ()
#6  0x00000000022179ef in std::thread::_Impl<std::_Bind_simple<proxygen::WorkerThread::start()::{lambda()#1} ()> >::_M_run() ()
#7  0x00007f2f9743c1e0 in ?? () from /lib64/libstdc++.so.6
#8  0x00007f2f97695df5 in start_thread () from /lib64/libpthread.so.0
#9  0x00007f2f96ba41ad in clone () from /lib64/libc.so.6

Thread 7 (Thread 0x7f2f83fff700 (LWP 28398)):
#0  0x00007f2f97699705 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x0000000001f85b88 in HPHP::SynchronizableMulti::waitImpl(int, int, bool, timespec*) ()
#2  0x0000000000ebafaa in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start() ()
#3  0x0000000001f842b7 in HPHP::AsyncFuncImpl::ThreadFunc(void*) ()
#4  0x0000000000d19107 in HPHP::start_routine_wrapper(void*) ()
#5  0x00007f2f97695df5 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f2f96ba41ad in clone () from /lib64/libc.so.6

Thread 6 (Thread 0x7f2f7e3ff700 (LWP 28399)):
#0  0x00007f2f97699705 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x0000000001f85b88 in HPHP::SynchronizableMulti::waitImpl(int, int, bool, timespec*) ()
#2  0x0000000000ebafaa in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start() ()
#3  0x0000000001f842b7 in HPHP::AsyncFuncImpl::ThreadFunc(void*) ()
#4  0x0000000000d19107 in HPHP::start_routine_wrapper(void*) ()
#5  0x00007f2f97695df5 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f2f96ba41ad in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x7f2f747ff700 (LWP 28401)):
#0  0x00007f2f97699705 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x0000000001f85b88 in HPHP::SynchronizableMulti::waitImpl(int, int, bool, timespec*) ()
#2  0x0000000000ebafaa in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start() ()
#3  0x0000000001f842b7 in HPHP::AsyncFuncImpl::ThreadFunc(void*) ()
#4  0x0000000000d19107 in HPHP::start_routine_wrapper(void*) ()
#5  0x00007f2f97695df5 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f2f96ba41ad in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x7f2f75fff700 (LWP 28402)):
#0  0x00007f2f97699705 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x0000000001f85b88 in HPHP::SynchronizableMulti::waitImpl(int, int, bool, timespec*) ()
#2  0x0000000000ebafaa in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start() ()
```

server.ini

```
; php options

pid = /var/run/hhvm/pid

; hhvm specific

hhvm.server.port = 9000
hhvm.server.type = fastcgi
hhvm.log.level = Verbose
hhvm.log.use_log_file = true
hhvm.log.file = /var/log/hhvm/error.log
hhvm.repo.central.path = /var/run/hhvm/hhvm.hhbc
hhvm.server.user = admin
hhvm.mysql.socket = /tmp/mysql.sock
```

HHVM error.log after a hung request

```
receiving css.php
f_is_file/1108: No such file or directory
runtime/ext_mysql: successfully executed [0ms] [SET @@session.sql_mode='STRICT_ALL_TABLES']
receiving proxy.php
runtime/ext_mysql: successfully executed [0ms] [SET @@session.sql_mode='STRICT_ALL_TABLES']
f_rewind/337: Resource temporarily unavailable
f_unlink/1612: No such file or directory
receiving css.php
receiving index.php
runtime/ext_mysql: successfully executed [0ms] [SET @@session.sql_mode='STRICT_ALL_TABLES']
receiving index.php
runtime/ext_mysql: successfully executed [0ms] [SET @@session.sql_mode='STRICT_ALL_TABLES']
receiving index.php
runtime/ext_mysql: successfully executed [0ms] [SET @@session.sql_mode='STRICT_ALL_TABLES']
receiving index.php
runtime/ext_mysql: successfully executed [0ms] [SET @@session.sql_mode='STRICT_ALL_TABLES']
f_is_file/1108: No such file or directory
receiving index.php
runtime/ext_mysql: successfully executed [0ms] [SET @@session.sql_mode='STRICT_ALL_TABLES']
receiving css.php
receiving css.php
receiving proxy.php
runtime/ext_mysql: successfully executed [0ms] [SET @@session.sql_mode='STRICT_ALL_TABLES']
receiving proxy.php
runtime/ext_mysql: successfully executed [1ms] [SET @@session.sql_mode='STRICT_ALL_TABLES']
receiving css.php
receiving index.php
runtime/ext_mysql: successfully executed [0ms] [SET @@session.sql_mode='STRICT_ALL_TABLES']
receiving deferred.php
runtime/ext_mysql: successfully executed [0ms] [SET @@session.sql_mode='STRICT_ALL_TABLES']
```

**Comment by bvidinli** [comment]
Similar situation: https://github.com/facebook/hhvm/issues/5081
Let me know if you find some way

**Comment by ksaltik** [comment]
Same situation and can't get any answer from developers. 

Read it 

https://www.redy.host/blog/drupal-8-stress-test-round-3
In our previous test (Making Drupal 8 Fly), this same setup (but using HHVM) was maxing out at 13542 responses received (the test stopped counting responses strictly at 1 minute 00 seconds since the test start) and the average response time was 4426ms. As you see in the picture above, PHP7 was able to outperform HHVM by serving 32.7% more responses in 33.3% less average response time.

As mentioned in this article after one minute HHVMstarts to eat CPU it doesn't matter how many cores you have.

.they don't accept this issue because accepting this issue will make them vulnerable to attacks and recent failures of Facebook shows the problem is obvious.

**Comment by fredemmott** [comment]
Deleted @ksaltik's comment for spamming it all over the place.

**Comment by Orvid** [comment]
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.
