### ISSUE TITLE
Really, really easy to make HH\Asio\curl_exec() segfault or raise notices

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#5749]
Assigning to myself to give more details :)

**Comment by fredemmott** [comment]
```Hack
<?hh

HH\Asio\curl_exec('http://www.example.com')->getWaitHandle()->join();
```

No jit: all good.

With jit:

```
Notice: Object of class HH\ExternalThreadEventWaitHandle could not be converted to int in /home/fredemmott/hhtest/test.php on line 3
```

many, many times. Not reproing the segfault on an FB machine yet.

cc @sgolemon

**Comment by fredemmott** [comment]
intermittent segfault repro:

```Hack
<?hh

error_reporting(E_ALL ^ E_NOTICE);

async function main() {
  $handles = Vector { };
  for ($i = 0; $i < 10; ++$i) {
    $handles[] = HH\Asio\curl_exec(curl_init('http://www.example.com'));
  }
  await HH\Asio\v($handles);
}

main()->getWaitHandle()->join();
```

Again, must be ran with JIT on. Output:

```
E0720 09:31:27.000000 1078888 folly/io/async/EventHandler.cpp:91] EventBase: failed to register event handler for fd 13: No such file or directory
E0720 09:31:27.000000 1078888 folly/io/async/EventHandler.cpp:91] EventBase: failed to register event handler for fd 13: No such file or directory
E0720 09:31:27.000000 1078888 folly/io/async/EventHandler.cpp:91] EventBase: failed to register event handler for fd 13: No such file or directory
E0720 09:31:27.000000 1078888 folly/io/async/EventHandler.cpp:91] EventBase: failed to register event handler for fd 13: No such file or directory
E0720 09:31:27.000000 1078888 folly/io/async/EventHandler.cpp:91] EventBase: failed to register event handler for fd 13: No such file or directory
E0720 09:31:27.000000 1078888 folly/io/async/EventHandler.cpp:91] EventBase: failed to register event handler for fd 13: No such file or directory
E0720 09:31:27.000000 1078888 folly/io/async/EventHandler.cpp:91] EventBase: failed to register event handler for fd 13: No such file or directory
E0720 09:31:27.000000 1078888 folly/io/async/EventHandler.cpp:91] EventBase: failed to register event handler for fd 13: No such file or directory
E0720 09:31:27.000000 1078888 folly/io/async/EventHandler.cpp:91] EventBase: failed to register event handler for fd 13: No such file or directory
hhvm: /home/engshare/third-party2/libevent/1.4.14b_hphp/src/libevent-1.4.14b-stable/event.c:263: event_base_free: Assertion `(((&base->eventqueue)->tqh_first) == ((void *)0))' failed.
Core dumped: Aborted
```

Core dump didn't give me a usable backtrace :(

**Comment by fredemmott** [comment]
Reliably aborts on an OSS build, unless attached to gdb. gdb is intermittent.

HHVM 3.8-dbg package on trusty:


```
[err] evmap.c:367: Assertion nread >= 0 failed in evmap_io_del

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffe0bff700 (LWP 21526)]
0x00007ffff0a34cc9 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff0a34cc9 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff0a380d8 in __GI_abort () at abort.c:89
#2  0x00007ffff22b651a in ?? () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
#3  0x00007ffff22b688b in event_errx ()
   from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
#4  0x00007ffff22b5bb7 in evmap_io_del ()
   from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
#5  0x00007ffff22a72da in event_base_loop ()
   from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
#6  0x0000000002e1c20d in folly::EventBase::loopBody (
    this=this@entry=0x7fffe197f800, flags=flags@entry=0)
    at /tmp/tmp.Q3me4RhiuU/third-party/folly/folly/io/async/EventBase.cpp:335
#7  0x0000000002e1cc14 in folly::EventBase::loop (this=this@entry=0x7fffe197f800)
    at /tmp/tmp.Q3me4RhiuU/third-party/folly/folly/io/async/EventBase.cpp:286
#8  0x0000000002e1f270 in folly::EventBase::loopForever (this=0x7fffe197f800)
    at /tmp/tmp.Q3me4RhiuU/third-party/folly/folly/io/async/EventBase.cpp:434
#9  0x00000000023473e9 in operator() (__closure=<optimized out>)
    at /tmp/tmp.Q3me4RhiuU/hphp/runtime/ext/asio/socket-event.cpp:10
#10 _M_invoke<> (this=<optimized out>) at /usr/include/c++/4.8/functional:1732
#11 operator() (this=<optimized out>) at /usr/include/c++/4.8/functional:1720
#12 std::thread::_Impl<std::_Bind_simple<HPHP::AsioEventBase::AsioEventBase()::__lambda27()> >::_M_run(void) (this=<optimized out>) at /usr/include/c++/4.8/thread:115
#13 0x00007ffff1390a40 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#14 0x00007ffff15eb182 in start_thread (arg=0x7fffe0bff700) at pthread_create.c:312
#15 0x00007ffff0af847d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by fredemmott** [comment]
This is a regression - works fine in 3.7 and below.

**Comment by fredemmott** [comment]
bisects to b59f783e009c43cd9648859884a086acb41c044f

**Comment by fredemmott** [comment]
'async' should not be used for native functions.

Notice: Object of class HH\ExternalThreadEventWaitHandle could not be converted to int

As it's 'async', we wrap the impl return in Awaitable - but the impl return is already an Awaitable.

**Comment by fredemmott** [comment]
fix up soon.
