### ISSUE TITLE
hhvm segmentation fault, possibly related to jemalloc

### ISSUE THREAD

**Issue by yan12125** [facebook/hhvm#6218]
I've compiled a debug build against commit ee805d9d90839a93f3ade17aabd56437b1994eed using the build script at http://aur.archlinux.org/packages/hhvm-git/. I get a segmentation fault for every run of ./hhvm:
```
$ ./hhvm 
[1]    25954 segmentation fault (core dumped)  ./hhvm
```
With a brief debugging via gdb, I found the problem is here:
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000000002620bad in HPHP::JEMallocInitializer::JEMallocInitializer (this=<optimized out>)
    at /home/yen/Computer/Programming/aur/hhvm-git/src/hhvm/hphp/util/alloc.cpp:408
#2  0x0000000002b16c7d in __libc_csu_init ()
    at /home/yen/Computer/Programming/aur/hhvm-git/src/hhvm/hphp/runtime/base/classname-is.h:37
#3  0x00007fffefab659f in __libc_start_main () from /usr/lib/libc.so.6
#4  0x0000000000f6c3e9 in _start ()
```
A few more steps lead me to here:
```
(gdb) 
0x00007ffff7defff4 in _dl_runtime_resolve () from /lib64/ld-linux-x86-64.so.2
(gdb) 
0x0000000000000000 in ?? ()
```
IP is suspicious here. Here's the dump of ```_dl_runtime_resolve```:
```
Dump of assembler code for function _dl_runtime_resolve:
   0x00007ffff7deff60 <+0>:	sub    rsp,0x78
   0x00007ffff7deff64 <+4>:	mov    QWORD PTR [rsp+0x40],rax
   0x00007ffff7deff69 <+9>:	mov    QWORD PTR [rsp+0x48],rcx
   0x00007ffff7deff6e <+14>:	mov    QWORD PTR [rsp+0x50],rdx
   0x00007ffff7deff73 <+19>:	mov    QWORD PTR [rsp+0x58],rsi
   0x00007ffff7deff78 <+24>:	mov    QWORD PTR [rsp+0x60],rdi
   0x00007ffff7deff7d <+29>:	mov    QWORD PTR [rsp+0x68],r8
   0x00007ffff7deff82 <+34>:	mov    QWORD PTR [rsp+0x70],r9
   0x00007ffff7deff87 <+39>:	bndmov [rsp],bnd0
   0x00007ffff7deff8c <+44>:	bndmov [rsp+0x10],bnd1
   0x00007ffff7deff92 <+50>:	bndmov [rsp+0x20],bnd2
   0x00007ffff7deff98 <+56>:	bndmov [rsp+0x30],bnd3
   0x00007ffff7deff9e <+62>:	mov    rsi,QWORD PTR [rsp+0x80]
   0x00007ffff7deffa6 <+70>:	mov    rdi,QWORD PTR [rsp+0x78]
   0x00007ffff7deffab <+75>:	call   0x7ffff7de9560 <_dl_fixup>
   0x00007ffff7deffb0 <+80>:	mov    r11,rax
   0x00007ffff7deffb3 <+83>:	bndmov bnd3,[rsp+0x30]
   0x00007ffff7deffb9 <+89>:	bndmov bnd2,[rsp+0x20]
   0x00007ffff7deffbf <+95>:	bndmov bnd1,[rsp+0x10]
   0x00007ffff7deffc5 <+101>:	bndmov bnd0,[rsp]
   0x00007ffff7deffca <+106>:	mov    r9,QWORD PTR [rsp+0x70]
   0x00007ffff7deffcf <+111>:	mov    r8,QWORD PTR [rsp+0x68]
   0x00007ffff7deffd4 <+116>:	mov    rdi,QWORD PTR [rsp+0x60]
   0x00007ffff7deffd9 <+121>:	mov    rsi,QWORD PTR [rsp+0x58]
   0x00007ffff7deffde <+126>:	mov    rdx,QWORD PTR [rsp+0x50]
   0x00007ffff7deffe3 <+131>:	mov    rcx,QWORD PTR [rsp+0x48]
   0x00007ffff7deffe8 <+136>:	mov    rax,QWORD PTR [rsp+0x40]
   0x00007ffff7deffed <+141>:	add    rsp,0x88
   0x00007ffff7defff4 <+148>:	bnd jmp r11
```
And ```$r11```:
```
(gdb) p $r11
$1 = 0
```

Obviously hhvm crashes here. However, I can go no more further.

Environment:
OS: Arch Linux x86_64
Compiler: Clang 3.6.2
jemalloc: 4.0.0

**Comment by yan12125** [comment]
With jemalloc 4.0.4-1, clang 3.7, gcc 5.3 and c72c876ab99a4343ef642e2133113612d91d853e this bug is gone.
