### ISSUE TITLE
Segmentation Fault in wordsame()

### ISSUE THREAD

**Issue by octmoraru** [facebook/hhvm#6408]
Our lab has reported a runtime crash while running the WordPress benchmark from oss-performance. You can check the report [here]( https://lists.01.org/pipermail/langperf/2015-October/000204.html).
Upon investigations we found that HHVM was segfaulting somewhere after the pre-compilation phase, but before finishing the server initialization.
The issue was caused by the wordsame() function in hphp/util/word-mem.h This function compares two memory buffers for equality, 8 bytes at a time. The problem appears when the length of one of the buffers is not a multiple of 8; in this case, a read beyond the limits of the buffer is performed.

I guess you are aware of this, since the comments inside the function say
>  // We would like to make sure 'mem2' is also aligned.  But `strintern_eq' has
>  // always been using 'wordsame()' on non-aligned pointers, and this doesn't
>  // seem to cause crashes in practice.

Except it sometimes does cause a crash. Specifically, the crash happens if one of the buffers is located at the "edge" of a memory page.
In our case, mem2's address was 0x7f9f82bffff9. An 8-byte read spills over in the next page, causing a segfault.

The commit for which the build was made is: a2b3a8d
Please note that this wasn't reproducible outside the benchmarking environment (i.e. oss-performance). It all depends on the buffer's address being close to the edge of a page.

**Comment by octmoraru** [comment]
Stacktrace:
```
#0  wordsame (lenBytes=<optimized out>, mem2=<optimized out>, mem1=<optimized out>) at /home/lp-jenkins/hhvm-dbg/hphp/util/word-mem.h:200
#1  operator() (this=<optimized out>, k2=-140733897440480, k1=140686094479776) at /home/lp-jenkins/hhvm-dbg/hphp/runtime/base/static-string-table.cpp:82
#2  folly::AtomicHashArray<long, HPHP::rds::Link<HPHP::TypedValue>, HPHP::(anonymous namespace)::strintern_hash, HPHP::(anonymous namespace)::strintern_eq, std::allocator<char> >::findInternal (
    this=this@entry=0x7ff408c00000, key_in=key_in@entry=-140733897440480) at /home/lp-jenkins/hhvm-dbg/third-party/folly/folly/AtomicHashArray-inl.h:59
#3  0x0000000000ccf689 in findInternal (k=-140733897440480, k@entry=-140733897440416, this=0x7ff40981a0c0) at /home/lp-jenkins/hhvm-dbg/third-party/folly/folly/AtomicHashMap-inl.h:176
#4  folly::AtomicHashMap<long, HPHP::rds::Link<HPHP::TypedValue>, HPHP::(anonymous namespace)::strintern_hash, HPHP::(anonymous namespace)::strintern_eq, std::allocator<char> >::find (this=0x7ff40981a0c0, 
    k=k@entry=-140733897440480) at /home/lp-jenkins/hhvm-dbg/third-party/folly/folly/AtomicHashMap-inl.h:152
#5  0x0000000000cd25ac in HPHP::makeStaticString (slice=...) at /home/lp-jenkins/hhvm-dbg/hphp/runtime/base/static-string-table.cpp:188
#6  0x0000000000cd262d in makeStaticString (len=<optimized out>, str=0x7ff406bffff9 "arr") at /home/lp-jenkins/hhvm-dbg/hphp/runtime/base/static-string-table.cpp:218
#7  HPHP::makeStaticString (str=0x7ff406bffff9 "arr") at /home/lp-jenkins/hhvm-dbg/hphp/runtime/base/static-string-table.cpp:229
#8  0x0000000000e100f1 in HPHP::(anonymous namespace)::AsmState::getLocalId (this=this@entry=0x7fff29f70510, name="$arr") at /home/lp-jenkins/hhvm-dbg/hphp/runtime/vm/as.cpp:737
#9  0x0000000000e1f6e5 in HPHP::(anonymous namespace)::parse_opcode_CGetL (as=...) at /home/lp-jenkins/hhvm-dbg/hphp/runtime/vm/as.cpp:1349
#10 0x0000000000e2c07b in HPHP::(anonymous namespace)::parse_function_body (as=..., nestLevel=nestLevel@entry=0) at /home/lp-jenkins/hhvm-dbg/hphp/runtime/vm/as.cpp:1599
#11 0x0000000000e2e594 in parse_function (as=...) at /home/lp-jenkins/hhvm-dbg/hphp/runtime/vm/as.cpp:1880
#12 parse (as=...) at /home/lp-jenkins/hhvm-dbg/hphp/runtime/vm/as.cpp:2390
#13 HPHP::assemble_string (
    code=code@entry=0x7ff40775e018 "\n.function array_filter($arr = no_args, $func = start(\"\"\"null\"\"\"), $flag = start(\"\"\"null\"\"\"), $res = start) {\n          .numiters 2;\n\n# if we get here, a value was supplied for $res\n          String \""..., codeLen=codeLen@entry=9696, filename=filename@entry=0x1daa263 "systemlib.hhas", md5=...) at /home/lp-jenkins/hhvm-dbg/hphp/runtime/vm/as.cpp:2417
#14 0x00000000016cd34e in HPHP::Compiler::hphp_compiler_parse (
    code=0x7ff40775e018 "\n.function array_filter($arr = no_args, $func = start(\"\"\"null\"\"\"), $flag = start(\"\"\"null\"\"\"), $res = start) {\n          .numiters 2;\n\n# if we get here, a value was supplied for $res\n          String \""..., codeLen=9696, md5=..., filename=<optimized out>) at /home/lp-jenkins/hhvm-dbg/hphp/compiler/analysis/emitter.cpp:10184
#15 0x0000000000f3a75b in HPHP::compile_string (
    s=0x7ff40775e018 "\n.function array_filter($arr = no_args, $func = start(\"\"\"null\"\"\"), $flag = start(\"\"\"null\"\"\"), $res = start) {\n          .numiters 2;\n\n# if we get here, a value was supplied for $res\n          String \""..., sz=9696, fname=fname@entry=0x1daa263 "systemlib.hhas") at /home/lp-jenkins/hhvm-dbg/hphp/runtime/vm/runtime.cpp:192
#16 0x0000000000b8191f in HPHP::ProcessInit () at /home/lp-jenkins/hhvm-dbg/hphp/hhvm/process-init.cpp:115
#17 0x0000000000c85749 in HPHP::hphp_process_init () at /home/lp-jenkins/hhvm-dbg/hphp/runtime/base/program-functions.cpp:1956
#18 0x0000000000da5cbd in HPHP::HttpServer::HttpServer (this=0x7ff409bd9618) at /home/lp-jenkins/hhvm-dbg/hphp/runtime/server/http-server.cpp:151
#19 0x0000000000c90c38 in construct<HPHP::HttpServer> (__p=0x7ff409bd9618, this=<optimized out>) at /usr/lib/gcc/x86_64-redhat-linux/4.8.3/../../../../include/c++/4.8.3/bits/shared_ptr_base.h:396
#20 _S_construct<HPHP::HttpServer> (__p=0x7ff409bd9618, __a=...) at /usr/lib/gcc/x86_64-redhat-linux/4.8.3/../../../../include/c++/4.8.3/bits/alloc_traits.h:254
#21 construct<HPHP::HttpServer> (__p=0x7ff409bd9618, __a=...) at /usr/lib/gcc/x86_64-redhat-linux/4.8.3/../../../../include/c++/4.8.3/bits/alloc_traits.h:393
#22 _Sp_counted_ptr_inplace<> (__a=..., this=0x7ff409bd9600) at /usr/lib/gcc/x86_64-redhat-linux/4.8.3/../../../../include/c++/4.8.3/bits/shared_ptr_base.h:399
#23 construct<std::_Sp_counted_ptr_inplace<HPHP::HttpServer, std::allocator<HPHP::HttpServer>, (__gnu_cxx::_Lock_policy)2>, std::allocator<HPHP::HttpServer> const> (__p=<optimized out>, 
    this=<synthetic pointer>) at /usr/lib/gcc/x86_64-redhat-linux/4.8.3/../../../../include/c++/4.8.3/ext/new_allocator.h:120
#24 _S_construct<std::_Sp_counted_ptr_inplace<HPHP::HttpServer, std::allocator<HPHP::HttpServer>, (__gnu_cxx::_Lock_policy)2>, std::allocator<HPHP::HttpServer> const> (__p=<optimized out>, 
    __a=<synthetic pointer>) at /usr/lib/gcc/x86_64-redhat-linux/4.8.3/../../../../include/c++/4.8.3/bits/alloc_traits.h:254
#25 construct<std::_Sp_counted_ptr_inplace<HPHP::HttpServer, std::allocator<HPHP::HttpServer>, (__gnu_cxx::_Lock_policy)2>, std::allocator<HPHP::HttpServer> const> (__p=<optimized out>, __a=<synthetic pointer>)
    at /usr/lib/gcc/x86_64-redhat-linux/4.8.3/../../../../include/c++/4.8.3/bits/alloc_traits.h:393
#26 __shared_count<HPHP::HttpServer, std::allocator<HPHP::HttpServer> > (__a=..., this=<optimized out>) at /usr/lib/gcc/x86_64-redhat-linux/4.8.3/../../../../include/c++/4.8.3/bits/shared_ptr_base.h:502
#27 __shared_ptr<std::allocator<HPHP::HttpServer> > (__a=..., __tag=..., this=<optimized out>) at /usr/lib/gcc/x86_64-redhat-linux/4.8.3/../../../../include/c++/4.8.3/bits/shared_ptr_base.h:957
#28 shared_ptr<std::allocator<HPHP::HttpServer> > (__a=..., __tag=..., this=<optimized out>) at /usr/lib/gcc/x86_64-redhat-linux/4.8.3/../../../../include/c++/4.8.3/bits/shared_ptr.h:316
#29 allocate_shared<HPHP::HttpServer, std::allocator<HPHP::HttpServer> > (__a=...) at /usr/lib/gcc/x86_64-redhat-linux/4.8.3/../../../../include/c++/4.8.3/bits/shared_ptr.h:598
#30 make_shared<HPHP::HttpServer> () at /usr/lib/gcc/x86_64-redhat-linux/4.8.3/../../../../include/c++/4.8.3/bits/shared_ptr.h:614
#31 start_server (username=..., xhprof=0) at /home/lp-jenkins/hhvm-dbg/hphp/runtime/base/program-functions.cpp:926
#32 HPHP::execute_program_impl (argc=argc@entry=29, argv=argv@entry=0x7fff29f73878) at /home/lp-jenkins/hhvm-dbg/hphp/runtime/base/program-functions.cpp:1739
#33 0x0000000000c91f2f in HPHP::execute_program (argc=argc@entry=29, argv=argv@entry=0x7fff29f73878) at /home/lp-jenkins/hhvm-dbg/hphp/runtime/base/program-functions.cpp:1049
#34 0x0000000000b7ff55 in main (argc=<optimized out>, argv=0x7fff29f73878) at /home/lp-jenkins/hhvm-dbg/hphp/hhvm/main.cpp:66
```
