### ISSUE TITLE
Segmentation fault when building HHBC

### ISSUE THREAD

**Issue by jshthornton** [facebook/hhvm#6517]
Using `hhvm --hphp -thhbc -o some_dir --input-list files.txt -v WholeProgram=false` I am experiencing a segmentation fault. Nothing in the stacktrace other than `PHP Stacktrace:`.

No idea how to get gdb working whilst compiling.

**Comment by jwatzman** [comment]
This could be #6296. You can get a backtrace by just running that `hhvm` compilation command under `gdb` -- I'd probably do this by `gdb --args hhvm --hphp -thhbc -o some_dir --input-list files.txt -v WholeProgram=false`. You will probably need to tell gdb `set follow-fork-mode child` since most of the work happens in a child for some reason.

**Comment by firodj** [comment]
The Segfault occurs when `WholeProgram=false`.

```
$ gdb --args hhvm --hphp -t hhbc -v AllVolatile=true -v WholeProgram=false --output-dir . -v Eval.SyncGdbChunks=1 -v Eval.JitNoGdb=false main.php -l4 -k1
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from hhvm...done.
(gdb) r
Starting program: /usr/bin/hhvm --hphp -t hhbc -v AllVolatile=true -v WholeProgram=false --output-dir . -v Eval.SyncGdbChunks=1 -v Eval.JitNoGdb=false main.php -l4 -k1
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Possible bad config node: Eval
running hphp...
parsing inputs...
[New Thread 0x7fffde7ff700 (LWP 1647)]
parsing ./main.php ...
[Thread 0x7fffde7ff700 (LWP 1647) exited]
parsing inputs took 0'00" (11886 us) wall time
pre-optimizing...
[New Thread 0x7fffde7ff700 (LWP 1648)]
[New Thread 0x7fffddbff700 (LWP 1649)]
[New Thread 0x7fffd93ff700 (LWP 1650)]
[New Thread 0x7fffd8bff700 (LWP 1651)]
[New Thread 0x7fffd7bff700 (LWP 1652)]
[New Thread 0x7fffcefff700 (LWP 1653)]
[New Thread 0x7fffca7ff700 (LWP 1654)]
[New Thread 0x7fffc97ff700 (LWP 1656)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffde7ff700 (LWP 1648)]
0x00000000060b23fe in HPHP::Symbol::setStaticInitVal (this=0x0, initVal=std::shared_ptr (count 2, weak 1) 0x7fffe0a5ff78)
    at /tmp/tmp.JgQ8ces5ZQ/hphp/compiler/analysis/symbol_table.h:159
159	    if (m_flags.m_hasClassInit) initVal.reset();
(gdb) bt
#0  0x00000000060b23fe in HPHP::Symbol::setStaticInitVal (this=0x0, initVal=std::shared_ptr (count 2, weak 1) 0x7fffe0a5ff78)
    at /tmp/tmp.JgQ8ces5ZQ/hphp/compiler/analysis/symbol_table.h:159
#1  0x000000000618a32f in HPHP::StaticStatement::preOptimize (this=0x7fffe0a26718, ar=std::shared_ptr (count 10, weak 1) 0x7fffe5cc9718)
    at /tmp/tmp.JgQ8ces5ZQ/hphp/compiler/statement/static_statement.cpp:118
#2  0x00000000060090ec in (anonymous namespace)::DepthFirstVisitor::visit (this=0x7fffffffd820, stmt=std::shared_ptr (count 5, weak 1) 0x7fffe0a26718)
    at /tmp/tmp.JgQ8ces5ZQ/hphp/compiler/analysis/analysis_result.cpp:899
#3  0x0000000006008378 in (anonymous namespace)::DepthFirstVisitor::visitStmtRecur (this=0x7fffffffd820, 
    stmt=std::shared_ptr (count 5, weak 1) 0x7fffe0a26718) at /tmp/tmp.JgQ8ces5ZQ/hphp/compiler/analysis/analysis_result.cpp:767
#4  0x000000000600813d in (anonymous namespace)::DepthFirstVisitor::visitStmtRecur (this=0x7fffffffd820, 
    stmt=std::shared_ptr (count 4, weak 1) 0x7fffe0a60218) at /tmp/tmp.JgQ8ces5ZQ/hphp/compiler/analysis/analysis_result.cpp:752
#5  0x000000000600813d in (anonymous namespace)::DepthFirstVisitor::visitStmtRecur (this=0x7fffffffd820, 
    stmt=std::shared_ptr (count 5, weak 1) 0x7fffe0a43e18) at /tmp/tmp.JgQ8ces5ZQ/hphp/compiler/analysis/analysis_result.cpp:752
#6  0x000000000600850e in (anonymous namespace)::DepthFirstVisitor::visitScope (this=0x7fffffffd820, scope=...)
    at /tmp/tmp.JgQ8ces5ZQ/hphp/compiler/analysis/analysis_result.cpp:777
#7  0x000000000600936d in (anonymous namespace)::OptWorker::doJob (this=0x7fffdeace670, scope=0x7fffe0a1a098)
    at /tmp/tmp.JgQ8ces5ZQ/hphp/compiler/analysis/analysis_result.cpp:939
#8  0x000000000600faa7 in HPHP::JobQueueWorker<HPHP::BlockScope*, void*, true, true, HPHP::detail::NoDropCachePolicy>::start (this=0x7fffdeace670)
    at /tmp/tmp.JgQ8ces5ZQ/hphp/util/job-queue.h:459
#9  0x0000000004666b7f in HPHP::AsyncFunc<HPHP::WorkerWrapper<HPHP::IFJob, HPHP::InitFiniNode::IFWorker> >::run_ (obj=0x7fffdeb1f200)
    at /tmp/tmp.JgQ8ces5ZQ/hphp/util/async-func.h:208
#10 0x0000000006287781 in HPHP::AsyncFuncImpl::threadFuncImpl (this=0x7fffdeb1f200) at /tmp/tmp.JgQ8ces5ZQ/hphp/util/async-func.cpp:131
#11 0x0000000006287373 in HPHP::AsyncFuncImpl::ThreadFunc (obj=0x7fffdeb1f200) at /tmp/tmp.JgQ8ces5ZQ/hphp/util/async-func.cpp:51
#12 0x00000000047ab697 in HPHP::start_routine_wrapper (arg=0x7fffdea34780) at /tmp/tmp.JgQ8ces5ZQ/hphp/runtime/base/thread-hooks.cpp:104
#13 0x00007ffff1330182 in start_thread (arg=0x7fffde7ff700) at pthread_create.c:312
#14 0x00007ffff083d47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

```

I am using `hhvm-dbg` that doesnt have source-code for gdb to show, so I fill `/tmp/tmp.JgQ8ces5ZQ/` with https://github.com/facebook/hhvm/tree/5b0e52b83f1dc0aa0c1dfe3a5687995c9693f5a6

For details of version what was used:
```
$ ls -a
.  ..  .hhconfig  main.php

$ hh_client
No errors!

$ cat main.php 
<?hh

function main() {
    echo "stub or stabbed\n";
}

main();

$ hhvm -v Eval.Jit=1 main.php
stub or stabbed

$ apt search hhvm
Sorting... Done
Full Text Search... Done
hhvm/unknown,now 3.13.0~trusty amd64 [residual-config]
  HHVM virtual machine, runtime, and JIT for the PHP language

hhvm-dbg/unknown,now 3.13.0~trusty amd64 [installed]
  HHVM virtual machine, runtime, and JIT for the PHP language

hhvm-dev/unknown,now 3.13.0~trusty amd64 [installed]
  Developer package for the HHVM virtual machine, runtime, and JIT for the PHP language

hhvm-dev-nightly/unknown 2016.03.31~trusty amd64
  Developer package for the HHVM virtual machine, runtime, and JIT for the PHP language

hhvm-nightly/unknown 2016.03.31~trusty amd64
  HHVM virtual machine, runtime, and JIT for the PHP language

hhvm-nightly-dbg/unknown 2016.03.31~trusty amd64
  HHVM virtual machine, runtime, and JIT for the PHP language

$ % uname -a
Linux woi-sixtyseven 3.16.0-60-generic #80~14.04.1-Ubuntu SMP Wed Jan 20 13:37:48 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ ls /etc/hhvm 
php.ini  server.ini

$ cat /etc/hhvm/php.ini 
; php options
session.save_handler = files
session.save_path = /var/lib/hhvm/sessions
session.gc_maxlifetime = 1440

; hhvm specific 
hhvm.log.level = Warning
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.runtime_error_reporting_level = 8191
hhvm.mysql.typed_results = false

$ hhvm --hphp -t hhbc -v AllVolatile=true -v WholeProgram=true --output-dir . main.php -l4 -k1
running hphp...
parsing inputs...
parsing ./main.php ...
analyzeProgram...
Analyzing Includes
Analyzing All
analyzeProgram took 0'00" (82210 us) wall time
parsing inputs took 0'00" (84035 us) wall time
pre-optimizing...
pre-optimizing took 0'00" (24851 us) wall time
creating binary HHBC files...
creating binary HHBC files took 0'02" (2040911 us) wall time
all files saved in . ...
running hphp took 0'03" (3556285 us) wall time

$ hhvm --hphp -t hhbc -v AllVolatile=true -v WholeProgram=false --output-dir . main.php -l4 -k1
running hphp...
parsing inputs...
parsing ./main.php ...
parsing inputs took 0'00" (1573 us) wall time
pre-optimizing...
Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.1215.log
hphp failed
running hphp took 0'01" (1438316 us) wall time

$ cat /tmp/stacktrace.1215.log

PHP Stacktrace:



$ hhvm --hphp -t hhbc -v AllVolatile=true -v WholeProgram=false --output-dir . main.php -l4 -k1 --nofork=1            
running hphp...
parsing inputs...
parsing ./main.php ...
parsing inputs took 0'00" (1586 us) wall time
pre-optimizing...
Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.1790.log
[1]    1790 segmentation fault (core dumped)  hhvm --hphp -t hhbc -v AllVolatile=true -v WholeProgram=false --output-dir . 


$ [255] % hhvm --hphp -t hhbc -v AllVolatile=true -v WholeProgram=false --optimize-level=0 --output-dir . main.php -l4 -k1
running hphp...
parsing inputs...
parsing ./main.php ...
parsing inputs took 0'00" (1616 us) wall time
creating binary HHBC files...
hhvm: /tmp/tmp.JgQ8ces5ZQ/hphp/hhbbc/index.cpp:1831: HPHP::HHBBC::res::Class HPHP::HHBBC::Index::builtin_class(HPHP::HHBBC::SString) const: Assertion `rcls->val.right() && (rcls->val.right()->cls->attrs & AttrBuiltin)' failed.
hhvm: /tmp/tmp.JgQ8ces5ZQ/hphp/hhbbc/index.cpp:1831: HPHP::HHBBC::res::Class HPHP::HHBBC::Index::builtin_class(HPHP::HHBBC::SString) const: Assertion `rcls->val.right() && (rcls->val.right()->cls->attrs & AttrBuiltin)' failed.
hphp failed
running hphp took 0'01" (1650396 us) wall time
```

How to fix these problem since I am using Laravel that use `class_alias` where there is not possible using `WholeProgram=true` as meniton in https://github.com/facebook/hhvm/issues/867

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

I tried to run your repro on hhvm 4.143. I got a warning: Possible bad config node: WholeProgram.
I could run this hhvm.hhbc just fine. It appears this WholeProgram mode has been removed at some point. WholeProgram only appears in comments.
