### ISSUE TITLE
pfsockopen-created sockets get closed by the engine's memory cleanup in FastCGI mode

### ISSUE THREAD

**Issue by isegal** [facebook/hhvm#6631]
When running in FastCGI, pfsockopen() is not being honored, as the socket gets immediately closed upon exit of page serving.

The problem appears to be with the way garbage collection interacts with the socket object:

Simple test-case:

index.php
```
<?php
$socksock = pfsockopen("10.1.64.11", 27017);

return;
```

Trace of SocketData::closeImpl() calls:
```
#0  HPHP::SocketData::closeImpl (this=0x7f9a01827b18) at /tmp/tmp.37b2AKSInv/hphp/runtime/base/socket.cpp:44
#1  0x000000000391bacb in HPHP::SSLSocketData::closeImpl (this=0x7f9a01827b18)
    at /tmp/tmp.37b2AKSInv/hphp/runtime/base/ssl-socket.cpp:37
#2  0x00000000039c7151 in HPHP::File::closeImpl (this=0x7f9a018afa70) at /tmp/tmp.37b2AKSInv/hphp/runtime/base/file.cpp:209
#3  0x000000000391ca1e in HPHP::SSLSocket::sweep (this=0x7f9a018afa70)
    at /tmp/tmp.37b2AKSInv/hphp/runtime/base/ssl-socket.cpp:226
#4  0x00000000038b7816 in HPHP::MemoryManager::sweep (this=0x7f99fc3fb910)
    at /tmp/tmp.37b2AKSInv/hphp/runtime/base/memory-manager.cpp:484
#5  0x00000000039f510f in HPHP::hphp_memory_cleanup () at /tmp/tmp.37b2AKSInv/hphp/runtime/base/program-functions.cpp:2167
#6  0x00000000039f52b0 in HPHP::hphp_session_exit () at /tmp/tmp.37b2AKSInv/hphp/runtime/base/program-functions.cpp:2201
#7  0x0000000003ad5dd9 in HPHP::HttpRequestHandler::teardownRequest (this=0x7f9a02be1510, transport=0x7f9a09fe2a18)
    at /tmp/tmp.37b2AKSInv/hphp/runtime/server/http-request-handler.cpp:215
#8  0x0000000003b409ae in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl(std::shared_ptr<HPHP::FastCGIJob>, bool)::{lambda()#1}::operator()() const (__closure=0x7f99fc3fa588)
    at /tmp/tmp.37b2AKSInv/hphp/runtime/server/server-worker.h:94
#9  0x0000000003b4114e in folly::ScopeGuardImpl<HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl(std::shared_ptr<HPHP::FastCGIJob>, bool)::{lambda()#1}>::execute() (this=0x7f99fc3fa580)
    at /tmp/tmp.37b2AKSInv/third-party/folly/folly/ScopeGuard.h:111
#10 0x0000000003b410f4 in folly::ScopeGuardImpl<HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl(std::shared_ptr<HPHP::FastCGIJob>, bool)::{lambda()#1}>::~ScopeGuardImpl() (this=0x7f99fc3fa580,
    __in_chrg=<optimized out>) at /tmp/tmp.37b2AKSInv/third-party/folly/folly/ScopeGuard.h:104
#11 0x0000000003b40dd7 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl (
    this=0x7f9a02bc89c0, job=..., abort=false) at /tmp/tmp.37b2AKSInv/hphp/runtime/server/server-worker.h:133
#12 0x0000000003b40518 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJob (
    this=0x7f9a02bc89c0, job=...) at /tmp/tmp.37b2AKSInv/hphp/runtime/server/server-worker.h:56
#13 0x0000000003b3cf99 in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start (this=0x7f9a02bc89c0) at /tmp/tmp.37b2AKSInv/hphp/util/job-queue.h:463
#14 0x0000000003a37afc in HPHP::AsyncFunc<HPHP::LibEventHttpClient>::run_ (obj=0x7f9a02b4b700)
    at /tmp/tmp.37b2AKSInv/hphp/util/async-func.h:213
#15 0x0000000005174ecd in HPHP::AsyncFuncImpl::threadFuncImpl (this=0x7f9a02b4b700)
    at /tmp/tmp.37b2AKSInv/hphp/util/async-func.cpp:131
#16 0x0000000005174abf in HPHP::AsyncFuncImpl::ThreadFunc (obj=0x7f9a02b4b700)
    at /tmp/tmp.37b2AKSInv/hphp/util/async-func.cpp:51
#17 0x000000000393f38f in HPHP::start_routine_wrapper (arg=0x7f9a02b7f940)
    at /tmp/tmp.37b2AKSInv/hphp/runtime/base/thread-hooks.cpp:104
#18 0x00007f9a12d22182 in start_thread (arg=0x7f99fc3ff700) at pthread_create.c:312
#19 0x00007f9a1222f47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

```
print *this
$1 = {<HPHP::FileData> = {_vptr.FileData = 0x5a184b0 <vtable for HPHP::SSLSocketData+16>, static CHUNK_SIZE = 8192,
    m_fd = 23, m_isLocal = false, m_closed = false, m_nonblocking = true, m_eof = false, m_position = 0, m_writepos = 0,
    m_readpos = 0, m_name = {static npos = <optimized out>,
      _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>},
        _M_p = 0x7f9a12d193f8 <std::string::_Rep::_S_empty_rep_storage+24> ""}}, m_mode = {static npos = <optimized out>,
      _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>},
        _M_p = 0x7f9a12d193f8 <std::string::_Rep::_S_empty_rep_storage+24> ""}}, m_buffer = 0x0, m_bufferSize = 8192},
  m_address = {static npos = <optimized out>,
    _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>},
      _M_p = 0x7f9a01afdf58 "10.1.64.11"}}, m_port = 27017, m_type = 2, m_bytesSent = 0, m_error = 0, m_timeout = 60000000,
  m_timedOut = false}
```

The breakpoint is hit more than once within the same page request:
```
#0  HPHP::SocketData::closeImpl (this=0x7f9a01827b18) at /tmp/tmp.37b2AKSInv/hphp/runtime/base/socket.cpp:44
#1  0x000000000391bacb in HPHP::SSLSocketData::closeImpl (this=0x7f9a01827b18)
    at /tmp/tmp.37b2AKSInv/hphp/runtime/base/ssl-socket.cpp:37
#2  0x00000000039c7151 in HPHP::File::closeImpl (this=0x7f9a018afa70) at /tmp/tmp.37b2AKSInv/hphp/runtime/base/file.cpp:209
#3  0x00000000039c70e3 in HPHP::File::sweep (this=0x7f9a018afa70) at /tmp/tmp.37b2AKSInv/hphp/runtime/base/file.cpp:202
#4  0x000000000391ca2a in HPHP::SSLSocket::sweep (this=0x7f9a018afa70)
    at /tmp/tmp.37b2AKSInv/hphp/runtime/base/ssl-socket.cpp:227
#5  0x00000000038b7816 in HPHP::MemoryManager::sweep (this=0x7f99fc3fb910)
    at /tmp/tmp.37b2AKSInv/hphp/runtime/base/memory-manager.cpp:484
#6  0x00000000039f510f in HPHP::hphp_memory_cleanup () at /tmp/tmp.37b2AKSInv/hphp/runtime/base/program-functions.cpp:2167
#7  0x00000000039f52b0 in HPHP::hphp_session_exit () at /tmp/tmp.37b2AKSInv/hphp/runtime/base/program-functions.cpp:2201
#8  0x0000000003ad5dd9 in HPHP::HttpRequestHandler::teardownRequest (this=0x7f9a02be1510, transport=0x7f9a09fe2a18)
    at /tmp/tmp.37b2AKSInv/hphp/runtime/server/http-request-handler.cpp:215
#9  0x0000000003b409ae in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl(std::shared_ptr<HPHP::FastCGIJob>, bool)::{lambda()#1}::operator()() const (__closure=0x7f99fc3fa588)
    at /tmp/tmp.37b2AKSInv/hphp/runtime/server/server-worker.h:94
#10 0x0000000003b4114e in folly::ScopeGuardImpl<HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl(std::shared_ptr<HPHP::FastCGIJob>, bool)::{lambda()#1}>::execute() (this=0x7f99fc3fa580)
    at /tmp/tmp.37b2AKSInv/third-party/folly/folly/ScopeGuard.h:111
#11 0x0000000003b410f4 in folly::ScopeGuardImpl<HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl(std::shared_ptr<HPHP::FastCGIJob>, bool)::{lambda()#1}>::~ScopeGuardImpl() (this=0x7f99fc3fa580,
    __in_chrg=<optimized out>) at /tmp/tmp.37b2AKSInv/third-party/folly/folly/ScopeGuard.h:104
#12 0x0000000003b40dd7 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl (
    this=0x7f9a02bc89c0, job=..., abort=false) at /tmp/tmp.37b2AKSInv/hphp/runtime/server/server-worker.h:133
#13 0x0000000003b40518 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJob (
    this=0x7f9a02bc89c0, job=...) at /tmp/tmp.37b2AKSInv/hphp/runtime/server/server-worker.h:56
#14 0x0000000003b3cf99 in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start (this=0x7f9a02bc89c0) at /tmp/tmp.37b2AKSInv/hphp/util/job-queue.h:463
#15 0x0000000003a37afc in HPHP::AsyncFunc<HPHP::LibEventHttpClient>::run_ (obj=0x7f9a02b4b700)
    at /tmp/tmp.37b2AKSInv/hphp/util/async-func.h:213
#16 0x0000000005174ecd in HPHP::AsyncFuncImpl::threadFuncImpl (this=0x7f9a02b4b700)
    at /tmp/tmp.37b2AKSInv/hphp/util/async-func.cpp:131
#17 0x0000000005174abf in HPHP::AsyncFuncImpl::ThreadFunc (obj=0x7f9a02b4b700)
    at /tmp/tmp.37b2AKSInv/hphp/util/async-func.cpp:51
#18 0x000000000393f38f in HPHP::start_routine_wrapper (arg=0x7f9a02b7f940)
    at /tmp/tmp.37b2AKSInv/hphp/runtime/base/thread-hooks.cpp:104
#19 0x00007f9a12d22182 in start_thread (arg=0x7f99fc3ff700) at pthread_create.c:312
#20 0x00007f9a1222f47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

```
$2 = {<HPHP::FileData> = {_vptr.FileData = 0x5a184b0 <vtable for HPHP::SSLSocketData+16>, static CHUNK_SIZE = 8192,
    m_fd = -1, m_isLocal = false, m_closed = true, m_nonblocking = true, m_eof = false, m_position = 0, m_writepos = 0,
    m_readpos = 0, m_name = {static npos = <optimized out>,
      _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>},
        _M_p = 0x7f9a12d193f8 <std::string::_Rep::_S_empty_rep_storage+24> ""}}, m_mode = {static npos = <optimized out>,
      _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>},
        _M_p = 0x7f9a12d193f8 <std::string::_Rep::_S_empty_rep_storage+24> ""}}, m_buffer = 0x0, m_bufferSize = 8192},
  m_address = {static npos = <optimized out>,
    _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>},
      _M_p = 0x7f9a01afdf58 "10.1.64.11"}}, m_port = 27017, m_type = 2, m_bytesSent = 0, m_error = 0, m_timeout = 60000000,
  m_timedOut = false}
```

Upon a subsequent request, the first thing that happens is f_pfsockopen() itself cleans up the inadvertadly dead socket from previous request, and starts a new connection.

```
#0  HPHP::SocketData::closeImpl (this=0x7f9a01827b18) at /tmp/tmp.37b2AKSInv/hphp/runtime/base/socket.cpp:44
#1  0x000000000391bacb in HPHP::SSLSocketData::closeImpl (this=0x7f9a01827b18)
    at /tmp/tmp.37b2AKSInv/hphp/runtime/base/ssl-socket.cpp:37
#2  0x00000000039c7151 in HPHP::File::closeImpl (this=0x7f9a018acae0) at /tmp/tmp.37b2AKSInv/hphp/runtime/base/file.cpp:209
#3  0x0000000003980b22 in HPHP::Socket::close (this=0x7f9a018acae0) at /tmp/tmp.37b2AKSInv/hphp/runtime/base/socket.cpp:132
#4  0x0000000004aab850 in HPHP::sockopen_impl (hosturl=..., errnum=..., errstr=..., timeout=-1, persistent=true, context=...)
    at /tmp/tmp.37b2AKSInv/hphp/runtime/ext/sockets/ext_sockets.cpp:1411
#5  0x0000000004aabcea in HPHP::f_pfsockopen (hostname=..., port=27017, errnum=..., errstr=..., timeout=-1)
    at /tmp/tmp.37b2AKSInv/hphp/runtime/ext/sockets/ext_sockets.cpp:1457
#6  0x0000000008e0027a in ?? ()
#7  0x0000000005947de9 in enterTCHelper () at /tmp/tmp.37b2AKSInv/hphp/runtime/vm/jit/translator-asm-helpers.S:77
#8  0x00000000041bc0ec in HPHP::jit::x64::(anonymous namespace)::BackEnd::enterTCHelper (this=0x7f9a09c2bb70,
    start=0x48e10030 "H\211\357\350\250\363\214\273\377\740\017\v\314\314\314\314H\211\357UH\211\3.5\377w\b\377\067\061\366\350s\326\2004\300\017\204\006", stashedAR=0x0) at /tmp/tmp.37b2AKSInv/hphp/runtime/vm/jit/back-end-x64.cpp:99
#9  0x000000000487c19e in HPHP::jit::MCGenerator::enterTC (this=0x7f9a07c6d400,
    start=0x48e10030 "H\211\357\350\250\363\214\273\377\740\017\v\314\314\314\314H\211\357UH\211\345\377w\b\377\067\061\366\350s\326\2004\300\017\204\006", stashedAR=0x0) at /tmp/tmp.37b2AKSInv/hphp/runtime/vm/jit/mc-generator.cpp:1214
#10 0x0000000003c10570 in HPHP::jit::MCGenerator::enterTCAfterPrologue (this=0x7f9a07c6d400,
    start=0x48e10030 "H\211\357\350\250\363\A14\273\377\340\017\v\314\314\314\314H\211\357UH\211\345\377w\b\377\067\061\366\350s\326\2004\300\017\204\006") at /tmp/tmp.37b2AKSInv/hphp/runtime/vm/jit/mc-generator.h:229
#11 0x0000000003c1bc03 in HPHP::enterVMAtFunc (enterFnAr=0x7f9a01b3ffc0, stk=HPHP::Untrimmed, varEnv=0x7f9a018a6320)
    at /tmp/tmp.37b2AKSInv/hphp/runtime/vm/bytecode.cpp:2025
#12 0x0000000003c1be05 in HPHP::ExecutionContext::__lambda136::operator() (__closure=0x7f99fc3f9b50)
    at /tmp/tmp.37b2AKSInv/hphp/runtime/vm/bytecode.cpp:2197
#13 0x0000000003cbd500 in HPHP::exception_handler<HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, const HPHP::Func*, const HPHP::Variant&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags)::__lambda136>(HPHP::ExecutionContext::__lambda136) (action=...) at /tmp/tmp.37b2AKSInv/hphp/runtime/vm/unwind-inl.h:30
#14 0x0000000003c8ab65 in HPHP::__lambda134::operator() (__closure=0x7f99fc3f9c00)
    at /tmp/tmp.37b2AKSInv/hphp/runtime/vm/bytecode.cpp:2071
#15 0x0000000003cbdaf4 in HPHP::enterVMCustomHandler<HPHP::enterVM(HPHP::ActRec*, Action) [with Action = HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, const HPHP::Func*, const HPHP::Variant&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags)::__lambda136]::__lambda134>(HPHP::ActRec *, HPHP::__lambda134) (
    ar=0x7f9a01b3ffc0, action=...) at /tmp/tmp.37b2AKSInv/hphp/runtime/vm/bytecode.cpp:2062
#16 0x0000000003c8ab9a in HPHP::enterVM<HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, const HPHP::Func*, const HPHP::Variant&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags)::__lambda136>(HPHP::ActRec *, HPHP::ExecutionContext::__lambda136) (ar=0x7f9a01b3ffc0, action=...)
    at /tmp/tmp.37b2AKSInv/hphp/runtime/vm/bytecode.cpp:2071
#17 0x0000000005947762 in HPHP::ExecutionContext::invokeFunc (this=0x7f9a018a5010, retptr=0x7f99fc3f9ea0, f=0x7f9a02420480,
    args_=..., this_=0x0, cls=0x0, varEnv=0x7f9a018a6320, invName=0x0, flags=HPHP::ExecutionContext::InvokePseudoMain)
#18 0x0000000005977de2 in HPHP::ExecutionContext::invokeUnit (this=0x7f9a018a5010, retval=0x7f99fc3f9ea0, unit=0x7f9a08fe4100)
    at /tmp/tmp.37b2AKSInv/hphp/runtime/vm/bytecode.cpp:2368
#19 0x00000000038a9911 in HPHP::invoke_file_impl (res=..., path=..., once=true, currentDir=0x5a77394 "")
    at /tmp/tmp.37b2AKSInv/hphp/runtime/base/builtin-functions.cpp:806
#20 0x0000000005977cfd in HPHP::invoke_file (s=..., once=true, currentDir=0x5a77394 "")
    at /tmp/tmp.37b2AKSInv/hphp/runtime/base/builtin-functions.cpp:819
#21 0x00000000038a99df in HPHP::include_impl_invoke (file=..., once=true, currentDir=0x5a77394 "")
    at /tmp/tmp.37b2AKSInv/hphp/runtime/base/builtin-functions.cpp:830
#22 0x00000000039f4d8c in HPHP::hphp_invoke (context=0x7f9a018a5010, cmd=..., func=false, funcParams=..., funcRet=...,
    reqInitFunc=..., reqInitDoc=..., error=@0x7f99fc3fa119: false, errorMsg=..., once=true, warmupOnly=false,
    richErrorMsg=false) at /tmp/tmp.37b2AKSInv/hphp/runtime/base/program-functions.cpp:2109
#23 0x0000000003ad76d8 in HPHP::HttpRequestHandler::executePHPRequest (this=0x7f9a02be1510, transport=0x7f9a09fe2d98,
    reqURI=..., sourceRootInfo=..., cacheableDynamicContent=false)
    at /tmp/tmp.37b2AKSInv/hphp/runtime/server/http-request-handler.cpp:477
#24 0x0000000003ad6c7c in HPHP::HttpRequestHandler::handleRequest (this=0x7f9a02be1510, transport=0x7f9a09fe2d98)
    at /tmp/tmp.37b2AKSInv/hphp/runtime/server/http-request-handler.cpp:388
#25 0x0000000003b40cdd in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl (
    this=0x7f9a02bc89c0, job=..., abort=false) at /tmp/tmp.37b2AKSInv/hphp/runtime/server/server-worker.h:108
#26 0x0000000003b40518 in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJob (
    this=0x7f9a02bc89c0, job=...) at /tmp/tmp.37b2AKSInv/hphp/runtime/server/server-worker.h:56
#27 0x0000000003b3cf99 in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start (this=0x7f9a02bc89c0) at /tmp/tmp.37b2AKSInv/hphp/util/job-queue.h:463
#28 0x0000000003a37afc in HPHP::AsyncFunc<HPHP::LibEventHttpClient>::run_ (obj=0x7f9a02b4b700)
    at /tmp/tmp.37b2AKSInv/hphp/util/async-func.h:213
#29 0x0000000005174ecd in HPHP::AsyncFuncImpl::threadFuncImpl (this=0x7f9a02b4b700)
    at /tmp/tmp.37b2AKSInv/hphp/util/async-func.cpp:131
#30 0x0000000005174abf in HPHP::AsyncFuncImpl::ThreadFunc (obj=0x7f9a02b4b700)
    at /tmp/tmp.37b2AKSInv/hphp/util/async-func.cpp:51
#31 0x000000000393f38f in HPHP::start_routine_wrapper (arg=0x7f9a02b7f940)
    at /tmp/tmp.37b2AKSInv/hphp/runtime/base/thread-hooks.cpp:104
#32 0x00007f9a12d22182 in start_thread (arg=0x7f99fc3ff700) at pthread_create.c:312
#33 0x00007f9a1222f47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

```
$3 = {<HPHP::FileData> = {_vptr.FileData = 0x5a184b0 <vtable for HPHP::SSLSocketData+16>, static CHUNK_SIZE = 8192,
    m_fd = -1, m_isLocal = false, m_closed = true, m_nonblocking = true, m_eof = false, m_position = 0, m_writepos = 0,
    m_readpos = 0, m_name = {static npos = <optimized out>,
      _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>},
        _M_p = 0x7f9a12d193f8 <std::string::_Rep::_S_empty_rep_storage+24> ""}}, m_mode = {static npos = <optimized out>,
      _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>},
        _M_p = 0x7f9a12d193f8 <std::string::_Rep::_S_empty_rep_storage+24> ""}}, m_buffer = 0x0, m_bufferSize = 8192},
  m_address = {static npos = <optimized out>,
    _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>},
      _M_p = 0x7f9a01afdf58 "10.1.64.11"}}, m_port = 27017, m_type = 2, m_bytesSent = 0, m_error = 0, m_timeout = 60000000,
  m_timedOut = false}
```

Server information:
```
hhvm --version
HipHop VM 3.10.1 (dbg)
Compiler: tags/HHVM-3.10.1-0-g689b4969a141620ee5a282ce0dbf72278c84d44b
Repo schema: 6c99ee1f98340f6f3ef397a332583f0e843a627d


hhvm.admin_server.port = 9001

hhvm.server.port = 9000
hhvm.server.type = fastcgi
hhvm.server.source_root = /var/www/public_html/
hhvm.server.default_document = index.php

; (E_ALL & ~E_NOTICE & ~E_STRICT & ~E_WARNING)
hhvm.log.runtime_error_reporting_level = 30709
hhvm.log.level = Warning
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.use_log_file = true
hhvm.log.file = /var/log/hhvm/error.log
hhvm.log.header = true
hhvm.log.injected_stack_trace = true
hhvm.log.natives_stack_trace = true

hhvm.error_handling.call_user_handler_on_fatals = true
hhvm.error_handling.no_infinite_recursion_detection = true
hhvm.error_handling.throw_bad_type_exceptions = true
hhvm.error_handling.throw_too_many_arguments = true
hhvm.error_handling.warn_too_many_arguments = true
hhvm.error_handling.throw_missing_arguments = true
hhvm.error_handling.throw_invalid_arguments = true

hhvm.mysql.slow_query_threshold = 30000
hhvm.mysql.typed_results = false

hhvm.jit_a_cold_size = 256M
hhvm.jit_a_frozen_size = 512M
hhvm.jit_a_hot_size = 0
hhvm.jit_a_prof_size = 512M
hhvm.jit_a_size = 512M
hhvm.jit_global_data_size = 256M

hhvm.repo.central.path = /mnt/hhvm/.hhvm.hhbc
hhvm.http.default_timeout = 600
hhvm.server.connection_timeout_seconds = 600
memory_limit = 2048M

; Fix for https://github.com/facebook/hhvm/issues/4993 until there's a more permanent fix
hhvm.enable_zend_ini_compat = false

; E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED
error_reporting = 22519
display_errors =  "0"

```

**Comment by lokeshhctm** [comment]
I see the same issue and not able to use persistent connection anywhere.
Did you find some fix for this?

**Comment by isegal** [comment]
We have not found a fix for this, we are simply allowing it to reconnect for every request for now.

**Comment by aorenste** [comment]
I think this is a dup of #6578 and #6542
