### ISSUE TITLE
DOMNode core dump in hhvm-nightly-dbg_2016.01.21~wheezy

### ISSUE THREAD

**Issue by josephscott** [facebook/hhvm#6778]
Ran into core dump issues with hhvm-nightly-dbg_2016.01.21~wheezy_amd64.deb, under Debian 7.8.

php.ini:
````
; php options
session.save_handler = files
session.save_path = /var/lib/hhvm/sessions
session.gc_maxlifetime = 1440

; hhvm specific 
hhvm.log.level = Warning
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.runtime_error_reporting_level = 8191
hhvm.mysql.typed_results = false
```

server.ini
```
; php options

pid = /var/run/hhvm/pid
expose_php = 0

; hhvm specific 
;
; hhvm.server.port = 9000
hhvm.server.file_socket = /var/run/hhvm/hhvm.sock
hhvm.server.type = fastcgi
hhvm.server.default_document = index.php
hhvm.log.use_log_file = true
hhvm.log.header = true
hhvm.log.file = /var/log/hhvm/error.log
hhvm.repo.central.path = /var/run/hhvm/hhvm.hhbc

hhvm.perf_pid_map = false
hhvm.log.use_log_file = true

hhvm.server.dns_cache.enable = true
hhvm.server.dns_cache.ttl = 600

; JIT settings based on ratios from
; https://github.com/facebook/hhvm/wiki/INI-Settings
;
; base
hhvm.jit_a_size = 524288000
; 0.5x of a_size
hhvm.jit_a_cold_size = 262144000
; 1.0x of a_size
hhvm.jit_a_frozen_size = 524288000
; 1.0x of a_size
hhvm.jit_a_prof_size = 524288000
; 1.0x of a_size
hhvm.jit_a_max_usage = 524288000

; localmods for debugging
hhvm.debug.native_stack_trace = true
hhvm.debug.full_backtrace = true
hhvm.debug.server_stack_trace = true
hhvm.debug.server_error_message = true
hhvm.debug.translate_source = true
hhvm.debug.record_input = false
hhvm.debug.clear_input_on_success = true
hhvm.debug.profiler_output_dir = /tmp
hhvm.debug.core_dump_report = true
hhvm.debug.core_dump_report_directory = /tmp
```

I collected five core dump files over a period of roughly 30 minutes.  Here is the output from gdb `thread apply all bt`:

- https://gist.github.com/anonymous/2836a901bc2d39a30b26
- https://gist.github.com/anonymous/ab4e85397e3da08de505
- https://gist.github.com/anonymous/9995283a5ba22a579cd0
- https://gist.github.com/anonymous/dd1f912ec2cffbf57157
- https://gist.github.com/anonymous/4a07bbc5816e85bf1e09

The memcache references in there stood out, I'm wondering if that is the problem.  Skimming through the recent commits turned up https://github.com/facebook/hhvm/commit/4281a8a50b971209ecd749b84e05e21bc4d335f5.

**Comment by fredemmott** [comment]
DOMNode, not memcached - at the top:

```
Program terminated with signal 6, Aborted.
#0  0x00007f8a4e664165 in raise () from /lib/x86_64-linux-gnu/libc.so.6
```

So, the responsible thread calls raise(); searching your dumps for raise always shows something like this:

```
#11 0x00007f928bb4a165 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#12 0x00007f928bb4d3e0 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#13 0x00007f928bb43311 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#14 0x00000000050653bb in HPHP::DOMNode::~DOMNode() ()
    at /tmp/tmp.mYZMLUqKuO/hphp/runtime/ext/domdocument/ext_domdocument.h:47
```

**Comment by josephscott** [comment]
Good to know, thanks.

**Comment by fredemmott** [comment]
would you be able to isolate some PHP code that triggers this?

**Comment by josephscott** [comment]
I've got an idea where in the code this might be, still need to sort exactly what conditions trigger it.

**Comment by josephscott** [comment]
My current suspect is a line of code that clones a DOMText object.  Something like:

```
$another_thing = clone $element;
```

I'm still trying to come up with a way to reproduce this with a stand alone piece of code.

**Comment by josephscott** [comment]
One more data point while I continue to keep digging.  Switching to:

```
$another_thing = $element->cloneNode( true );
```

Doesn't core dump, and appears to provide the correct data ( still need to confirm that ).

**Comment by fredemmott** [comment]
This is sad:

```
fred@hhvm-oss-bench:~/test$ cat test.php
<?php

function main() {
  $root = new DOMElement('html');
  $copy = clone $root;
}

main();
fred@hhvm-oss-bench:~/test$ hhvm test.php
hhvm: /tmp/tmp.a3Y9gerkau/hphp/runtime/ext/domdocument/ext_domdocument.h:48: virtual HPHP::DOMNode::~DOMNode(): Assertion `m_node->getCache() && Native::data<DOMNode>(m_node->getCache()) == this' failed.
Segmentation fault (core dumped)
```

**Comment by fredemmott** [comment]
cc @paulbiss

**Comment by josephscott** [comment]
Nice find.  When I was extracting the code to a separate stand alone test file I didn't have it in a function call anymore.  That seems to make the difference here.

**Comment by fredemmott** [comment]
Memory management for pseudomains and globals acts differently to locals; locals in functions/methods are more predictable (simple ref-counting) so it's generally easier to reproduce problems that way.
