### ISSUE TITLE
Conection refused error error when run oss-performance on HHVM.

### ISSUE THREAD

**Issue by racardoso** [facebook/hhvm#6973]
I'm  trying to run oss-performance (with siege 2.78) on **HHVM 3.13** (installed from package) with **nginx** and **fastcgi** on x86-64 machine with **Ubuntu 15.04.** Works fine for `toys-helloworld`,  `toys-fibonacci` and, `wordpress` but, fails on sanity check for the others benchmarks (laravel, magento, mediwiki, drupal). 

**Example:**
Running mediawiki: `hhvm perf.php --mediawiki --hhvm=/usr/bin/hhvm`
```
Warning: failed to connect to localhost [111]: Connection refused in /home/rcardoso/oss-performance/base/SystemChecks.php on line 83
...
f_is_readable/1039: No such file or directory (lots of this message) 
...
Warning: filemtime(): No such file or directory in /tmp/hhvm-nginxYmYKCF/mediawiki-1.26.2/includes/cache/CacheDependency.php on line 187
**************************
** 2016-04-08 07:28:21 PDT
** Running sanity check

Warning: Failed to open http://rcardoso:8090/ () in /home/rcardoso/oss-performance/base/PerfTarget.php on line 30

Fatal error: Uncaught exception 'HH\InvariantException' with message 'Failed to find string "Obama" in http://rcardoso:8090/' in /home/rcardoso/oss-performance/base/PerfTarget.php:34
Stack trace:
#0 /home/rcardoso/oss-performance/base/PerfTarget.php(34): HH\invariant_violation()
#1 /home/rcardoso/oss-performance/base/PerfRunner.php(99): PerfTarget->sanityCheck()
#2 /home/rcardoso/oss-performance/base/PerfRunner.php(42): PerfRunner::RunWithOptionsAndEngine()
#3 /home/rcardoso/oss-performance/base/PerfRunner.php(17): PerfRunner::RunWithOptions()
#4 /home/rcardoso/oss-performance/perf.php(15): PerfRunner::RunWithArgv()
#5 /home/rcardoso/oss-performance/perf.php(19): perf_main()
#6 {main}

Warning: Failed to open http://localhost:8091/check-health (Failed to connect to localhost port 8091: Connection refused) in /home/rcardoso/oss-performance/base/HHVMDaemon.php on line 343
Terminated
```

I have the same problem cloning from master and install it from package (HHVM 3.13). After that i clone **HHVM-3.11** tag in the same machine, with the same configuration and mediawiki (and the others tests) runs fine (that exclude some obvious configuration error). The problem seems to occur on versions 3.12 and 3.13.

**Comment by racardoso** [comment]
Appears to be related with task #6764 . Added `assert.active=false` on php.ini file solves the problem. A pull request will be opened to oss-performance.
