### ISSUE TITLE
HHVM segfault in test/quick/string_replace_overflow.php in release build

### ISSUE THREAD

**Issue by apeabody** [facebook/hhvm#7115]
### HHVM Version
HipHop VM 3.14.0-dev (rel)
Compiler: heads/master-0-g98e5d214dadde2a28458702ccfd06a7f7c221697
Repo schema: 30b087f6d4b189bf4529ac794888ebf32a1984cc

CentOS 7 64bit with gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)

This only occurs in release builds, NOT debug builds.

### Standalone code, or other way to reproduce the problem
Part of the quick test suite: test/quick/string_replace_overflow.php

gdb --args hhvm/hhvm -c /home/vagrant/hhvm/hphp/test/config.ini -vEval.EnableArgsInBacktraces=true -vEval.EnableIntrinsicsExtension=true -vRepo.Local.Mode=-- -vRepo.Central.Path=/home/vagrant/hhvm/hphp/hhvm/verify.hhbc -vEval.Jit=true -vResourceLimit.CoreFileSize=0 --file 'test/quick/string_replace_overflow.php'

### Expected result
success

### Actual result
Program received signal SIGSEGV, Segmentation fault.
0x000000000344779c in HPHP::StringData::release() ()
(gdb) bt
#0  0x000000000344779c in HPHP::StringData::release() ()
#1  0x0000000009600920 in ?? ()
#2  0x000000000460004f in ?? ()
#3  0x00007fffe4511e60 in ?? ()
#4  0x00007fffffffd140 in ?? ()
#5  0x00000000022bc02b in HPHP::jit::x64::enterTCImpl(unsigned char*, HPHP::ActRec*) ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

### NOTE
I'm aware that CentOS 7 is officially unsupported by the development team, however it is an very common distro outside FB and potential future.  This is mainly to confirm if this is a larger issue as I may attempt to investigate this further.

**Comment by apeabody** [comment]
Issue no longer manifests in current master branch.
