### ISSUE TITLE
HHVM segfault in test/quick/pcre_limit.php in release build

### ISSUE THREAD

**Issue by apeabody** [facebook/hhvm#7116]
### HHVM Version
HipHop VM 3.14.0-dev (rel)
Compiler: heads/master-0-g98e5d214dadde2a28458702ccfd06a7f7c221697
Repo schema: 30b087f6d4b189bf4529ac794888ebf32a1984cc

CentOS 7 64bit with gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)

This only occurs in release builds, NOT debug builds.

### Standalone code, or other way to reproduce the problem
Part of the quick test suite: test/quick/pcre_limit.php

gdb --args hhvm/hhvm -c /home/vagrant/hhvm/hphp/test/config.ini -vEval.EnableArgsInBacktraces=true -vEval.EnableIntrinsicsExtension=true -vRepo.Local.Mode=-- -vRepo.Central.Path=/home/vagrant/hhvm/hphp/hhvm/verify.hhbc -vEval.Jit=true -vResourceLimit.CoreFileSize=0 --file 'test/quick/pcre_limit.php'

### Expected result
success

### Actual result

Warning: REGEXERR: php_pcre_replace/1441: err=-8(PCRE_ERROR_MATCHLIMIT), pattern='/b.*b/', subject='baabaa<SNIPED FOR ISSUE>aaa', repl='', limits=(1000000, 100000), extra=(0, -1, 0, 0) in /home/vagrant/hhvm/hphp/test/quick/pcre_limit.php on line 4

Program received signal SIGSEGV, Segmentation fault.
0x000000000344779c in HPHP::StringData::release() ()
(gdb) bt
#0  0x000000000344779c in HPHP::StringData::release() ()
#1  0x0000000003459496 in HPHP::php_pcre_replace(HPHP::String const&, HPHP::String const&, HPHP::Variant const&, bool, int, int*) ()
#2  0x0000000003457f44 in HPHP::php_replace_in_subject(HPHP::Variant const&, HPHP::Variant const&, HPHP::String, int, bool, int*) ()
#3  0x00000000034575ff in HPHP::preg_replace_impl(HPHP::Variant const&, HPHP::Variant const&, HPHP::Variant const&, int, HPHP::Variant*, bool, bool) ()
#4  0x0000000003457522 in HPHP::f_preg_replace(HPHP::Variant const&, HPHP::Variant const&, HPHP::Variant const&, int, HPHP::VRefParamValue const&)
    ()
#5  0x0000000004600543 in ?? ()
#6  0x000000000460004f in ?? ()
#7  0x00007fffe44f7050 in ?? ()
#8  0x00007fffffffd140 in ?? ()
#9  0x00000000022bc02b in HPHP::jit::x64::enterTCImpl(unsigned char*, HPHP::ActRec*) ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

### NOTE
I'm aware that CentOS 7 is officially unsupported by the development team, however it is an very common distro outside FB and potential future.

**It initially looks like we are exceeding the PCRE_ERROR_MATCHLIMIT on CentOS 7, but that seems unlikely as I believe it is set at 10 million, and the backtrace shows we are in StringData when it segfaults.  I plan to look into this further when I have the time.**

**Comment by apeabody** [comment]
Issue no longer manifests in current master branch.
