### ISSUE TITLE
Guzzle failed on HHVM 3.15.0 but not on 3.14.5

### ISSUE THREAD

**Issue by firodj** [facebook/hhvm#7375]
Guzzle fail on hhvm 3.15.0 but not on 3.14.5.

### HHVM Version

HipHop VM 3.15.0 (rel)
Compiler: tags/HHVM-3.15.0-0-g92a682ebaa3c85b84857852d8621f528607fe27d
Repo schema: 225d4323575bbc8a498dc809a1c41354f6bca830

### Standalone code, or other way to reproduce the problem

```php
<?php

require 'vendor/autoload.php';

$client = new GuzzleHttp\Client();
$res = $client->request('GET', 'https://www.liputan6.com');
echo $res->getBody();
var_dump( $res->getHeader('content-type') );
echo $res->getStatusCode();
```

composer.json
```json
{
    "name": "vagrant/guzzle",
    "require": {
        "guzzlehttp/guzzle": "6.2.1"
    }
}
```

### Expected result

no exception!

### Actual result

```
Fatal error: Uncaught exception 'RuntimeException' with message 'Unable to determine stream position' in /home/vagrant/guzzle/vendor/guzzlehttp/psr7/src/Stream.php:184
Stack trace:
#0 /home/vagrant/guzzle/vendor/guzzlehttp/psr7/src/functions.php(278): GuzzleHttp\Psr7\Stream->tell()
#1 /home/vagrant/guzzle/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(176): GuzzleHttp\Psr7\rewind_body()
#2 /home/vagrant/guzzle/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(93): GuzzleHttp\RedirectMiddleware->modifyRequest()
#3 /home/vagrant/guzzle/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\RedirectMiddleware->checkRedirect()
#4 /home/vagrant/guzzle/vendor/guzzlehttp/promises/src/FulfilledPromise.php(39): Closure$GuzzleHttp\RedirectMiddleware::__invoke()
#5 /home/vagrant/guzzle/vendor/guzzlehttp/promises/src/TaskQueue.php(61): Closure$GuzzleHttp\Promise\FulfilledPromise::then()
#6 /home/vagrant/guzzle/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run()
#7 /home/vagrant/guzzle/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#8 /home/vagrant/guzzle/vendor/guzzlehttp/promises/src/Promise.php(266): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /home/vagrant/guzzle/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#10 /home/vagrant/guzzle/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#11 /home/vagrant/guzzle/vendor/guzzlehttp/guzzle/src/Client.php(129): GuzzleHttp\Promise\Promise->wait()
#12 /home/vagrant/guzzle/kutu.php(6): GuzzleHttp\Client->request()
#13 {main}
```

**Comment by paulbiss** [comment]
Hmm, as best I can find, the only change to ftell in 3.15 was f2f147e5a36339475a845ea9dde1e9b64edf8b5c.

**Comment by lesterchan** [comment]
Same problem as well on 3.15 when using it with AWS SDK (because it uses Guzzle). 3.14.5 works fine as @paulbiss mentioned.
```
A sha256 checksum could not be calculated for the provided upload body, because it was not seekable. To prevent this error you can either 1) include the ContentMD5 or ContentSHA256 parameters with your request, 2) use a seekable stream for the body, or 3) wrap the non-seekable stream in a GuzzleHttp\Psr7\CachingStream object. You should be careful though and remember that the CachingStream utilizes PHP temp streams. This means that the stream will be temporarily stored on the local disk.
```

**Comment by aorenste** [comment]
I'm able to repro this locally - I'll take a look.

**Comment by paulbiss** [comment]
@aorenste if you get a chance could you try reverting the rev I mentioned?

**Comment by aorenste** [comment]
@paulbiss - yup - that was the culprit.  ftell() on an empty TempFile was returning false instead of 0.  Fix submitted.

**Comment by fentie** [comment]
Is there a timeline for this to go into a tagged 3.15 release? We're having to downgrade to 3.12 LTS until this is readily available. Thanks!

**Comment by aorenste** [comment]
@fentie - I just added this to the list of cherry-picks so it should be in 3.15.3.
