### ISSUE TITLE
Segfault on HHBC compilation w/ stock Drupal 8

### ISSUE THREAD

**Issue by Kazanir** [facebook/hhvm#7462]
Suddenly I'm having a fun time trying to compile Drupal 8 with HHVM:

### HHVM Version

3.15.2

### Standalone code, or other way to reproduce the problem

A fresh clone of Drupal 8's 8.3.x branch (and subsequent `composer install`) should be able to repro this.

```
$ git clone git@github.com:drupal/drupal.git --branch=8.3.x
Cloning into 'drupal'...
$ cd drupal/
$ composer install
...
$ sudo hhvm-repo-mode enable .
...
creating binary HHBC files...

Assertion failure: /tmp/tmp.VdL4MxbDR6/hphp/hhbbc/index.cpp:1462: void HPHP::HHBBC::{anonymous}::check_invariants(HPHP::HHBBC::IndexData&): assertion `std::next(begin(range)) == end(range)' failed.


Core dumped: Aborted
```

### Expected result

HHBC compilation works.

### Actual result

HHBC compilation does not work. Stack traces:

```
Assertion failure: /tmp/tmp.VdL4MxbDR6/hphp/hhbbc/index.cpp:1462: void HPHP::HHBBC::{anonymous}::check_invariants(HPHP::HHBBC::IndexData&): assertion `std::next(begin(range)) == end(range)' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff0128cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff0128cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff012c0d8 in __GI_abort () at abort.c:89
#2  0x0000000004ec8fcb in HPHP::assert_fail (e=0x78dc748 "std::next(begin(range)) == end(range)",
    file=0x78dc2d0 "/tmp/tmp.VdL4MxbDR6/hphp/hhbbc/index.cpp", line=1462,
    func=0x78e4780 <HPHP::HHBBC::(anonymous namespace)::check_invariants(HPHP::HHBBC::IndexData&)::__PRETTY_FUNCTION__> "void HPHP::HHBBC::{anonymous}::check_invariants(HPHP::HHBBC::IndexData&)", msg="") at /tmp/tmp.VdL4MxbDR6/hphp/util/assertions.cpp:80
#3  0x0000000004fbab70 in HPHP::HHBBC::(anonymous namespace)::check_invariants (data=...) at /tmp/tmp.VdL4MxbDR6/hphp/hhbbc/index.cpp:1462
#4  0x0000000004fbc376 in HPHP::HHBBC::Index::Index (this=0x7fffffffda10, program=0x7fffe67c0320) at /tmp/tmp.VdL4MxbDR6/hphp/hhbbc/index.cpp:1734
#5  0x0000000004f00a3e in HPHP::HHBBC::whole_program (ues=std::vector of length 0, capacity 16384)
    at /tmp/tmp.VdL4MxbDR6/hphp/hhbbc/whole-program.cpp:407
#6  0x0000000004cc887d in HPHP::Compiler::emitAllHHBC(std::shared_ptr<HPHP::AnalysisResult>&&) (
    ar=<unknown type in /usr/bin/hhvm, CU 0x7376b9, DIE 0x95042e>) at /tmp/tmp.VdL4MxbDR6/hphp/compiler/analysis/emitter.cpp:11004
#7  0x0000000004c1cc08 in HPHP::hhbcTarget(HPHP::CompilerOptions const&, std::shared_ptr<HPHP::AnalysisResult>&&, HPHP::AsyncFileCacheSaver&) (
    po=..., ar=<unknown type in /usr/bin/hhvm, CU 0x3fac88, DIE 0x548e5c>, fcThread=...) at /tmp/tmp.VdL4MxbDR6/hphp/compiler/compiler.cpp:828
#8  0x0000000004c1bf3f in HPHP::process (po=...) at /tmp/tmp.VdL4MxbDR6/hphp/compiler/compiler.cpp:651
#9  0x0000000004c18e64 in HPHP::compiler_main (argc=10, argv=0x7fffffffe630) at /tmp/tmp.VdL4MxbDR6/hphp/compiler/compiler.cpp:177
#10 0x0000000004c088e8 in main (argc=11, argv=0x7fffffffe628) at /tmp/tmp.VdL4MxbDR6/hphp/hhvm/main.cpp:39
```

This stack trace is from a not-quite-vanilla Drupal 8 install, but once I was able to replicate this with stock D8 I gave up on trying to hunt for offending files.

```
hhvm: /tmp/tmp.VdL4MxbDR6/hphp/compiler/statement/interface_statement.h:57: HPHP::ClassScopeRawPtr HPHP::InterfaceStatement::getClassScope() const: Assertion `b->is(BlockScope::ClassScope)' failed.

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffdebff700 (LWP 24147)]
0x00007ffff0128cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff0128cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff012c0d8 in __GI_abort () at abort.c:89
#2  0x00007ffff0121b86 in __assert_fail_base (fmt=0x7ffff0272830 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=assertion@entry=0x76b8f22 "b->is(BlockScope::ClassScope)",
    file=file@entry=0x76b8ee0 "/tmp/tmp.VdL4MxbDR6/hphp/compiler/statement/interface_statement.h", line=line@entry=57,
    function=function@entry=0x76c9360 <HPHP::InterfaceStatement::getClassScope() const::__PRETTY_FUNCTION__> "HPHP::ClassScopeRawPtr HPHP::InterfaceStatement::getClassScope() const") at assert.c:92
#3  0x00007ffff0121c32 in __GI___assert_fail (assertion=0x76b8f22 "b->is(BlockScope::ClassScope)",
    file=0x76b8ee0 "/tmp/tmp.VdL4MxbDR6/hphp/compiler/statement/interface_statement.h", line=57,
    function=0x76c9360 <HPHP::InterfaceStatement::getClassScope() const::__PRETTY_FUNCTION__> "HPHP::ClassScopeRawPtr HPHP::InterfaceStatement::getClassScope() const") at assert.c:101
#4  0x0000000004c541b0 in HPHP::InterfaceStatement::getClassScope (this=0x7fffb3c1b818)
    at /tmp/tmp.VdL4MxbDR6/hphp/compiler/statement/interface_statement.h:57
#5  0x0000000004c945c4 in HPHP::Compiler::EmitterVisitor::visit (this=0x7fffdebfa0f0, file=std::shared_ptr (count 5, weak 1) 0x7fffb3d4c918)
    at /tmp/tmp.VdL4MxbDR6/hphp/compiler/analysis/emitter.cpp:3506
#6  0x0000000004cc6832 in HPHP::Compiler::emitHHBCUnitEmitter (ar=std::shared_ptr (count 34, weak 1) 0x7fffe6789418,
    fsp=std::shared_ptr (count 5, weak 1) 0x7fffb3d4c918, md5=...) at /tmp/tmp.VdL4MxbDR6/hphp/compiler/analysis/emitter.cpp:10584
#7  0x0000000004cc7502 in HPHP::Compiler::emitHHBCVisitor (ar=std::shared_ptr (count 34, weak 1) 0x7fffe6789418, fsp=...)
    at /tmp/tmp.VdL4MxbDR6/hphp/compiler/analysis/emitter.cpp:10788
#8  0x0000000004cc7b9c in HPHP::Compiler::EmitterWorker::doJob (this=0x7fffaa043b80, job=...)
    at /tmp/tmp.VdL4MxbDR6/hphp/compiler/analysis/emitter.cpp:10851
#9  0x0000000004cecb26 in HPHP::JobQueueWorker<HPHP::hphp_raw_ptr<HPHP::FileScope>, void*, true, true, HPHP::detail::NoDropCachePolicy>::start (
    this=0x7fffaa043b80) at /tmp/tmp.VdL4MxbDR6/hphp/util/job-queue.h:462
#10 0x0000000004c1f9a8 in HPHP::AsyncFunc<HPHP::AsyncFileCacheSaver>::run_ (obj=0x7fffd3c82a00) at /tmp/tmp.VdL4MxbDR6/hphp/util/async-func.h:198
#11 0x0000000004edbe0d in HPHP::AsyncFuncImpl::threadFuncImpl (this=0x7fffd3c82a00) at /tmp/tmp.VdL4MxbDR6/hphp/util/async-func.cpp:134
#12 0x0000000004edb9ff in HPHP::AsyncFuncImpl::ThreadFunc (obj=0x7fffd3c82a00) at /tmp/tmp.VdL4MxbDR6/hphp/util/async-func.cpp:54
#13 0x000000000533965e in HPHP::start_routine_wrapper (arg=0x7fffcf78e860) at /tmp/tmp.VdL4MxbDR6/hphp/runtime/base/thread-hooks.cpp:105
#14 0x00007ffff57f8182 in start_thread (arg=0x7fffdebff700) at pthread_create.c:312
#15 0x00007ffff01ec47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by racardoso** [comment]
@Kazanir check this thread https://github.com/facebook/hhvm/issues/7477 seems the same problem Ihave.

**Comment by mofarrell** [comment]
Thanks @racardoso.  @Kazanir comment if it is not fixed.
