### ISSUE TITLE
SSE42 causing crash with AsyncMySQL

### ISSUE THREAD

**Issue by simonwelsh** [facebook/hhvm#7471]
### HHVM Version
3.15.2, 3.1.6.0-dev (2016.10.03~trusty)
### Standalone code, or other way to reproduce the problem
```hack
<?hh

class Test {
  public static async function doStuff(): Awaitable<mixed> {
    $conn = await self::get_connection();

    return await HH\Asio\vmk(
      ['foo' => 'bar'],
      async ($path, $name) ==> {
        return await $conn->queryf('SELECT * FROM users');
      },
    );
  }

  public static async function get_connection(
  ): Awaitable<AsyncMysqlConnection> {
    // Get a connection pool with default options
    $pool = new AsyncMysqlConnectionPool(array());
    return await $pool->connect('127.0.0.1', 3306, 'mysql', 'root', '');
  }
}

var_dump(HH\Asio\join(Test::doStuff()));
```
### Expected result
Some users get outputted
### Actual result
Crash.

```
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1106 04:19:05.098094 16547 RangeSse42.cpp:32] Check failed: false Function qfind_first_byte_of_sse42 only works with SSE42!
*** Check failure stack trace: ***
Core dumped: Aborted
Stack trace in /tmp/stacktrace.16543.log
Aborted
```

Currently install hhvm-nightly-dbg to hopefully get a stack trace.

This may just be a packing issue with the Ubuntu Trusty packages.

**Comment by simonwelsh** [comment]
gdb backtrace:
```
#0  0x00007fffeff1cc37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fffeff20028 in __GI_abort () at abort.c:89
#2  0x00007ffff5e3ed81 in ?? () from /usr/lib/x86_64-linux-gnu/libglog.so.0
#3  0x00007ffff5e3edaa in google::LogMessage::Fail() () from /usr/lib/x86_64-linux-gnu/libglog.so.0
#4  0x00007ffff5e3ece4 in google::LogMessage::SendToLog() () from /usr/lib/x86_64-linux-gnu/libglog.so.0
#5  0x00007ffff5e3e6e6 in google::LogMessage::Flush() () from /usr/lib/x86_64-linux-gnu/libglog.so.0
#6  0x00007ffff5e41687 in google::LogMessageFatal::~LogMessageFatal() () from /usr/lib/x86_64-linux-gnu/libglog.so.0
#7  0x00000000070e9534 in folly::detail::qfind_first_byte_of_sse42 (haystack=..., needles=...) at /tmp/tmp.J0LG84lGj1/third-party/folly/src/folly/detail/RangeSse42.cpp:32
#8  0x0000000006fc4221 in folly::detail::qfind_first_byte_of (haystack=..., needles=...) at /tmp/tmp.J0LG84lGj1/third-party/folly/folly/Range.h:1031
#9  0x0000000006fc4259 in folly::qfind_first_of<char const*> (haystack=..., needles=...) at /tmp/tmp.J0LG84lGj1/third-party/folly/folly/Range.h:1143
#10 0x0000000006fcbc20 in folly::Range<char const*>::find_first_of (this=0x7fffe0930800, needles=...) at /tmp/tmp.J0LG84lGj1/third-party/folly/folly/Range.h:532
#11 0x0000000006fc9e44 in folly::Range<char const*>::find_first_of (this=0x7fffe0930800, needles=0x8e1d17f ";'\"`") at /tmp/tmp.J0LG84lGj1/third-party/folly/folly/Range.h:543
#12 0x0000000006fc74d7 in facebook::common::mysql_client::Query::render (this=0x7fffe1abab50, conn=0x7fffe1a81600, params=std::vector of length 0, capacity 0)
    at /tmp/tmp.J0LG84lGj1/third-party/squangle/squangle/mysql_client/Query.cpp:453
#13 0x0000000006fc7438 in facebook::common::mysql_client::Query::render (this=0x7fffe1abab50, conn=0x7fffe1a81600) at /tmp/tmp.J0LG84lGj1/third-party/squangle/squangle/mysql_client/Query.cpp:441
#14 0x0000000006fc72fc in facebook::common::mysql_client::Query::renderMultiQuery (connection=0x7fffe1a81600, queries=std::vector of length 1, capacity 1 = {...})
    at /tmp/tmp.J0LG84lGj1/third-party/squangle/squangle/mysql_client/Query.cpp:425
#15 0x0000000006fc8237 in facebook::common::mysql_client::MultiQuery::renderQuery (this=0x7fffe19fbf18, conn=0x7fffe1a81600) at /tmp/tmp.J0LG84lGj1/third-party/squangle/squangle/mysql_client/Query.cpp:600
#16 0x0000000006fb4c23 in facebook::common::mysql_client::FetchOperation::specializedRunImpl (this=0x7fffe19fbe18) at /tmp/tmp.J0LG84lGj1/third-party/squangle/squangle/mysql_client/Operation.cpp:616
#17 0x0000000006fbc423 in std::_Mem_fn<void (facebook::common::mysql_client::ConnectOperation::*)()>::operator()<, void>(facebook::common::mysql_client::ConnectOperation*) const (this=0x7fffe1e8e180, __object=0x7fffe19fbe18)
    at /usr/include/c++/4.8/functional:601
#18 0x0000000006fbb7fc in std::_Bind<std::_Mem_fn<void (facebook::common::mysql_client::ConnectOperation::*)()> (facebook::common::mysql_client::ConnectOperation*)>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (
    this=0x7fffe1e8e180, __args=<unknown type in /usr/bin/hhvm, CU 0x375dff79, DIE 0x3765f520>) at /usr/include/c++/4.8/functional:1296
#19 0x0000000006fbb43a in std::_Bind<std::_Mem_fn<void (facebook::common::mysql_client::FetchOperation::*)()> (facebook::common::mysql_client::FetchOperation*)>::operator()<, void>() (this=0x7fffe1e8e180)
    at /usr/include/c++/4.8/functional:1355
#20 0x0000000006fba9b6 in std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (facebook::common::mysql_client::FetchOperation::*)()> (facebook::common::mysql_client::FetchOperation*)> >::_M_invoke(std::_Any_data const&) (
    __functor=...) at /usr/include/c++/4.8/functional:2071
#21 0x0000000004afe092 in std::function<void ()>::operator()() const (this=0x7fffe199ceb0) at /usr/include/c++/4.8/functional:2471
#22 0x0000000006fa2eff in facebook::common::mysql_client::AsyncMysqlClient::__lambda136::operator() (__closure=0x7fffe199ceb0) at /tmp/tmp.J0LG84lGj1/third-party/squangle/squangle/mysql_client/AsyncMysqlClient.cpp:93
#23 0x0000000006faabec in folly::detail::function::FunctionTraits<void()>::callBig<facebook::common::mysql_client::AsyncMysqlClient::runInThread(folly::Cob&&)::__lambda136>(folly::detail::function::Data &) (p=...)
    at /tmp/tmp.J0LG84lGj1/third-party/folly/folly/Function.h:297
#24 0x00000000070c0077 in folly::detail::function::FunctionTraits<void ()>::operator()() (this=0x7fffe0930d70) at /tmp/tmp.J0LG84lGj1/third-party/folly/folly/Function.h:306
#25 0x0000000007131e2e in folly::EventBase::FunctionRunner::messageAvailable(folly::Function<void ()>&&) (this=0x7fffe19f4520, msg=<unknown type in /usr/bin/hhvm, CU 0x37dae1c6, DIE 0x37dd708c>)
    at /tmp/tmp.J0LG84lGj1/third-party/folly/src/folly/io/async/EventBase.cpp:80
#26 0x00000000071394b7 in folly::NotificationQueue<folly::Function<void ()> >::Consumer::consumeMessages(bool, unsigned long*) (this=0x7fffe19f4520, isDrain=false, numConsumed=0x0)
    at /tmp/tmp.J0LG84lGj1/third-party/folly/folly/io/async/NotificationQueue.h:727
#27 0x000000000713853a in folly::NotificationQueue<folly::Function<void ()> >::Consumer::handlerReady(unsigned short) (this=0x7fffe19f4520) at /tmp/tmp.J0LG84lGj1/third-party/folly/folly/io/async/NotificationQueue.h:664
#28 0x000000000710c0ed in folly::EventHandler::libeventCallback (fd=14, events=2, arg=0x7fffe19f4530) at /tmp/tmp.J0LG84lGj1/third-party/folly/src/folly/io/async/EventHandler.cpp:160
#29 0x00007ffff62daf24 in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
#30 0x00000000071351db in folly::EventBase::loopBody (this=0x7fffe1f49040, flags=0) at /tmp/tmp.J0LG84lGj1/third-party/folly/src/folly/io/async/EventBase.cpp:359
#31 0x0000000007134d69 in folly::EventBase::loop (this=0x7fffe1f49040) at /tmp/tmp.J0LG84lGj1/third-party/folly/src/folly/io/async/EventBase.cpp:297
#32 0x0000000007135f9d in folly::EventBase::loopForever (this=0x7fffe1f49040) at /tmp/tmp.J0LG84lGj1/third-party/folly/src/folly/io/async/EventBase.cpp:474
#33 0x0000000006fa2d88 in facebook::common::mysql_client::AsyncMysqlClient::__lambda135::operator() (__closure=0x7fffe1931530) at /tmp/tmp.J0LG84lGj1/third-party/squangle/squangle/mysql_client/AsyncMysqlClient.cpp:78
#34 0x0000000006fb0f20 in std::_Bind_simple<facebook::common::mysql_client::AsyncMysqlClient::init()::__lambda135()>::_M_invoke<>(std::_Index_tuple<>) (this=0x7fffe1931530) at /usr/include/c++/4.8/functional:1732
#35 0x0000000006fb0c95 in std::_Bind_simple<facebook::common::mysql_client::AsyncMysqlClient::init()::__lambda135()>::operator()(void) (this=0x7fffe1931530) at /usr/include/c++/4.8/functional:1720
#36 0x0000000006fb0828 in std::thread::_Impl<std::_Bind_simple<facebook::common::mysql_client::AsyncMysqlClient::init()::__lambda135()> >::_M_run(void) (this=0x7fffe1931518) at /usr/include/c++/4.8/thread:115
#37 0x00007ffff0878a60 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#38 0x00007ffff57f8184 in start_thread (arg=0x7fffe0935700) at pthread_create.c:312
#39 0x00007fffeffe037d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by mofarrell** [comment]
https://github.com/facebook/hhvm/issues/7448
This will be fixed with the next third-party update.
