### ISSUE TITLE
Segfault running oss-performance wordpress

### ISSUE THREAD

**Issue by gdbentley** [facebook/hhvm#7487]
### HHVM Version
commit: e0d2d14 (the previous day's run with commit 0ab2327 was successful)

### Standalone code, or other way to reproduce the problem
oss-performance wordpress
See https://01.org/lp/documentation/hhvm-environment-setup

### Expected result
Successful completion with a number of requests per second reported.

### Actual result
Segmentation fault with the following backtrace:

```
#0  std::_Hashtable<std::string, std::pair<std::string const, std::shared_ptr<HPHP::FileScope> >, std::allocator<std::pair<std::string const, std::shared_ptr<HPHP::FileScope> > >, std::__detail::_Select1st, std::equal_to<std::string>, HPHP::string_hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_find_before_node (this=this@entry=0x7fffdb676b08, __n=1, __k="magic_quotes_runtime", __code=444412608672435771) at /usr/lib/gcc/x86_64-redhat-linux/4.8.3/../../../../include/c++/4.8.3/bits/hashtable.h:1162
#1  0x00000000012dbf85 in _M_find_node (__c=<optimized out>, __key="magic_quotes_runtime", __bkt=<optimized out>, this=0x7fffdb676b08)
    at /usr/lib/gcc/x86_64-redhat-linux/4.8.3/../../../../include/c++/4.8.3/bits/hashtable.h:604
#2  std::_Hashtable<std::string, std::pair<std::string const, HPHP::Variant>, std::allocator<std::pair<std::string const, HPHP::Variant> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::find (this=this@entry=0x7fffdb676b08,
    __k="magic_quotes_runtime") at /usr/lib/gcc/x86_64-redhat-linux/4.8.3/../../../../include/c++/4.8.3/bits/hashtable.h:1025
#3  0x0000000002377ce6 in find (__x="magic_quotes_runtime", this=<optimized out>) at /usr/lib/gcc/x86_64-redhat-linux/4.8.3/../../../../include/c++/4.8.3/bits/unordered_map.h:543
#4  HPHP::IniSetting::SetUser (name=..., value=...) at hphp/runtime/base/ini-setting.cpp:1091
#5  0x000000000237768a in HPHP::f_ini_set (varname=..., newvalue=...) at hphp/runtime/ext/std/ext_std_options.cpp:875
#6  0x00000000014b462d in HPHP::Native::callFuncIndirectImpl<HPHP::Variant> (f=<optimized out>, GP=GP@entry=0x7fffd9bfa6d0, GP_count=<optimized out>, SIMD=SIMD@entry=0x7fffd9bfa690,
    SIMD_count=SIMD_count@entry=0) at hphp/runtime/vm/native-func-caller.h:2253
#7  0x000000000235c3fb in HPHP::Native::callFunc<true> (func=func@entry=0x7fffdc6b3b80, ctx=ctx@entry=0x0, args=args@entry=0x7fffd5bbfda0, numNonDefault=numNonDefault@entry=2, ret=...)
    at hphp/runtime/vm/native.cpp:202
#8  0x0000000001579f0e in HPHP::iopFCallBuiltin (numArgs=..., numNonDefault=..., id=<optimized out>) at hphp/runtime/vm/bytecode.cpp:4756
#9  0x000000000157a0dc in HPHP::iopWrapper (pc=<optimized out>, op=<optimized out>, fn=0x1579e30 <HPHP::iopFCallBuiltin(HPHP::intva_t, HPHP::intva_t, int)>)
    at hphp/runtime/vm/bytecode.cpp:6530
#10 0x00000000023b26a3 in HPHP::dispatchImpl<false> () at hphp/runtime/vm/bytecode.cpp:6781
#11 0x00000000015a7435 in dispatch () at hphp/runtime/vm/bytecode.cpp:6798
#12 HPHP::enterVMAtFunc (enterFnAr=enterFnAr@entry=0x7fffd5bbffc0, stk=<optimized out>, varEnv=varEnv@entry=0x7fffd5811810) at hphp/runtime/vm/bytecode.cpp:1512
#13 0x00000000012b5ed7 in operator() (__closure=<synthetic pointer>) at hphp/runtime/base/execution-context.cpp:1643
#14 exception_handler<HPHP::ExecutionContext::invokeFunc(const HPHP::Func*, const HPHP::Variant&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags, bool)::__lambda161::__lambda162> (action=...) at hphp/runtime/vm/unwind-inl.h:30
#15 operator() (__closure=<synthetic pointer>) at hphp/runtime/base/execution-context.cpp:1573
#16 enterVMCustomHandler<HPHP::enterVM(HPHP::ActRec*, Action) [with Action = HPHP::ExecutionContext::invokeFunc(const HPHP::Func*, const HPHP::Variant&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags, bool)::__lambda161::__lambda162]::__lambda158> (action=..., ar=0x7fffd5bbffc0)
    at hphp/runtime/base/execution-context.cpp:1564
#17 enterVM<HPHP::ExecutionContext::invokeFunc(const HPHP::Func*, const HPHP::Variant&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags, bool)::__lambda161::__lambda162> (action=..., ar=0x7fffd5bbffc0) at hphp/runtime/base/execution-context.cpp:1573
#18 operator() (ar=0x7fffd5bbffc0, __closure=<synthetic pointer>) at hphp/runtime/base/execution-context.cpp:1644
#19 invokeFuncImpl<HPHP::ExecutionContext::invokeFunc(const HPHP::Func*, const HPHP::Variant&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags, bool)::__lambda159, HPHP::ExecutionContext::invokeFunc(const HPHP::Func*, const HPHP::Variant&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags, bool)::__lambda160, HPHP::ExecutionContext::invokeFunc(const HPHP::Func*, const HPHP::Variant&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags, bool)::__lambda161> (
    doEnterVM=..., doInitArgs=..., doStackCheck=..., useWeakTypes=false, invName=0x0, argc=0, cls=0x0, thiz=0x0, f=0x7fffdc718b30, this=0x7fffd580e010)
    at hphp/runtime/base/execution-context.cpp:1535
#20 HPHP::ExecutionContext::invokeFunc (this=this@entry=0x7fffd580e010, f=0x7fffdc718b30, args_=..., thiz=thiz@entry=0x0, cls=cls@entry=0x0, varEnv=0x7fffd5811810, invName=invName@entry=0x0,
    flags=flags@entry=HPHP::ExecutionContext::InvokePseudoMain, useWeakTypes=useWeakTypes@entry=false) at hphp/runtime/base/execution-context.cpp:1648
#21 0x00000000012b6477 in HPHP::ExecutionContext::invokeUnit (this=0x7fffd580e010, unit=0x7fffdc6e4d40) at hphp/runtime/base/execution-context.cpp:1265
#22 0x00000000023939fd in invoke_file_impl (currentDir=0x1 <Address 0x1 out of bounds>, once=true, path=..., res=...) at hphp/runtime/base/builtin-functions.cpp:909
#23 HPHP::invoke_file (s=..., once=once@entry=true, currentDir=currentDir@entry=0x23ce508 "") at hphp/runtime/base/builtin-functions.cpp:922
#24 0x0000000002393c92 in HPHP::include_impl_invoke (file=..., once=once@entry=true, currentDir=currentDir@entry=0x23ce508 "")
    at hphp/runtime/base/builtin-functions.cpp:933
#25 0x00000000023929b5 in HPHP::hphp_invoke (context=context@entry=0x7fffd580e010, cmd="/tmp/hhvm-nginxQ4yUhb/wordpress/index.php", func=func@entry=false, funcParams=..., funcRet=..., reqInitFunc=...,
    reqInitDoc="", error=@0x7fffd9bfadef: false, errorMsg="Internal Server Error", once=once@entry=true, warmupOnly=warmupOnly@entry=false, richErrorMsg=richErrorMsg@entry=false)
    at hphp/runtime/base/program-functions.cpp:2273
#26 0x000000000141efe3 in HPHP::HttpRequestHandler::executePHPRequest (this=this@entry=0x7fffdb6d8790, transport=transport@entry=0x7fffd5a4b818, reqURI=..., sourceRootInfo=...)
    at hphp/runtime/server/http-request-handler.cpp:473
#27 0x000000000238abf6 in HPHP::HttpRequestHandler::handleRequest (this=0x7fffdb6d8790, transport=0x7fffd5a4b818) at hphp/runtime/server/http-request-handler.cpp:375
#28 0x00000000023898f9 in HPHP::ServerWorker<std::shared_ptr<HPHP::ProxygenJob>, HPHP::ProxygenTransportTraits>::doJobImpl (this=0x7fffdb704d00, job=std::shared_ptr (count 3, weak 0) 0x7fffd5ad29d8,
    abort=abort@entry=false) at hphp/runtime/server/server-worker.h:110
#29 0x00000000023892aa in HPHP::ServerWorker<std::shared_ptr<HPHP::ProxygenJob>, HPHP::ProxygenTransportTraits>::doJob (this=<optimized out>, job=...)
    at hphp/runtime/server/server-worker.h:56
#30 0x0000000002389032 in HPHP::JobQueueWorker<std::shared_ptr<HPHP::ProxygenJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start (this=0x7fffdb704d00)
    at hphp/util/job-queue.h:462
#31 0x00000000010b8390 in HPHP::AsyncFuncImpl::threadFuncImpl (this=this@entry=0x7fffd5ad6000) at hphp/util/async-func.cpp:134 ---Type <return> to continue, or q <return> to quit---
#32 0x00000000010b854b in HPHP::AsyncFuncImpl::ThreadFunc (obj=0x7fffd5ad6000) at hphp/util/async-func.cpp:54
#33 0x000000000134c587 in HPHP::start_routine_wrapper (arg=0x7fffd5a13280) at hphp/runtime/base/thread-hooks.cpp:105
#34 0x00007ffff57c2df5 in start_thread (arg=0x7fffd9bff700) at pthread_create.c:308
#35 0x00007ffff061f1ad in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
```

**Comment by edwinsmith** [comment]
any chance you have a smaller repro for this?  I have a guess at what might be going wrong

**Comment by edwinsmith** [comment]
@drewklein nevermind the repro, i have a small repro of what i think is happening, and a fix. if you want to try the fix with the oss benchmarks, apply this:
https://gist.github.com/edwinsmith/1940a6128fe9ac7accd282b470e8e72c

**Comment by drewklein** [comment]
That patch does fix the oss issue.

**Comment by gdbentley** [comment]
@edwinsmith I've confirmed that commit a6de3bf9 fixes the segfault.
