### ISSUE TITLE
'BadMethodCallException' in oss-performance WordPress

### ISSUE THREAD

**Issue by octmoraru** [facebook/hhvm#7735]
### HHVM Version
master branch, commit 41aaf5c344df77cb7de8ec9bdcb21fcb3aee2c1a
### Standalone code, or other way to reproduce the problem
To quickly reproduce the problem, just run oss-performance with the WordPress target:
```
$ hhvm perf.php --wordpress --hhvm=/path/to/hhvm
```
You should get something like:
```
**************************
** 2017-03-17 17:06:11 PDT
** Starting PHP Engine
running hphp...
all files saved in /tmp/hhvm-nginxo3HrRw ...
running hphp took 0'06" (6718814 us) wall time

**************************
** 2017-03-17 17:06:20 PDT
** Unfreezing framework

Warning: Failed to open http://localhost:8090/ () in /path/to/oss-performance/targets/wordpress/WordpressTarget.php on line 100

Fatal error: Uncaught exception 'HH\InvariantException' with message 'Failed to unfreeze http://localhost:8090/ after 60.000000 secs' in /path/to/oss-performance/targets/wordpress/WordpressTarget.php:106
Stack trace:
#0 /path/to/oss-performance/targets/wordpress/WordpressTarget.php(106): HH\invariant_violation()
#1 /path/to/oss-performance/targets/wordpress/WordpressTarget.php(90): WordpressTarget->unfreezeRequest()
#2 /path/to/oss-performance/base/PerfRunner.php(93): WordpressTarget->unfreeze()
#3 /path/to/oss-performance/base/PerfRunner.php(42): PerfRunner::RunWithOptionsAndEngine()
#4 /path/to/oss-performance/base/PerfRunner.php(17): PerfRunner::RunWithOptions()
#5 /path/to/oss-performance/perf.php(15): PerfRunner::RunWithArgv()
#6 /path/to/oss-performance/perf.php(19): perf_main()
#7 {main}

```
To get more useful information, you can do the following set-up:

1. Get WordPress website from [oss-performance](https://github.com/hhvm/oss-performance/blob/master/targets/wordpress/wordpress-4.2.0.tar.gz) and extract sources into some dir.
```
$ pwd
/home/user/testdir
$ tar xzf wordpress-4.2.0.tar.gz
```
2. Build bytecode repo, just as oss-performance does.
```
$ hhvm --hphp --target hhbc --output-dir /home/user/testdir --input-dir /home/user/testdir/wordpress --module / --cmodule / -l3 -k1 --file-cache /home/user/testdir/static.content
```

3. Start HHVM in server mode just as oss-performance does (you must also have nginx/apache set up beforehand):
```
$ hhvm -m server -p 8092 -v AdminServer.Port=8093 -v Server.Type=proxygen -v Server.DefaultDocument=index.php -v Server.ErrorDocument404=index.php -v Server.SourceRoot=/home/user/testdir/wordpress -v Eval.Jit=1 -d pid='/home/user/testdir/hhvm.pid' -c /path/to/oss-performance/conf/php.ini -v Repo.Authoritative=true -v Repo.Central.Path=/home/user/testdir/hhvm.hhbc -v Server.FileCache=/home/user/testdir/static.content -v Server.SourceRoot=/home/user/testdir/wordpress
```

4. Make two HTTP requests to the home page. First one will succeed, second one will give you a 500 error.
```
$ wget http://127.0.0.1:8090
--2017-03-17 17:02:47--  http://127.0.0.1:8090/
Connecting to 127.0.0.1:8090... connected.
HTTP request sent, awaiting response... 200 OK
Length: 38367 (37K) [text/html]
Saving to: ‘index.html’

100%[========================================>] 38,367      --.-K/s   in 0s      

2017-03-17 17:02:48 (372 MB/s) - ‘index.html’ saved [38367/38367]

$ wget http://127.0.0.1:8090
--2017-03-17 17:02:51--  http://127.0.0.1:8090/
Connecting to 127.0.0.1:8090... connected.
HTTP request sent, awaiting response... 500 hphp_invoke
2017-03-17 17:02:51 ERROR 500: hphp_invoke.
```
The actual error is:
```
Fatal error: Uncaught exception 'BadMethodCallException' with message 'Call to a member function switch_to_blog() on a non-object (null)' in /home/user/testdir/wordpress/wp-includes/cache.php:195
Stack trace:
#0 /home/user/testdir/wordpress/wp-includes/load.php(449): wp_cache_switch_to_blog()
#1 /home/user/testdir/wordpress/wp-settings.php(86): wp_start_object_cache()
#2 /home/user/testdir/wordpress/wp-config.php(111): include()
#3 /home/user/testdir/wordpress/wp-load.php(37): include()
#4 /home/user/testdir/wordpress/wp-blog-header.php(12): include()
#5 /home/user/testdir/wordpress/index.php(17): include()
#6 {main}

```

**Comment by jim-saxman** [comment]
@octmoraru This is a very nice bug description. I ran into this issue on an ARM system and confirmed that commit  41aaf5c causes the failure.

**Comment by PengfeiZheng** [comment]
I also encountered this issue. I cannot run the benchmarks. How could I solve it?

**Comment by fredemmott** [comment]
This is expected on 4.0 - neither oss-performance or wordpress are supported.

**Comment by PengfeiZheng** [comment]
@fredemmott Thanks for letting me know this! Where could I download an older prebuilt version of HHVM? Is there an archive? Or... I have to compile from an older branch and deal with compiling errors.
