### ISSUE TITLE
Segfault with HHVM 3.18.2 in hhvm_zlib_encode()

### ISSUE THREAD

**Issue by mmuehlenhoff** [facebook/hhvm#7860]
HHVM 3.18.2 running on Debian jessie segfaulted with the following backtrace in a mediawiki setup, unfortunately I can't pin this a specific reproducer at this point. I have copied the core file, let me know if you need further information:

```
#0  HPHP::jit::FixupMap::fixupWork (ec=<optimized out>, nextRbp=0x0) at /tmp/buildd/hhvm-3.18.2+dfsg/hphp/runtime/vm/jit/fixup.cpp:175
#1  0x00000000013009ad in HPHP::jit::detail::syncVMRegsWork () at /tmp/buildd/hhvm-3.18.2+dfsg/hphp/runtime/vm/jit/fixup.cpp:240
#2  0x000000000217fb8c in HPHP::createBacktrace (btArgs=...) at /tmp/buildd/hhvm-3.18.2+dfsg/hphp/runtime/base/backtrace.cpp:168
#3  0x0000000001b501f8 in HPHP::debug_string_backtrace (skip=skip@entry=false, ignore_args=ignore_args@entry=true, limit=limit@entry=0)
    at /tmp/buildd/hhvm-3.18.2+dfsg/hphp/runtime/ext/std/ext_std_errorfunc.cpp:117
#4  0x0000000000f3ded7 in HPHP::bt_handler (sig=11) at /tmp/buildd/hhvm-3.18.2+dfsg/hphp/runtime/base/crash-reporter.cpp:137
#5  <signal handler called>
#6  0x0000000002137b9a in HPHP::MemoryManager::FreeList::maybePop (this=0x7f0c037fbed0) at /tmp/buildd/hhvm-3.18.2+dfsg/hphp/runtime/base/memory-manager-inl.h:109
#7  HPHP::MemoryManager::mallocSmallSizeSlow (this=0x7f0c037fbd40, this@entry=<error reading variable: Asked for position 0 of stack, stack only has 0 elements on it.>,
    bytes=65552, index=44) at /tmp/buildd/hhvm-3.18.2+dfsg/hphp/runtime/base/memory-manager.cpp:858
#8  0x0000000000f79f05 in HPHP::MemoryManager::mallocSmallIndex (bytes=<optimized out>, index=<optimized out>, this=<optimized out>)
    at /tmp/buildd/hhvm-3.18.2+dfsg/hphp/runtime/base/memory-manager-inl.h:227
#9  HPHP::MemoryManager::mallocSmallSize (bytes=<optimized out>, this=<optimized out>) at /tmp/buildd/hhvm-3.18.2+dfsg/hphp/runtime/base/memory-manager-inl.h:238
#10 HPHP::req::allocate<false> (nbytes=<optimized out>, ty=0) at /tmp/buildd/hhvm-3.18.2+dfsg/hphp/runtime/base/memory-manager.cpp:952
#11 0x00007f0ca35af78b in deflateInit2_ (strm=0x7f0c037fa880, level=6, method=<optimized out>, windowBits=15, memLevel=9, strategy=0, version=0x21ff0ef "1.2.8",
    stream_size=112) at deflate.c:294
#12 0x0000000001a36f43 in HPHP::hhvm_zlib_encode (data=(HPHP::req::ptr<HPHP::StringData>) 0x30fce60 <HPHP::s_theEmptyString> "", level=<optimized out>,
    enc=<optimized out>) at /tmp/buildd/hhvm-3.18.2+dfsg/hphp/runtime/ext/zlib/ext_zlib.cpp:163
#13 0x0000000001a371e7 in HPHP::f_gzencode (data=..., level=<optimized out>, encoding_mode=<optimized out>)
    at /tmp/buildd/hhvm-3.18.2+dfsg/hphp/runtime/ext/zlib/ext_zlib.cpp:198
#14 0x00000000041cb025 in ?? ()
#15 0x00007f0c232ffe40 in ?? ()
#16 0x00000000041ca27f in ?? ()
#17 0x00007f0c232fff00 in ?? ()
#18 0x9c044d90fb32f500 in ?? ()
#19 0x0000000003a0004f in ?? ()
#20 0x9c044d90fb32f500 in ?? ()
#21 0x00007f0c037fa9c0 in ?? ()
#22 0x0000000001772a84 in HPHP::jit::enterTCImpl (start=<optimized out>, stashedAR=<optimized out>)
    at /tmp/buildd/hhvm-3.18.2+dfsg/hphp/runtime/vm/jit/unique-stubs.cpp:1421
#23 0x00000000041ca27f in ?? ()
#24 0x00007f0c81245200 in ?? ()
#25 0x0000000100000191 in ?? ()
#26 0x00007f0c70cf0f40 in ?? ()
#27 0x0000000000000000 in ?? ()
```

deflate.c:294 correlates to this memory allocation in zlib's deflateInit2_ function:
```
s->prev   = (Posf *)  ZALLOC(strm, s->w_size, sizeof(Pos));
```

**Comment by mmuehlenhoff** [comment]
This was very likely fallout of the bug fixed in https://github.com/facebook/hhvm/issues/7864
I'm closing this one, if we catch that error at Wikimedia again, I'll reopen.
