### ISSUE TITLE
SIGSEGV test/slow/u_converter/2136.php

### ISSUE THREAD

**Issue by lapetr** [facebook/hhvm#7970]
### HHVM Version
HipHop VM 3.21.0 (rel)
Compiler: tags/HHVM-3.21.0-0-gbdbaff80f67e02080f1ea377d30efee63f10126d
Repo schema: 1381c379b9e7d8cd9efa2ce49aeb6f699919dc3a
(only without hhvm-dbg version)

OR

master-19ab70e2d0148ca7efbb05bf022d28bd85249920 
(only without -DCMAKE_BUILD_TYPE=Debug)

### Standalone code, or other way to reproduce the problem
```php
<?php // test/slow/u_converter/2136.php (modified)
class MyConverter extends UConverter {
/*  public function toUCallback($reason, $source, $codeUnits, &$error) {
    $error = U_ZERO_ERROR;
    switch ($codeUnits) {
      case "\x80": return NULL;
      case "\x81": return 'a';
      case "\x82": return ord('b');
      case "\x83": return array('c');
    }
  }
  public function fromUCallback($reason, $source, $codePoint, &$error) {
    $error = U_ZERO_ERROR;
    switch ($codePoint) {
      case 0x00F1: return "A";
      case 0x00F2: return ord("B");
      case 0x00F3: return array("C");
      case 0x00F4: return NULL;
    }
  }*/
}
/*
$c = new MyConverter('ascii', 'utf-8'); //  SIGSEGV on the end
var_dump($c->convert("\x80\x81\x82\x83"));
var_dump($c->convert("\xC3\xB1\xC3\xB2\xC3\xB3\xC3\xB4"));
*/
//$d = new UConverter(); //OK
$e = new MyConverter(); //  SIGSEGV on the end
echo "TEST END";  // prints "TEST END",  SIGSEGV
//sleep(5); // prints "TEST END", sleeps 5sec ,  SIGSEGV
```
### steps to reproduce:

* ` sudo aptitude install hhvm `
* `hhvm  --no-config 2136.php`
*  output:
    *  `TEST END`
    *  `SIGSEGV  (core dumped...)`

* `hhvm  --no-config  -v Eval.Jit=0   2136.php`
    *  OK 

 ```
hvm --version
HipHop VM 3.21.0 (rel)
Compiler: tags/HHVM-3.21.0-0-gbdbaff80f67e02080f1ea377d30efee63f10126d
Repo schema: 1381c379b9e7d8cd9efa2ce49aeb6f699919dc3a
```
---

* `sudo aptitude install hhvm-dbg`
* `hhvm  --no-config 2136.php `  (or `hhvm  --no-config  -v Eval.Jit=1   2136.php` )
    * OK
```
hhvm --version
HipHop VM 3.21.0 (dbg)
Compiler: tags/HHVM-3.21.0-0-gbdbaff80f67e02080f1ea377d30efee63f10126d
Repo schema: 1381c379b9e7d8cd9efa2ce49aeb6f699919dc3a
```
---

* i can repeat this steps with same results
* I got the same results when I compiled the source code (master-19ab70e2d0148ca7efbb05bf022d28bd85249920) with and without -DCMAKE_BUILD_TYPE=Debug

---

backtrace :
```
Starting program: /usr/bin/hhvm -vEval.SyncGdbChunks=1 -vEval.JitNoGdb=false --no-config /tmp/lxc/u_converter/2136.php
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Possible bad config node: Eval.SyncGdbChunks
TEST END
Program received signal SIGSEGV, Segmentation fault.
0x000000000229e820 in HPHP::jit::detail::syncVMRegsWork() ()
(gdb) bt
#0  0x000000000229e820 in HPHP::jit::detail::syncVMRegsWork() ()
#1  0x00000000010f9c59 in HPHP::ExecutionContext::invokeFuncFew(HPHP::Func const*, void*, HPHP::StringData*, int, HPHP::TypedValue const*, bool) ()
#2  0x0000000003617ae9 in HPHP::ObjectData::o_invoke_few_args(HPHP::String const&, int, HPHP::Variant const&, HPHP::Variant const&, HPHP::Variant const&, HPHP::Variant const&, HPHP::Variant const&, HPHP::Variant const&) ()
#3  0x000000000299a9c6 in HPHP::Intl::ucnvToUCallback(HPHP::ObjectData*, UConverterToUnicodeArgs*, char const*, int, UConverterCallbackReason, UErrorCode*) ()
#4  0x00007ffff6b10fb1 in ucnv_close_55 (converter=0x7fffe05f1100) at /build/icu-iXEUIQ/icu-55.1/source/common/ucnv.c:362
#5  0x00000000084001b9 in ?? ()
#6  0x000000000480004f in ?? ()
#7  0x0000000000000000 in ?? ()
(gdb) continue
Continuing.

Program received signal SIGSEGV, Segmentation fault.
0x000000000229e820 in HPHP::jit::detail::syncVMRegsWork() ()
(gdb) bt
#0  0x000000000229e820 in HPHP::jit::detail::syncVMRegsWork() ()
#1  0x000000000110acc2 in void HPHP::walkStack<HPHP::createCompactBacktrace()::{lambda(HPHP::ActRec*, int)#1}>(HPHP::createCompactBacktrace()::{lambda(HPHP::ActRec*, int)#1}) ()
#2  0x0000000003626657 in HPHP::createBacktrace(HPHP::BacktraceArgs const&) ()
#3  0x0000000002652d48 in HPHP::debug_string_backtrace(bool, bool, long) ()
#4  0x000000000119ac47 in HPHP::bt_handler(int) ()
#5  <signal handler called>
#6  0x000000000229e820 in HPHP::jit::detail::syncVMRegsWork() ()
#7  0x00000000010f9c59 in HPHP::ExecutionContext::invokeFuncFew(HPHP::Func const*, void*, HPHP::StringData*, int, HPHP::TypedValue const*, bool) ()
#8  0x0000000003617ae9 in HPHP::ObjectData::o_invoke_few_args(HPHP::String const&, int, HPHP::Variant const&, HPHP::Variant const&, HPHP::Variant const&, HPHP::Variant const&, HPHP::Variant const&, HPHP::Variant const&) ()
#9  0x000000000299a9c6 in HPHP::Intl::ucnvToUCallback(HPHP::ObjectData*, UConverterToUnicodeArgs*, char const*, int, UConverterCallbackReason, UErrorCode*) ()
#10 0x00007ffff6b10fb1 in ucnv_close_55 (converter=0x7fffe05f1100) at /build/icu-iXEUIQ/icu-55.1/source/common/ucnv.c:362
#11 0x00000000084001b9 in ?? ()
#12 0x000000000480004f in ?? ()
#13 0x0000000000000000 in ?? ()
```

[cpuinfo.txt](https://github.com/facebook/hhvm/files/1250553/cpuinfo.txt)
[hphp.zip](https://github.com/facebook/hhvm/files/1250563/hphp.zip)

**Comment by lapetr** [comment]
possibly related to: https://github.com/facebook/hhvm/pull/7767#issuecomment-292282705
