### ISSUE TITLE
segfault on include/require with registered user 'file' stream wrapper

### ISSUE THREAD

**Issue by pprasse** [facebook/hhvm#8089]
### HHVM Version
tested in 3.22.0, still in master
at least since 3.2.0

### Operating System and Version
Ubuntu 16.04 (probably all operating systems)

### Analysis

In https://github.com/facebook/hhvm/blob/HHVM-3.22/hphp/runtime/base/unit-cache.cpp#L493 we get the stream wrapper and execute stat on it.
If stat fails, we continue to use the stream wrapper we got before stat. This gets problematic if the stream wrapper is messed with (unregistered, restored, registered) in the stat call.

### Standalone code, or other way to reproduce the problem
[segfault-user-stream-wrapper.zip](https://github.com/facebook/hhvm/files/1607876/segfault-user-stream-wrapper.zip)
```
unzip segfault-user-stream-wrapper.zip
hhvm main.php
```
### Actual result

```
START FileIsolationStreamWrapper::url_stat array (
  0 => '/home/patrickprasse/sandboxes/polymer/actindo3/_ERP-1130/Autoload1.php',
  1 => 2,
)
strlen($_text)=8388608
END FileIsolationStreamWrapper::url_stat array (
  0 => 87,
  1 => 1073273987,
  2 => 33188,
  3 => 1,
  4 => 10010,
  5 => 10010,
  6 => 0,
  7 => 45,
  8 => 1515162286,
  9 => 1515162287,
  10 => 1515162287,
  11 => 1048576,
  12 => 8,
  'dev' => 87,
  'ino' => 1073273987,
  'mode' => 33188,
  'nlink' => 1,
  'uid' => 10010,
  'gid' => 10010,
  'rdev' => 0,
  'size' => 45,
  'atime' => 1515162286,
  'mtime' => 1515162287,
  'ctime' => 1515162287,
  'blksize' => 1048576,
  'blocks' => 8,
)

START FileIsolationStreamWrapper::url_stat array (
  0 => '/home/patrickprasse/sandboxes/polymer/actindo3/_ERP-1130/Autoload2.php',
  1 => 2,
)
strlen($_text)=16777216
END FileIsolationStreamWrapper::url_stat array (
  0 => 87,
  1 => 1073272912,
  2 => 33188,
  3 => 1,
  4 => 10010,
  5 => 10010,
  6 => 0,
  7 => 45,
  8 => 1515162285,
  9 => 1515162285,
  10 => 1515162285,
  11 => 1048576,
  12 => 8,
  'dev' => 87,
  'ino' => 1073272912,
  'mode' => 33188,
  'nlink' => 1,
  'uid' => 10010,
  'gid' => 10010,
  'rdev' => 0,
  'size' => 45,
  'atime' => 1515162285,
  'mtime' => 1515162285,
  'ctime' => 1515162285,
  'blksize' => 1048576,
  'blocks' => 8,
)

START FileIsolationStreamWrapper::url_stat array (
  0 => '/home/patrickprasse/sandboxes/polymer/actindo3/_ERP-1130/Autoload3.php',
  1 => 2,
)
strlen($_text)=25165824
END FileIsolationStreamWrapper::url_stat array (
  0 => 87,
  1 => 1073273418,
  2 => 33188,
  3 => 1,
  4 => 10010,
  5 => 10010,
  6 => 0,
  7 => 45,
  8 => 1515162285,
  9 => 1515162286,
  10 => 1515162286,
  11 => 1048576,
  12 => 8,
  'dev' => 87,
  'ino' => 1073273418,
  'mode' => 33188,
  'nlink' => 1,
  'uid' => 10010,
  'gid' => 10010,
  'rdev' => 0,
  'size' => 45,
  'atime' => 1515162285,
  'mtime' => 1515162286,
  'ctime' => 1515162286,
  'blksize' => 1048576,
  'blocks' => 8,
)

START FileIsolationStreamWrapper::url_stat array (
  0 => '/home/patrickprasse/sandboxes/polymer/actindo3/_ERP-1130/Autoload4.php',
  1 => 2,
)
strlen($_text)=33554432
END FileIsolationStreamWrapper::url_stat array (
  0 => 87,
  1 => 1073274467,
  2 => 33188,
  3 => 1,
  4 => 10010,
  5 => 10010,
  6 => 0,
  7 => 115,
  8 => 1515162287,
  9 => 1515162287,
  10 => 1515162287,
  11 => 1048576,
  12 => 8,
  'dev' => 87,
  'ino' => 1073274467,
  'mode' => 33188,
  'nlink' => 1,
  'uid' => 10010,
  'gid' => 10010,
  'rdev' => 0,
  'size' => 115,
  'atime' => 1515162287,
  'mtime' => 1515162287,
  'ctime' => 1515162287,
  'blksize' => 1048576,
  'blocks' => 8,
)

START FileIsolationStreamWrapper::url_stat array (
  0 => '/home/patrickprasse/sandboxes/polymer/actindo3/_ERP-1130/thisFileDoesNotExist.php',
  1 => 2,
)
strlen($_text)=41943040
END FileIsolationStreamWrapper::url_stat false
Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.20914.log
Segmentation fault (core dumped)
patrickprasse@f6b57a25f004:~/sandboxes/polymer/actindo3/_ERP-1130$ hhvm main.php 

START FileIsolationStreamWrapper::url_stat array (
  0 => '/home/patrickprasse/sandboxes/polymer/actindo3/_ERP-1130/Autoload1.php',
  1 => 2,
)
strlen($_text)=8388608
END FileIsolationStreamWrapper::url_stat array (
  0 => 87,
  1 => 1073273987,
  2 => 33188,
  3 => 1,
  4 => 10010,
  5 => 10010,
  6 => 0,
  7 => 45,
  8 => 1515162286,
  9 => 1515162287,
  10 => 1515162287,
  11 => 1048576,
  12 => 8,
  'dev' => 87,
  'ino' => 1073273987,
  'mode' => 33188,
  'nlink' => 1,
  'uid' => 10010,
  'gid' => 10010,
  'rdev' => 0,
  'size' => 45,
  'atime' => 1515162286,
  'mtime' => 1515162287,
  'ctime' => 1515162287,
  'blksize' => 1048576,
  'blocks' => 8,
)


START FileIsolationStreamWrapper::url_stat array (
  0 => '/home/patrickprasse/sandboxes/polymer/actindo3/_ERP-1130/Autoload2.php',
  1 => 2,
)
strlen($_text)=16777216
END FileIsolationStreamWrapper::url_stat array (
  0 => 87,
  1 => 1073272912,
  2 => 33188,
  3 => 1,
  4 => 10010,
  5 => 10010,
  6 => 0,
  7 => 45,
  8 => 1515162285,
  9 => 1515162285,
  10 => 1515162285,
  11 => 1048576,
  12 => 8,
  'dev' => 87,
  'ino' => 1073272912,
  'mode' => 33188,
  'nlink' => 1,
  'uid' => 10010,
  'gid' => 10010,
  'rdev' => 0,
  'size' => 45,
  'atime' => 1515162285,
  'mtime' => 1515162285,
  'ctime' => 1515162285,
  'blksize' => 1048576,
  'blocks' => 8,
)


START FileIsolationStreamWrapper::url_stat array (
  0 => '/home/patrickprasse/sandboxes/polymer/actindo3/_ERP-1130/Autoload3.php',
  1 => 2,
)
strlen($_text)=25165824
END FileIsolationStreamWrapper::url_stat array (
  0 => 87,
  1 => 1073273418,
  2 => 33188,
  3 => 1,
  4 => 10010,
  5 => 10010,
  6 => 0,
  7 => 45,
  8 => 1515162285,
  9 => 1515162286,
  10 => 1515162286,
  11 => 1048576,
  12 => 8,
  'dev' => 87,
  'ino' => 1073273418,
  'mode' => 33188,
  'nlink' => 1,
  'uid' => 10010,
  'gid' => 10010,
  'rdev' => 0,
  'size' => 45,
  'atime' => 1515162285,
  'mtime' => 1515162286,
  'ctime' => 1515162286,
  'blksize' => 1048576,
  'blocks' => 8,
)


START FileIsolationStreamWrapper::url_stat array (
  0 => '/home/patrickprasse/sandboxes/polymer/actindo3/_ERP-1130/Autoload4.php',
  1 => 2,
)
strlen($_text)=33554432
END FileIsolationStreamWrapper::url_stat array (
  0 => 87,
  1 => 1073274467,
  2 => 33188,
  3 => 1,
  4 => 10010,
  5 => 10010,
  6 => 0,
  7 => 115,
  8 => 1515162287,
  9 => 1515162287,
  10 => 1515162287,
  11 => 1048576,
  12 => 8,
  'dev' => 87,
  'ino' => 1073274467,
  'mode' => 33188,
  'nlink' => 1,
  'uid' => 10010,
  'gid' => 10010,
  'rdev' => 0,
  'size' => 115,
  'atime' => 1515162287,
  'mtime' => 1515162287,
  'ctime' => 1515162287,
  'blksize' => 1048576,
  'blocks' => 8,
)


START FileIsolationStreamWrapper::url_stat array (
  0 => '/home/patrickprasse/sandboxes/polymer/actindo3/_ERP-1130/thisFileDoesNotExist.php',
  1 => 2,
)
strlen($_text)=41943040
END FileIsolationStreamWrapper::url_stat false

Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.20915.log
Segmentation fault (core dumped)
```

/tmp/stacktrace.20915.log:
```Host: f6b57a25f004
ProcessID: 20915
ThreadID: 140481358427072
ThreadPID: 20915
Name: /usr/bin/hhvm
Type: Segmentation fault
Runtime: hhvm
Version: tags/HHVM-3.20.2-0-gad133f299ece0e45db8536473a8ef77cc4612ae3
DebuggerCount: 0

Arguments: main.php
ThreadType: CLI

# 0  0000000003508796
# 1  0000000001167f92
# 2  00007fc45b54d3d0
# 3  00007fc4553e4f93
# 4  00000000034bf12d
# 5  00000000034beb4c
# 6  00000000034bb69e
# 7  000000000355e29c
# 8  00000000010caea8
# 9  00000000034e0493
# 10 00000000034dfac4
# 11 00000000034c2526
# 12 000000000354f5de
# 13 00000000010caea8
# 14 00000000034e0493
# 15 00000000034dfac4
# 16 00000000034c2526
# 17 000000000354f5de
# 18 00000000010caea8
# 19 00000000034e0493
# 20 00000000034dfac4
# 21 00000000034c2526
# 22 000000000354f5de
# 23 00000000010caea8
# 24 00000000034e0493
# 25 00000000034dfac4
# 26 0000000003481d1e
# 27 000000000354e230
# 28 00000000010caea8
# 29 00000000010cbba1
# 30 0000000003510348
# 31 0000000003510711
# 32 00000000013d575b
# 33 00000000013d5fcb
# 34 00000000013eae07
# 35 00000000013eca37
# 36 0000000000a10e7f
# 37 00007fc454a91830
# 38 0000000000a0c0d9

PHP Stacktrace:

#0  include() called at [/home/patrickprasse/sandboxes/polymer/actindo3/_ERP-1130/main.php:7]
#1  Closure$() called at [/home/patrickprasse/sandboxes/polymer/actindo3/_ERP-1130/Autoload3.php:3]
#2  include() called at [/home/patrickprasse/sandboxes/polymer/actindo3/_ERP-1130/main.php:7]
#3  Closure$() called at [/home/patrickprasse/sandboxes/polymer/actindo3/_ERP-1130/Autoload2.php:3]
#4  include() called at [/home/patrickprasse/sandboxes/polymer/actindo3/_ERP-1130/main.php:7]
#5  Closure$() called at [/home/patrickprasse/sandboxes/polymer/actindo3/_ERP-1130/Autoload1.php:3]
#6  include() called at [/home/patrickprasse/sandboxes/polymer/actindo3/_ERP-1130/main.php:7]
#7  Closure$() called at [/home/patrickprasse/sandboxes/polymer/actindo3/_ERP-1130/main.php:15]
```

gdb session
```
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /root/hhvm/hphp/hhvm/hhvm...done.
(gdb) r
Starting program: /root/hhvm/hphp/hhvm/hhvm main.php
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

START FileIsolationStreamWrapper::url_stat array (
  0 => '/home/sandboxes/full-source-access/polymer/actindo3/_ERP-1130/Autoload1.php',
  1 => 2,
)
strlen($_text)=8388608
END FileIsolationStreamWrapper::url_stat array (
  0 => 57,
  1 => 2182153740,
  2 => 33188,
  3 => 1,
  4 => 10010,
  5 => 10010,
  6 => 0,
  7 => 45,
  8 => 1515162286,
  9 => 1515162287,
  10 => 1515162287,
  11 => 1048576,
  12 => 8,
  'dev' => 57,
  'ino' => 2182153740,
  'mode' => 33188,
  'nlink' => 1,
  'uid' => 10010,
  'gid' => 10010,
  'rdev' => 0,
  'size' => 45,
  'atime' => 1515162286,
  'mtime' => 1515162287,
  'ctime' => 1515162287,
  'blksize' => 1048576,
  'blocks' => 8,
)


START FileIsolationStreamWrapper::url_stat array (
  0 => '/home/sandboxes/full-source-access/polymer/actindo3/_ERP-1130/Autoload2.php',
  1 => 2,
)
strlen($_text)=16777216
END FileIsolationStreamWrapper::url_stat array (
  0 => 57,
  1 => 2182157000,
  2 => 33188,
  3 => 1,
  4 => 10010,
  5 => 10010,
  6 => 0,
  7 => 45,
  8 => 1515162285,
  9 => 1515162285,
  10 => 1515162285,
  11 => 1048576,
  12 => 8,
  'dev' => 57,
  'ino' => 2182157000,
  'mode' => 33188,
  'nlink' => 1,
  'uid' => 10010,
  'gid' => 10010,
  'rdev' => 0,
  'size' => 45,
  'atime' => 1515162285,
  'mtime' => 1515162285,
  'ctime' => 1515162285,
  'blksize' => 1048576,
  'blocks' => 8,
)


START FileIsolationStreamWrapper::url_stat array (
  0 => '/home/sandboxes/full-source-access/polymer/actindo3/_ERP-1130/Autoload3.php',
  1 => 2,
)
strlen($_text)=25165824
END FileIsolationStreamWrapper::url_stat array (
  0 => 57,
  1 => 2182153726,
  2 => 33188,
  3 => 1,
  4 => 10010,
  5 => 10010,
  6 => 0,
  7 => 45,
  8 => 1515162285,
  9 => 1515162286,
  10 => 1515162286,
  11 => 1048576,
  12 => 8,
  'dev' => 57,
  'ino' => 2182153726,
  'mode' => 33188,
  'nlink' => 1,
  'uid' => 10010,
  'gid' => 10010,
  'rdev' => 0,
  'size' => 45,
  'atime' => 1515162285,
  'mtime' => 1515162286,
  'ctime' => 1515162286,
  'blksize' => 1048576,
  'blocks' => 8,
)


START FileIsolationStreamWrapper::url_stat array (
  0 => '/home/sandboxes/full-source-access/polymer/actindo3/_ERP-1130/Autoload4.php',
  1 => 2,
)
strlen($_text)=33554432
END FileIsolationStreamWrapper::url_stat array (
  0 => 57,
  1 => 2182153741,
  2 => 33188,
  3 => 1,
  4 => 10010,
  5 => 10010,
  6 => 0,
  7 => 115,
  8 => 1515162287,
  9 => 1515162287,
  10 => 1515162287,
  11 => 1048576,
  12 => 8,
  'dev' => 57,
  'ino' => 2182153741,
  'mode' => 33188,
  'nlink' => 1,
  'uid' => 10010,
  'gid' => 10010,
  'rdev' => 0,
  'size' => 115,
  'atime' => 1515162287,
  'mtime' => 1515162287,
  'ctime' => 1515162287,
  'blksize' => 1048576,
  'blocks' => 8,
)


START FileIsolationStreamWrapper::url_stat array (
  0 => '/home/sandboxes/full-source-access/polymer/actindo3/_ERP-1130/thisFileDoesNotExist.php',
  1 => 2,
)
strlen($_text)=41943040
END FileIsolationStreamWrapper::url_stat false


Program received signal SIGSEGV, Segmentation fault.
0x00007ffff0492f93 in __dynamic_cast () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff0492f93 in __dynamic_cast () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000000005c437e0 in HPHP::(anonymous namespace)::findFileWrapper (file=..., ctx=0x7fffffff8be0) at /root/hhvm/hphp/runtime/base/unit-cache.cpp:510
#2  0x0000000005977b77 in HPHP::resolve_include (file=..., currentDir=0x7fffe0e976c0 "/home/sandboxes/full-source-access/polymer/actindo3/_ERP-1130", 
    tryFile=0x5c4361b <HPHP::(anonymous namespace)::findFileWrapper(HPHP::String const&, void*)>, ctx=0x7fffffff8be0) at /root/hhvm/hphp/runtime/base/builtin-functions.cpp:1036
#3  0x0000000005c451ce in HPHP::resolveVmInclude (path=0x7fffe09cde80, currentDir=0x7fffe0e976c0 "/home/sandboxes/full-source-access/polymer/actindo3/_ERP-1130", s=0x7fffffff8cf0, allow_dir=false)
    at /root/hhvm/hphp/runtime/base/unit-cache.cpp:684
#4  0x0000000005c45340 in HPHP::lookupUnit (path=0x7fffe09cde80, currentDir=0x7fffe0e976c0 "/home/sandboxes/full-source-access/polymer/actindo3/_ERP-1130", initial_opt=0x7fffffff8f64)
    at /root/hhvm/hphp/runtime/base/unit-cache.cpp:708
#5  0x0000000006134377 in HPHP::<lambda()>::operator()(void) const (__closure=0x7fffffff8fe0) at /root/hhvm/hphp/runtime/vm/bytecode.cpp:5299
#6  0x000000000613467c in HPHP::inclOp (pc=@0x7fffffff9110: 0x7fffe0e97906 "\004\240\002\001", flags=HPHP::InclOpFlags::Default, opName=0x8eca6df "include")
    at /root/hhvm/hphp/runtime/vm/bytecode.cpp:5300
#7  0x0000000006134bdf in HPHP::iopIncl (pc=@0x7fffffff9110: 0x7fffe0e97906 "\004\240\002\001") at /root/hhvm/hphp/runtime/vm/bytecode.cpp:5322
#8  0x00000000061420c6 in HPHP::iopWrapper (fn=0x6134bbd <HPHP::iopIncl(unsigned char const*&)>, pc=@0x7fffffff9110: 0x7fffe0e97906 "\004\240\002\001")
    at /root/hhvm/hphp/runtime/vm/bytecode.cpp:6444
#9  0x00000000061d6b4e in HPHP::dispatchImpl<false> () at /root/hhvm/hphp/runtime/vm/bytecode.cpp:7229
#10 0x000000000619fdb3 in HPHP::dispatch () at /root/hhvm/hphp/runtime/vm/bytecode.cpp:7248
#11 0x00000000060fd2ef in HPHP::enterVMAtFunc (enterFnAr=0x7fffe0f3fdc0, stk=HPHP::StackArgsState::Trimmed, varEnv=0x0) at /root/hhvm/hphp/runtime/vm/bytecode.cpp:1574
#12 0x000000000593a4a7 in HPHP::ExecutionContext::<lambda(HPHP::ActRec*)>::<lambda()>::operator()(void) const (__closure=0x7fffffff92d0) at /root/hhvm/hphp/runtime/base/execution-context.cpp:1694
#13 0x0000000005946f37 in HPHP::exception_handler<HPHP::ExecutionContext::invokeFunc(const HPHP::Func*, const HPHP::Variant&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags, bool)::<lambda(HPHP::ActRec*)>::<lambda()> >(HPHP::ExecutionContext::<lambda(HPHP::ActRec*)>::<lambda()>) (action=...) at /root/hhvm/hphp/runtime/vm/unwind-inl.h:30
#14 0x0000000005942043 in HPHP::<lambda()>::operator()(void) const (__closure=0x7fffffff93f0) at /root/hhvm/hphp/runtime/base/execution-context.cpp:1624
#15 0x000000000594795f in HPHP::enterVMCustomHandler<HPHP::enterVM(HPHP::ActRec*, Action) [with Action = HPHP::ExecutionContext::invokeFunc(const HPHP::Func*, const HPHP::Variant&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags, bool)::<lambda(HPHP::ActRec*)>::<lambda()>]::<lambda()> >(HPHP::ActRec *, HPHP::<lambda()>) (
    ar=0x7fffe0f3fdc0, action=...) at /root/hhvm/hphp/runtime/base/execution-context.cpp:1615
#16 0x0000000005942079 in HPHP::enterVM<HPHP::ExecutionContext::invokeFunc(const HPHP::Func*, const HPHP::Variant&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags, bool)::<lambda(HPHP::ActRec*)>::<lambda()> >(HPHP::ActRec *, HPHP::ExecutionContext::<lambda(HPHP::ActRec*)>::<lambda()>) (ar=0x7fffe0f3fdc0, action=...)
    at /root/hhvm/hphp/runtime/base/execution-context.cpp:1624
#17 0x000000000593a4e3 in HPHP::ExecutionContext::<lambda(HPHP::ActRec*)>::operator()(HPHP::ActRec *) const (__closure=0x7fffffff9510, ar=0x7fffe0f3fdc0)
    at /root/hhvm/hphp/runtime/base/execution-context.cpp:1695
#18 0x000000000593ad10 in HPHP::ExecutionContext::invokeFuncImpl<HPHP::ExecutionContext::invokeFunc(const HPHP::Func*, const HPHP::Variant&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags, bool)::<lambda(HPHP::TypedValue&)>, HPHP::ExecutionContext::invokeFunc(const HPHP::Func*, const HPHP::Variant&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags, bool)::<lambda(HPHP::ActRec*, HPHP::TypedValue&)>, HPHP::ExecutionContext::invokeFunc(const HPHP::Func*, const HPHP::Variant&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags, bool)::<lambda(HPHP::ActRec*)> > (doEnterVM=..., doInitArgs=..., doStackCheck=..., 
    useWeakTypes=false, invName=0x0, argc=1, cls=0x0, thiz=0x7fffe7199120, f=0x7fffe09cbe80, this=0x7fffe718f020) at /root/hhvm/hphp/runtime/base/execution-context.cpp:1586
#19 HPHP::ExecutionContext::invokeFunc (this=0x7fffe718f020, f=0x7fffe09cbe80, args_=..., thiz=0x7fffe7199120, cls=0x0, varEnv=0x0, invName=0x0, flags=HPHP::ExecutionContext::InvokeCuf, 
    useWeakTypes=false) at /root/hhvm/hphp/runtime/base/execution-context.cpp:1699
#20 0x0000000005881e60 in HPHP::(anonymous namespace)::vm_call_user_func_cufiter (cufIter=..., params=...) at /root/hhvm/hphp/runtime/base/autoload-handler.cpp:88
#21 0x0000000005884223 in HPHP::AutoloadHandler::autoloadClassPHP5Impl (this=0x7fffe0e6dfc0, className=..., forceSplStack=false) at /root/hhvm/hphp/runtime/base/autoload-handler.cpp:423
#22 0x0000000005883314 in HPHP::AutoloadHandler::autoloadClass (this=0x7fffe0e6dfc0, clsName=..., forceSplStack=false) at /root/hhvm/hphp/runtime/base/autoload-handler.cpp:384
#23 0x000000000600256b in HPHP::Unit::loadMissingClass (ne=0x7fffe61f5690, name=0x7fffe09ceca0) at /root/hhvm/hphp/runtime/vm/unit.cpp:948
#24 0x000000000600262c in HPHP::Unit::getClass (ne=0x7fffe61f5690, name=0x7fffe09ceca0, tryAutoload=true) at /root/hhvm/hphp/runtime/vm/unit.cpp:957
#25 0x0000000005c5f901 in HPHP::Unit::getClass (name=0x7fffe09ceca0, tryAutoload=true) at /root/hhvm/hphp/runtime/vm/unit-inl.h:327
#26 0x0000000006001e06 in HPHP::Unit::defClass (preClass=0x7fffe0e91200, failIsFatal=true) at /root/hhvm/hphp/runtime/vm/unit.cpp:835
#27 0x0000000006135575 in HPHP::iopDefCls (cid=...) at /root/hhvm/hphp/runtime/vm/bytecode.cpp:5403
#28 0x0000000006142ad7 in HPHP::iopWrapper (fn=0x6135528 <HPHP::iopDefCls(HPHP::intva_t)>, pc=@0x7fffffff9ed0: 0x7fffe11f2dd2 "\027\001") at /root/hhvm/hphp/runtime/vm/bytecode.cpp:6507
#29 0x00000000061d7f52 in HPHP::dispatchImpl<false> () at /root/hhvm/hphp/runtime/vm/bytecode.cpp:7229
#30 0x000000000619fdb3 in HPHP::dispatch () at /root/hhvm/hphp/runtime/vm/bytecode.cpp:7248
#31 0x00000000060fd2ef in HPHP::enterVMAtFunc (enterFnAr=0x7fffe0f3fe50, stk=HPHP::StackArgsState::Trimmed, varEnv=0x0) at /root/hhvm/hphp/runtime/vm/bytecode.cpp:1574
---Type <return> to continue, or q <return> to quit---q
Quit
(gdb) frame 1
#1  0x0000000005c437e0 in HPHP::(anonymous namespace)::findFileWrapper (file=..., ctx=0x7fffffff8be0) at /root/hhvm/hphp/runtime/base/unit-cache.cpp:510
510	    dynamic_cast<FileStreamWrapper*>(w) ||
(gdb) l
505	
506	  if (!w) return false;
507	
508	  auto passW =
509	    RuntimeOption::RepoAuthoritative ||
510	    dynamic_cast<FileStreamWrapper*>(w) ||
511	    !w->isNormalFileStream()
512	      ? nullptr
513	      : w;
514	
(gdb) l 500
495	    if (w->stat(file, context->s) == 0) {
496	      context->path = file;
497	      return true;
498	    }
499	  }
500	
501	  // handle file://
502	  if (StringUtil::IsFileUrl(file)) {
503	    return findFileWrapper(file.substr(7), ctx);
504	  }
(gdb) break 495
Breakpoint 1 at 0x5c436de: file /root/hhvm/hphp/runtime/base/unit-cache.cpp, line 495.
(gdb) run
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /root/hhvm/hphp/hhvm/hhvm main.php
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, HPHP::(anonymous namespace)::findFileWrapper (file=..., ctx=0x7fffffffb520) at /root/hhvm/hphp/runtime/base/unit-cache.cpp:495
495	    if (w->stat(file, context->s) == 0) {
(gdb) c
Continuing.

START FileIsolationStreamWrapper::url_stat array (
  0 => '/home/sandboxes/full-source-access/polymer/actindo3/_ERP-1130/Autoload1.php',
  1 => 2,
)
strlen($_text)=8388608
END FileIsolationStreamWrapper::url_stat array (
  0 => 57,
  1 => 2182153740,
  2 => 33188,
  3 => 1,
  4 => 10010,
  5 => 10010,
  6 => 0,
  7 => 45,
  8 => 1515162286,
  9 => 1515162287,
  10 => 1515162287,
  11 => 1048576,
  12 => 8,
  'dev' => 57,
  'ino' => 2182153740,
  'mode' => 33188,
  'nlink' => 1,
  'uid' => 10010,
  'gid' => 10010,
  'rdev' => 0,
  'size' => 45,
  'atime' => 1515162286,
  'mtime' => 1515162287,
  'ctime' => 1515162287,
  'blksize' => 1048576,
  'blocks' => 8,
)


Breakpoint 1, HPHP::(anonymous namespace)::findFileWrapper (file=..., ctx=0x7fffffffa760) at /root/hhvm/hphp/runtime/base/unit-cache.cpp:495
495	    if (w->stat(file, context->s) == 0) {
(gdb) c
Continuing.

START FileIsolationStreamWrapper::url_stat array (
  0 => '/home/sandboxes/full-source-access/polymer/actindo3/_ERP-1130/Autoload2.php',
  1 => 2,
)
strlen($_text)=16777216
END FileIsolationStreamWrapper::url_stat array (
  0 => 57,
  1 => 2182157000,
  2 => 33188,
  3 => 1,
  4 => 10010,
  5 => 10010,
  6 => 0,
  7 => 45,
  8 => 1515162285,
  9 => 1515162285,
  10 => 1515162285,
  11 => 1048576,
  12 => 8,
  'dev' => 57,
  'ino' => 2182157000,
  'mode' => 33188,
  'nlink' => 1,
  'uid' => 10010,
  'gid' => 10010,
  'rdev' => 0,
  'size' => 45,
  'atime' => 1515162285,
  'mtime' => 1515162285,
  'ctime' => 1515162285,
  'blksize' => 1048576,
  'blocks' => 8,
)


Breakpoint 1, HPHP::(anonymous namespace)::findFileWrapper (file=..., ctx=0x7fffffff99a0) at /root/hhvm/hphp/runtime/base/unit-cache.cpp:495
495	    if (w->stat(file, context->s) == 0) {
(gdb) c
Continuing.

START FileIsolationStreamWrapper::url_stat array (
  0 => '/home/sandboxes/full-source-access/polymer/actindo3/_ERP-1130/Autoload3.php',
  1 => 2,
)
strlen($_text)=25165824
END FileIsolationStreamWrapper::url_stat array (
  0 => 57,
  1 => 2182153726,
  2 => 33188,
  3 => 1,
  4 => 10010,
  5 => 10010,
  6 => 0,
  7 => 45,
  8 => 1515162285,
  9 => 1515162286,
  10 => 1515162286,
  11 => 1048576,
  12 => 8,
  'dev' => 57,
  'ino' => 2182153726,
  'mode' => 33188,
  'nlink' => 1,
  'uid' => 10010,
  'gid' => 10010,
  'rdev' => 0,
  'size' => 45,
  'atime' => 1515162285,
  'mtime' => 1515162286,
  'ctime' => 1515162286,
  'blksize' => 1048576,
  'blocks' => 8,
)


Breakpoint 1, HPHP::(anonymous namespace)::findFileWrapper (file=..., ctx=0x7fffffff8be0) at /root/hhvm/hphp/runtime/base/unit-cache.cpp:495
495	    if (w->stat(file, context->s) == 0) {
(gdb) c
Continuing.

START FileIsolationStreamWrapper::url_stat array (
  0 => '/home/sandboxes/full-source-access/polymer/actindo3/_ERP-1130/Autoload4.php',
  1 => 2,
)
strlen($_text)=33554432
END FileIsolationStreamWrapper::url_stat array (
  0 => 57,
  1 => 2182153741,
  2 => 33188,
  3 => 1,
  4 => 10010,
  5 => 10010,
  6 => 0,
  7 => 115,
  8 => 1515162287,
  9 => 1515162287,
  10 => 1515162287,
  11 => 1048576,
  12 => 8,
  'dev' => 57,
  'ino' => 2182153741,
  'mode' => 33188,
  'nlink' => 1,
  'uid' => 10010,
  'gid' => 10010,
  'rdev' => 0,
  'size' => 115,
  'atime' => 1515162287,
  'mtime' => 1515162287,
  'ctime' => 1515162287,
  'blksize' => 1048576,
  'blocks' => 8,
)


Breakpoint 1, HPHP::(anonymous namespace)::findFileWrapper (file=..., ctx=0x7fffffff8be0) at /root/hhvm/hphp/runtime/base/unit-cache.cpp:495
495	    if (w->stat(file, context->s) == 0) {
(gdb) p w
$1 = (HPHP::Stream::Wrapper *) 0x7fffe7199090
```

**So, this is our valid stream wrapper before stat**
```
(gdb) p *w
$2 = {_vptr.Wrapper = 0x8da4890 <vtable for HPHP::UserStreamWrapper+16>, m_isLocal = true}
(gdb) b 500
Breakpoint 2 at 0x5c43739: file /root/hhvm/hphp/runtime/base/unit-cache.cpp, line 500.
(gdb) c
Continuing.

START FileIsolationStreamWrapper::url_stat array (
  0 => '/home/sandboxes/full-source-access/polymer/actindo3/_ERP-1130/thisFileDoesNotExist.php',
  1 => 2,
)
strlen($_text)=41943040
END FileIsolationStreamWrapper::url_stat false


Breakpoint 2, HPHP::(anonymous namespace)::findFileWrapper (file=..., ctx=0x7fffffff8be0) at /root/hhvm/hphp/runtime/base/unit-cache.cpp:502
502	  if (StringUtil::IsFileUrl(file)) {
```

**Stream wrapper is now invalid after the stat call:**
```
(gdb) p *w
$3 = {_vptr.Wrapper = 0x8, m_isLocal = 52}

(gdb) c
Continuing.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff0492f93 in __dynamic_cast () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
```

### Expected result

No segmentation fault

**Comment by fredemmott** [comment]
Are you able to reproduce this on 3.23 and/or nightly builds? 3.22 is unsupported.

**Comment by pprasse** [comment]
@fredemmott 
Yes, even in master, see paragraph HHVM Version in the initial report.
Just used HHVM-3.22.0 as I had a debug build handy.
Will submit a pull request sometime next Monday or Tuesday

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Support for user defined stream wrappers has been removed in hhvm [4.2.0](https://hhvm.com/blog/2019/04/23/hhvm-4.2.0.html).
