### ISSUE TITLE
Unknown or bad timezone ()

### ISSUE THREAD

**Issue by asim-vax** [facebook/hhvm#8337]
Believed to be fixed in 3.26.0 - #7270 , however still seeing the issue on magento application
### HHVM Version
HipHop VM 3.28.3 (rel)

### Operating System and Version
ubuntu 18.04.01 LTS

cat 236938917403 
a:5:{i:0;s:55:"DateTimeZone::__construct(): Unknown or bad timezone ()";i:1;s:2366:"#0 /[path]/app/code/local/Mage/Core/Model/Session/Abstract/Varien.php(135): DateTime->__wakeup()
#1 /[path]/app/code/local/Mage/Core/Model/Session/Abstract/Varien.php(227): Mage_Core_Model_Session_Abstract_Varien->start()
#2 /[path]/app/code/core/Mage/Core/Model/Session/Abstract.php(84): Mage_Core_Model_Session_Abstract_Varien->init()
#3 /[path]/app/code/community/Nexcessnet/Turpentine/Model/Core/Session.php(26): Mage_Core_Model_Session_Abstract->init()
#4 /[path]/app/code/core/Mage/Core/Model/Config.php(1357): Nexcessnet_Turpentine_Model_Core_Session->__construct()
#5 /[path]/app/Mage.php(474): Mage_Core_Model_Config->getModelInstance()
#6 /[path]/app/Mage.php(488): Mage::getModel()
#7 /[path]/app/code/core/Mage/Core/Controller/Varien/Action.php(493): Mage::getSingleton()
#8 /[path]/app/code/core/Mage/Core/Controller/Front/Action.php(69): Mage_Core_Controller_Varien_Action->preDispatch()
#9 /[path]/app/code/core/Mage/Core/Controller/Varien/Action.php(407): Mage_Core_Controller_Front_Action->preDispatch()
#10 /[path]/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch()
#11 /[path]/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match()
#12 /[path]/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#13 /[path]/app/Mage.php(695): Mage_Core_Model_App->run()
#14 /[path]/index.php(113): Mage::run()

### Actual result
page crashes. magento report generated 

### Expected result
No error thrown, page displayed

**Comment by fredemmott** [comment]
Do you have an isolated example, ideally PHP core that creates a DateTimeZone that can not be serialized-then-unserialized, or second best, the actual serialized time zone?

In general, we're not going to be able to investigate a report that requires installing and configuring a framework/cms/website.
