### ISSUE TITLE
Odd behavior between `TypeAssert\matches_type_structure` and `as` when arrays are involved.

### ISSUE THREAD

**Issue by mwildehahn** [facebook/hhvm#8343]
### HHVM Version

> Please include the output of `hhvm --version` and `hh_client --version`

```
➜ hhvm --version
HipHop VM 3.28.3
```

```
➜ hh_client --version
hh-5ab7f21d741bcf95e6ed049dac3576ab9f779c64-3.28.3 Tue Oct  2 20:15:11 2018
```

### Operating System and Version

> For example, 'Debian Squeeze', 'Ubuntu 16.04', 'MacOS High Sierra'. Please
> also mention if you are using Docker or similar images.

MacOS HIgh Seirra

### Standalone code, or other way to reproduce the problem

> This should not depend on installing any libraries or frameworks. Ideally, it
> should be possible to copy-paste this into a single file and reproduce the
> problem by running `hhvm` and/or `hh_client`

https://github.com/mwildehahn/repro-as-bug

Requires the `TypeAssert` library

### Actual result

> If applicable, please copy-paste output from `hhvm` or `hh_client`

```
Fatal error: Uncaught exception 'TypeAssertionException' with message 'Expected shape('type' => Types, ...), got array' in /Users/mh/work/repro-as-bug/main.php:40
Stack trace:
#0 /Users/mh/work/repro-as-bug/main.php(25): validate_one()
#1 /Users/mh/work/repro-as-bug/main.php(54): main()
#2 {main}
```

### Expected result

Would expect this to cast properly to the underlying type.

**Comment by fredemmott** [comment]
@kmeht : I"m working around this in the library, but is this an intentional exception to "darrays should just appear to be aliases for PHP arrays" ?

Minimal repo:

```
hphpd> = [] as shape()
```

**Comment by kmeht** [comment]
@fredemmott This is unintentional; will look into it.

**Comment by fredemmott** [comment]
FB: D10417664
