### ISSUE TITLE
HHVM 3.30 does not work on systems that report having exactly 1 CPU

### ISSUE THREAD

**Issue by juamedgod** [facebook/hhvm#8414]
### HHVM Version
```
root@4df3c4e4ff4b:/# hhvm --version
HipHop VM 3.30.1 (rel)
Compiler: 1545157756_373434727
Repo schema: 31408a98c34b09c1971e7a6826db52874430bb5c
root@4df3c4e4ff4b:/# hh_client --version
hh-c15d5f902880f7478651a85a635cf21d449d0b44-3.30.1 Tue Dec 18 18:31:42 2018

root@ip-192-168-30-135:/home/sample# uname -a
Linux ip-192-168-30-135 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
root@ip-192-168-30-135:/home/sample# cat /etc/*release*
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### Operating System and Version

Debian 9, but most likely other distros running newest kernels.

Tried using custom compiled version, system packages and docker on a clean virtual machine and on cloud images.

### Standalone code, or other way to reproduce the problem

Just running:

```
hhvm -vServer.AllowRunAsRoot=1 --mode server -d hhvm.server.type=fastcgi -d hhvm.server.file_socket=/var/run/hhvm/sock
```

### Actual result

It hangs there. It doesn't create the socket nor the pid (or respond to the port, if using a port instead of the socket). When using the (exact same) docker image running on a different host (Ubuntu 16.04, 4.4.0-116-generic), it all works as expected, so it seems to be related to the host kernel.

It just outputs:

```
root@4df3c4e4ff4b:/# hhvm -vServer.AllowRunAsRoot=1 --mode server -d hhvm.server.type=fastcgi -d hhvm.server.file_socket=/var/run/hhvm/sock
Failed to hugify the .text section
```

### Expected result

It should create the pid and socket, and respond to requests.

I tracked down the version in which it started hanging. The latest docker tag working is:

`hhvm/hhvm:2018.11.30`

And the next one starts hanging (until latest):

`hhvm/hhvm:2018.12.01`

**Comment by eryi** [comment]
I am facing the same issue. Running HHVM inside docker.

Docker container running ubuntu:18.04  
Works with HHVM 3.29.1-1-bionic  
Hangs with HHVM 3.30.1-1-bionic

Host OS:
```
[ec2-user@ip-XXX-XXX-XXX-XXX ~]$ uname -a
Linux ip-XXX-XXX-XXX-XXX 4.9.85-38.58.amzn1.x86_64 #1 SMP Wed Mar 14 01:17:26 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[ec2-user@ip-XXX-XXX-XXX-XXX ~]$ cat /etc/*release*
NAME="Amazon Linux AMI"
VERSION="2017.09"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2017.09"
PRETTY_NAME="Amazon Linux AMI 2017.09"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2017.09:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
Amazon Linux AMI release 2017.09
cpe:/o:amazon:linux:2017.09:ga
```

HHVM logs
```
Failed to hugify the .text section
BootStats: pagein_self done, took 2ms wall, 4ms cpu, 0 MB RSS
BootStats: pthread_init done, took 1ms wall, 0ms cpu, 0 MB RSS
BootStats: Process::InitProcessStatics done, took 0ms wall, 0ms cpu, 0 MB RSS
BootStats: timezone_init done, took 0ms wall, 0ms cpu, 0 MB RSS
```

**Comment by eryi** [comment]
I've managed to reproduce this on a brand new aws lightsail server running ubuntu 18.04. If anyone is interested in taking a look, I'll be happy to provide root credentials.

OS:
```
ubuntu@ip-XXX-XXX-XXX-XXX:~$ uname -a
Linux ip-XXX-XXX-XXX-XXX 4.15.0-1031-aws #33-Ubuntu SMP Fri Dec 7 09:32:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@ip-XXX-XXX-XXX-XXX:~$ cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

hhvm
```
ubuntu@ip-XXX-XXX-XXX-XXX:~$ hhvm --version
HipHop VM 3.30.2 (rel)
Compiler: 1547490882_020824028
Repo schema: d5a63c2347799500a45fc243ed47a17091c8d6ea
ubuntu@ip-XXX-XXX-XXX-XXX:~$ hhvm -m server -p 8080
Failed to hugify the .text section
```

curl
```
ubuntu@ip-XXX-XXX-XXX-XXX:~$ curl http://localhost:8080
curl: (7) Failed to connect to localhost port 8080: Connection refused
```

**Comment by fredemmott** [comment]
Not actually a crash, but close enough.

Strangely enough, I can't reproduce this on Mac, but can in our Linux-based docker images.

It would be helpful if you:
1. install the `hhvm-dbg` package
2. attach gdb to hhvm (use `ps aux` to find the process id, then `gdb -p ProcessIdHere`
3. type `thread apply all bt` in to gdb

This gets me:

```
Thread 1 (Thread 0x7f7add5aa340 (LWP 1)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f7ad590b91c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x0000000001595d44 in HPHP::(anonymous namespace)::CompilerManager::ensure_started() [clone .constprop.437] ()
#3  0x00000000015961a9 in HPHP::compilers_start() ()
#4  0x0000000001199da1 in HPHP::hphp_process_init() ()
#5  0x00000000011a026e in HPHP::execute_program_impl(int, char**) ()
#6  0x00000000011a234e in HPHP::execute_program(int, char**) ()
#7  0x0000000000d42f24 in main ()
```

**Comment by fredemmott** [comment]
8867c2872eb19a79535370d6c82dfd50bea69da0

- I'm having more luck reproducing this in Docker than in real linux systems
- I can fix it on the reliably-failing systems by specifying -v Eval.HackCompilerWorkers=1
- I get the same symptoms with Eval.HackCompilerWorkers=0
- reducing the HHVM code for establishing the default:

```
root@92aad977bf3f:/# cat test.c
#include <unistd.h>

int main() {
  return sysconf(_SC_NPROCESSORS_ONLN) / 2;
}
root@92aad977bf3f:/# ./a.out ; echo $?
0
```
