### ISSUE TITLE
Crash (C++ stack exceeded?) when decreffing an extremely long chain of objects

### ISSUE THREAD

**Issue by Lexidor** [facebook/hhvm#8473]
### HHVM Version

Found in HHVM 3.30.4

Reproduced in
```
HipHop VM 4.1.0-dev (rel)
Compiler: 1553571522_618506654
Repo schema: 3aa6437a729134874cb0c7de2a0d6599147dff43

hh-6ffc6209b028bd9621f502118e19a092f43a2b87-4.1.0-dev Tue Mar 26 04:42:41 2019
```

### Operating System and Version

Ubuntu 18.04 LTS

### Standalone code, or other way to reproduce the problem

https://github.com/Lexidor/Hack-SegmentationFault-LinkedList/blob/master/lexidor/Test.hh

### Actual result

Console output
```
And now the garbage collector...
Segmentation fault (core dumped)
```

### Expected result

Console output
```
And now the garbage collector...
(exit)
```

Segfault core dump will be included once I find the file. :sweat_smile:

**Comment by Lexidor** [comment]
GDB:
```
(gdb) run /path/to/DataStructures/lexidor/Test.hh 
Starting program: /usr/bin/hhvm /path/to/DataStructures/lexidor/Test.hh
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe47ff700 (LWP 21143)]
[New Thread 0x7fffdefff700 (LWP 21145)]
And now the garbage collector...

Thread 1 "hhvm" received signal SIGSEGV, Segmentation fault.
0x00005555579e6288 in HPHP::ObjectData::release (this=0x7fffdc84e890) at ./hphp/runtime/base/object-data.cpp:171
171	./hphp/runtime/base/object-data.cpp: No such file or directory.
```

**Comment by Lexidor** [comment]
More GDB:
```
(gdb) run /path/to/DataStructures/lexidor/Test.hh 
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /usr/bin/hhvm /path/to/DataStructures/lexidor/Test.hh
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe47ff700 (LWP 21165)]
[New Thread 0x7fffdefff700 (LWP 21167)]
And now the garbage collector...

Thread 1 "hhvm" received signal SIGSEGV, Segmentation fault.
0x00005555579e6288 in HPHP::ObjectData::release (this=0x7fffdc84e890) at ./hphp/runtime/base/object-data.cpp:171
171	in ./hphp/runtime/base/object-data.cpp
(gdb) thread apply bt all
Invalid thread ID: bt all
(gdb) thread apply all bt

Thread 3 (Thread 0x7fffdefff700 (LWP 21167)):
#0  0x00007fffeff2d26c in __GI___sigtimedwait (set=<optimized out>, set@entry=0x555558a8ab80 <HPHP::(anonymous namespace)::g_sync_signals>, info=info@entry=0x7fffdeffd840, timeout=timeout@entry=0x0)
    at ../sysdeps/unix/sysv/linux/sigtimedwait.c:42
#1  0x00007ffff5d2645c in __sigwait (set=set@entry=0x555558a8ab80 <HPHP::(anonymous namespace)::g_sync_signals>, sig=sig@entry=0x7fffdeffd8fc) at ../sysdeps/unix/sysv/linux/sigwait.c:28
#2  0x00005555578569cb in HPHP::(anonymous namespace)::handle_signals () at ./hphp/util/sync-signal.cpp:108
#3  0x00007ffff5d1b6db in start_thread (arg=0x7fffdefff700) at pthread_create.c:463
#4  0x00007ffff000e88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7fffe47ff700 (LWP 21165)):
#0  0x00007ffff0001bf9 in __GI___poll (fds=fds@entry=0x7fffe47fd928, nfds=nfds@entry=1, timeout=timeout@entry=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x0000555556535a22 in poll (__timeout=-1, __nfds=1, __fds=0x7fffe47fd928) at /usr/include/x86_64-linux-gnu/bits/poll2.h:46
#2  HPHP::(anonymous namespace)::ExternCompiler::<lambda()>::operator() (__closure=0x7fffe6982cd8) at ./hphp/runtime/vm/extern-compiler.cpp:951
#3  std::__invoke_impl<void, HPHP::(anonymous namespace)::ExternCompiler::start()::<lambda()> > (__f=...) at /usr/include/c++/7/bits/invoke.h:60
#4  std::__invoke<HPHP::(anonymous namespace)::ExternCompiler::start()::<lambda()> > (__fn=...) at /usr/include/c++/7/bits/invoke.h:95
#5  std::thread::_Invoker<std::tuple<HPHP::(anonymous namespace)::ExternCompiler::start()::<lambda()> > >::_M_invoke<0> (this=0x7fffe6982cd8) at /usr/include/c++/7/thread:234
#6  std::thread::_Invoker<std::tuple<HPHP::(anonymous namespace)::ExternCompiler::start()::<lambda()> > >::operator() (this=0x7fffe6982cd8) at /usr/include/c++/7/thread:243
#7  std::thread::_State_impl<std::thread::_Invoker<std::tuple<HPHP::(anonymous namespace)::ExternCompiler::start()::<lambda()> > > >::_M_run(void) (this=0x7fffe6982cd0) at /usr/include/c++/7/thread:186
#8  0x00007ffff095157f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007ffff5d1b6db in start_thread (arg=0x7fffe47ff700) at pthread_create.c:463
#10 0x00007ffff000e88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7ffff7fabc80 (LWP 21162)):
#0  0x00005555579e6288 in HPHP::ObjectData::release (this=0x7fffdc84e890) at ./hphp/runtime/base/object-data.cpp:171
#1  0x00005555579e62e3 in HPHP::tvDecRefCountable<HPHP::TypedValue*> (tv=0x7fffdc84e880) at ./hphp/runtime/base/tv-refcount.h:114
#2  HPHP::tvDecRefGen<HPHP::TypedValue*> (tv=0x7fffdc84e880) at ./hphp/runtime/base/tv-refcount.h:134
#3  HPHP::ObjectData::release (this=0x7fffdc84e860) at ./hphp/runtime/base/object-data.cpp:204
#4  0x00005555579e62e3 in HPHP::tvDecRefCountable<HPHP::TypedValue*> (tv=0x7fffdc84e850) at ./hphp/runtime/base/tv-refcount.h:114
#5  HPHP::tvDecRefGen<HPHP::TypedValue*> (tv=0x7fffdc84e850) at ./hphp/runtime/base/tv-refcount.h:134
#6  HPHP::ObjectData::release (this=0x7fffdc84e830) at ./hphp/runtime/base/object-data.cpp:204
#7  0x00005555579e62e3 in HPHP::tvDecRefCountable<HPHP::TypedValue*> (tv=0x7fffdc84e820) at ./hphp/runtime/base/tv-refcount.h:114
#8  HPHP::tvDecRefGen<HPHP::TypedValue*> (tv=0x7fffdc84e820) at ./hphp/runtime/base/tv-refcount.h:134
#9  HPHP::ObjectData::release (this=0x7fffdc84e800) at ./hphp/runtime/base/object-data.cpp:204
#10 0x00005555579e62e3 in HPHP::tvDecRefCountable<HPHP::TypedValue*> (tv=0x7fffdc84e7f0) at ./hphp/runtime/base/tv-refcount.h:114
#11 HPHP::tvDecRefGen<HPHP::TypedValue*> (tv=0x7fffdc84e7f0) at ./hphp/runtime/base/tv-refcount.h:134
#12 HPHP::ObjectData::release (this=0x7fffdc84e7d0) at ./hphp/runtime/base/object-data.cpp:204
#13 0x00005555579e62e3 in HPHP::tvDecRefCountable<HPHP::TypedValue*> (tv=0x7fffdc84e7c0) at ./hphp/runtime/base/tv-refcount.h:114
#14 HPHP::tvDecRefGen<HPHP::TypedValue*> (tv=0x7fffdc84e7c0) at ./hphp/runtime/base/tv-refcount.h:134
#15 HPHP::ObjectData::release (this=0x7fffdc84e7a0) at ./hphp/runtime/base/object-data.cpp:204
#16 0x00005555579e62e3 in HPHP::tvDecRefCountable<HPHP::TypedValue*> (tv=0x7fffdc84e790) at ./hphp/runtime/base/tv-refcount.h:114
#17 HPHP::tvDecRefGen<HPHP::TypedValue*> (tv=0x7fffdc84e790) at ./hphp/runtime/base/tv-refcount.h:134
#18 HPHP::ObjectData::release (this=0x7fffdc84e770) at ./hphp/runtime/base/object-data.cpp:204
#19 0x00005555579e62e3 in HPHP::tvDecRefCountable<HPHP::TypedValue*> (tv=0x7fffdc84e760) at ./hphp/runtime/base/tv-refcount.h:114
#20 HPHP::tvDecRefGen<HPHP::TypedValue*> (tv=0x7fffdc84e760) at ./hphp/runtime/base/tv-refcount.h:134
#21 HPHP::ObjectData::release (this=0x7fffdc84e740) at ./hphp/runtime/base/object-data.cpp:204
#22 0x00005555579e62e3 in HPHP::tvDecRefCountable<HPHP::TypedValue*> (tv=0x7fffdc84e730) at ./hphp/runtime/base/tv-refcount.h:114
#23 HPHP::tvDecRefGen<HPHP::TypedValue*> (tv=0x7fffdc84e730) at ./hphp/runtime/base/tv-refcount.h:134
#24 HPHP::ObjectData::release (this=0x7fffdc84e710) at ./hphp/runtime/base/object-data.cpp:204
#25 0x00005555579e62e3 in HPHP::tvDecRefCountable<HPHP::TypedValue*> (tv=0x7fffdc84e700) at ./hphp/runtime/base/tv-refcount.h:114
#26 HPHP::tvDecRefGen<HPHP::TypedValue*> (tv=0x7fffdc84e700) at ./hphp/runtime/base/tv-refcount.h:134
#27 HPHP::ObjectData::release (this=0x7fffdc84e6e0) at ./hphp/runtime/base/object-data.cpp:204
#28 0x00005555579e62e3 in HPHP::tvDecRefCountable<HPHP::TypedValue*> (tv=0x7fffdc84e6d0) at ./hphp/runtime/base/tv-refcount.h:114
#29 HPHP::tvDecRefGen<HPHP::TypedValue*> (tv=0x7fffdc84e6d0) at ./hphp/runtime/base/tv-refcount.h:134
```

**Comment by fredemmott** [comment]
Much smaller example:

```Hack
class MyNode {
  public ?MyNode $next;
}

<<__EntryPoint>>
function main(): noreturn {
  $head = new MyNode();
  $tail = $head;
  for ($i = 0; $i < 10000000; ++$i) {
    $next = new MyNode();
    $tail->next = $next;
    $tail = $next;
  }
  exit(0);
}
```

**Comment by Lexidor** [comment]
I can repreduce that one too.

**Comment by fredemmott** [comment]
At least on MacOS, the limit is extremely close to 1024*128 - 1023*128 is fine for this:

```
  for ($i = 0; $i < (1024 * 128); ++$i) {
```

**Comment by fredemmott** [comment]
FB T42335747

**Comment by fredemmott** [comment]
Sorry, we're not currently not expecting this to be fixed, as it's hitting native system limits.

For what it's worth, PHP also has similar behavior, at a lower limit:

```
<?php
class MyNode {
  public $next;
}

function main(): noreturn {
  $head = new MyNode();
  $tail = $head;
  for ($i = 0; $i < 1024 * 64; ++$i) {
    $next = new MyNode();
    $tail->next = $next;
    $tail = $next;
  }
}

main();
```

When ref-counting is gone ,this will likely be resolved.
