### ISSUE TITLE
five func-ptr tests have been failing for a while

### ISSUE THREAD

**Issue by swalk-cavium** [facebook/hhvm#8491]
### HHVM Version

These tests have been failing at least since 01/10/2019 (e06e050).
Most recently

swalk@lab-7:~/extra/play.042419a/hhvm$ hphp/hhvm/hhvm --version
HipHop VM 4.3.0-dev (rel)
Compiler: heads/master-0-ga0cf1623d8f80c9cdd84b6dbd35460415a0c530e
Repo schema: c5c378c58a1b5764969d4587dc398f2281b848aa

### Operating System and Version

Ubuntu 16.04, Aarch64
swalk@lab-7:~/extra/play.042419a/hhvm$ uname -a
Linux lab-7 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:15:48 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux

### Standalone code, or other way to reproduce the problem

hphp/test/run -v -m interp
hphp/test/run -v -m interp -r
hphp/test/run -v -m jit -a '-vEval.JitPGO=0'
hphp/test/run -v -m jit -r -a '-vEval.JitPGO=0'
hphp/test/run -v -m jit -a '-vEval.JitPGO=1'
hphp/test/run -v -m jit -r -a '-vEval.JitPGO=1'

### Actual result

Post processed output script

hphp/test/slow/func-ptr/func-cmp.php | . | . | F | F | F | F | 
hphp/test/slow/func-ptr/func-cmp-warn.php | . | . | F | F | F | F | 
hphp/test/slow/func-ptr/func-convert.php | . | . | F | F | F | F | 
hphp/test/slow/func-ptr/func-stringish.php | . | . | F | F | F | F | 
hphp/test/slow/func-ptr/func-warn.php | . | . | F | F | F | F | 

### Expected result

Pass

Adding work-around suggested in https://github.com/facebook/hhvm/issues/8488
changes the result slightly.

+ After adding the work-around

hphp/test/slow/func-ptr/func-cmp.php | . | . | . | F | . | F | 
hphp/test/slow/func-ptr/func-cmp-warn.php | . | F | F | F | F | F | 
hphp/test/slow/func-ptr/func-convert.php | . | F | F | F | F | F | 
hphp/test/slow/func-ptr/func-stringish.php | . | . | F | . | F | . | 
hphp/test/slow/func-ptr/func-warn.php | . | . | F | F | F | F | 

Same signature of failure for at least func-cmp-warn

(gdb) run -c /mnt/diskb/swalk/play.042419a/hhvm/hphp/test/slow/config.ini -vEval.EnableArgsInBacktraces=true -vEval.EnableIntrinsicsExtension=true -vEval.HHIRInliningIgnoreHints=false -vRepo.Local.Mode=-- -vRepo.Central.Path=/mnt/diskb/swalk/play.042419a/hhvm/hphp/hhvm/verify.hhbc -vEval.Jit=true  -vEval.ProfileHWEnable=false -vEval.HackCompilerExtractPath='/mnt/diskb/swalk/play.042419a/hhvm/hphp/hhvm/hackc_%{schema}' -vEval.EmbeddedDataExtractPath='/mnt/diskb/swalk/play.042419a/hhvm/hphp/hhvm/hhvm_%{type}_%{buildid}' -vEval.JitPGO=0 -vResourceLimit.CoreFileSize=0   -vEval.RaiseFuncConversionWarning=1  -vEval.EmitFuncPointers=1 -vEval.EnablePHP=1  --file 'hphp/test/slow/func-ptr/func-cmp-warn.php' 
Starting program: /mnt/diskb/swalk/play.042419a/hhvm/hphp/hhvm/hhvm -c /mnt/diskb/swalk/play.042419a/hhvm/hphp/test/slow/config.ini -vEval.EnableArgsInBacktraces=true -vEval.EnableIntrinsicsExtension=true -vEval.HHIRInliningIgnoreHints=false -vRepo.Local.Mode=-- -vRepo.Central.Path=/mnt/diskb/swalk/play.042419a/hhvm/hphp/hhvm/verify.hhbc -vEval.Jit=true  -vEval.ProfileHWEnable=false -vEval.HackCompilerExtractPath='/mnt/diskb/swalk/play.042419a/hhvm/hphp/hhvm/hackc_%{schema}' -vEval.EmbeddedDataExtractPath='/mnt/diskb/swalk/play.042419a/hhvm/hphp/hhvm/hhvm_%{type}_%{buildid}' -vEval.JitPGO=0 -vResourceLimit.CoreFileSize=0   -vEval.RaiseFuncConversionWarning=1  -vEval.EmitFuncPointers=1 -vEval.EnablePHP=1  --file 'hphp/test/slow/func-ptr/func-cmp-warn.php'
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
[New Thread 0xffffb1bfe0d0 (LWP 4367)]
[New Thread 0xffffabffe0d0 (LWP 4394)]
...
Thread 1 "hhvm" received signal SIGSEGV, Segmentation fault.
0x0000000002a5e198 in HPHP::same(HPHP::StringData const*, HPHP::StringData const*) ()
(gdb) thread apply all bt

Thread 3 (Thread 0xffffabffe0d0 (LWP 4394)):
#0  do_sigwait (set=<optimized out>, set@entry=0x5128460 <HPHP::(anonymous namespace)::g_sync_signals>, 
    sig=sig@entry=0xffffabffd7f4) at ../sysdeps/unix/sysv/linux/sigwait.c:64
#1  0x0000ffffb7930c58 in __sigwait (set=0x5128460 <HPHP::(anonymous namespace)::g_sync_signals>, sig=0xffffabffd7f4)
    at ../sysdeps/unix/sysv/linux/sigwait.c:96
#2  0x0000000003dc9ae0 in HPHP::(anonymous namespace)::handle_signals(void*) ()
#3  0x0000ffffb7925fc4 in start_thread (arg=0x3dc9a28 <HPHP::(anonymous namespace)::handle_signals(void*)>)
    at pthread_create.c:335
#4  0x0000ffffb67142e0 in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:89

Thread 2 (Thread 0xffffb1bfe0d0 (LWP 4367)):
#0  0x0000ffffb670c030 in __GI___poll (fds=0xffffb1bfd850, nfds=1, timeout=<optimized out>)
    at ../sysdeps/unix/sysv/linux/generic/poll.c:38
#1  0x0000000001aade48 in std::thread::_Impl<std::_Bind_simple<HPHP::(anonymous namespace)::ExternCompiler::start()::{lambda()#1} ()> >::_M_run() ()
#2  0x0000ffffb691c280 in ?? () from /usr/lib/aarch64-linux-gnu/libstdc++.so.6
#3  0x0000ffffb7925fc4 in start_thread (arg=0xffffb691c260) at pthread_create.c:335
#4  0x0000ffffb67142e0 in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:89

Thread 1 (Thread 0xffffb4009010 (LWP 4280)):
#0  0x0000000002a5e198 in HPHP::same(HPHP::StringData const*, HPHP::StringData const*) ()
#1  0x0000000005200dbc in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

**Comment by swalk-cavium** [comment]
These failures are no longer present in a build from yesterday
at the commit below.

swalk@lab-7:~/extra/play.080719a/hhvm$ git branch -v
* master 69ad5f4 Reap Purger and HdrBlock

swalk@lab-7:~/extra/play.080719a/hhvm$ uname -a
Linux lab-7 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:15:48 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux
