### ISSUE TITLE
Segmentation fault with 4.8 on Ubuntu 19.04 (disco), makes HHAST unusable

### ISSUE THREAD

**Issue by aloiret** [facebook/hhvm#8512]
### HHVM Version

HipHop VM 4.8.0 (rel)
Compiler: 1559592623_572952533
Repo schema: f8b33c447c65e2be58473f7e8a031a770faecf8f

### Operating System and Version

Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco

### Standalone code, or other way to reproduce the problem

```hack
class Foo {
  private static int $counter = 0;
  public function getID(): int {
    $id = self::$counter;
    self::$counter++;
    return $id;
  }
}

<<__EntryPoint>>
function main(): noreturn {
  $a = new Foo();
  var_dump($a->getID());
  exit(0);
}
```

### Actual result

```

--------------------------------------IRGS--------------------------------------
+---------------------------------------- 1 stack element(s): -----------------------------------------+
|  0: (20) "counter" = DefConst<StaticStr<"counter">>                                                  |
+------------------------------------------------------------------------------------------------------+

+--------------------------------------------- 1 local(s) ---------------------------------------------+
|  0: (12) t4:Int = LdStk<Int,IRSPOff 0> t1:StkPtr                                                     |
+------------------------------------------------------------------------------------------------------+


-------------------------------------IRUnit-------------------------------------
TransKind: TransProfile
digraph G {
B0 [shape=box,color=orange,label="B0\ncount=1"]
B0 -> B1
B1 [shape=box,color=orange,label="B1\ncount=1"]
B1 -> B4; B1 -> B2 [color=blue]
B4 [shape=box,color=orange,label="B4\ncount=1"]
B4 -> B5; B4 -> B3 [color=blue]
B5 [shape=box,color=orange,label="B5\ncount=1"]
B5 -> B8; B5 -> B7 [color=blue]
B8 [shape=box,color=orange,label="B8\ncount=1"]
B7 [shape=box,color=blue,label="B7\ncount=1"]
B7 -> B8; B7 -> B9 [color=gray]
B3 [shape=box,color=blue,label="B3\ncount=1"]
B2 [shape=box,color=blue,label="B2\ncount=1"]
B9 [shape=box,color=gray,label="B9\ncount=1"]
}

 B0: [profCount=1]
Method public (mayusevv) (leaf) Foo::getID at 86
 Ret:  int (HH\int)
maxStackCells: 3
numLocals: 1
numIterators: 0
numClsRefSlots: 1
    --- bc 95t, fp _, spOff 3 (Foo::getID)
  95: SetL L:0
    (00) t0:FramePtr = DefFP

    --- bc 95t, fp 0, spOff 3 (Foo::getID)
  95: SetL L:0
    (01) t1:StkPtr = DefSP<FPInvOff 3> t0:FramePtr
    (02) Jmp -> B1
  no fallthrough

 B1: [profCount=1] (preds B0)
    (04) CheckLoc<Uninit,0> t0:FramePtr -> B2<Unlikely>
  -> B4

 B4: [profCount=1] (preds B1)
    (06) CheckStk<Int,IRSPOff 0> t1:StkPtr -> B3<Unlikely>
  -> B5

 B5: [profCount=1] (preds B4)
    (07) EndGuards
    (08) IncProfCounter<6>
    (09) t2:{Obj<=Foo|Cctx} = LdCtx t0:FramePtr
    (10) t3:Obj<=Foo = AssertType<Obj<=Foo> t2:{Obj<=Foo|Cctx}
    (12) t4:Int = LdStk<Int,IRSPOff 0> t1:StkPtr
    (13) t5:Uninit = LdLoc<Uninit,0> t0:FramePtr
    (14) StLoc<0> t0:FramePtr, t4:Int
    (18) StStk<IRSPOff 0> t1:StkPtr, t4:Int
    --- bc 98t, fp 0, spOff 2 (Foo::getID)
  98: String "counter"
    (21) StStk<IRSPOff 0> t1:StkPtr, "counter"

    --- bc 103t, fp 0, spOff 3 (Foo::getID)
 103: Self 0
    (23) StClsRefCls<0> t0:FramePtr, Cls(Foo)
    (24) KillClsRefTS<0> t0:FramePtr

    --- bc 105t, fp 0, spOff 3 (Foo::getID)
 105: IncDecS PostInc 0
    (25) CheckRDSInitialized<153> -> B7<Unlikely>
  -> B8

 B8: [profCount=1] (preds B7 B5)
    (29) t9:PtrToSPropGen = LdRDSAddr<PtrToSPropGen,50304760>
    (30) t10:PtrToRSPropCell = UnboxPtr t9:PtrToSPropGen
    (31) t11:Cell = LdMem<Cell> t10:PtrToRSPropCell
  no fallthrough

------------------------cold blocks-------------------------
 B7<Unlikely>: [profCount=1]<Unlikely> (preds B5)
    (28) InitSProps<Foo> -> B9<Catch>
  -> B8

 B3<Unlikely>: [profCount=1]<Unlikely> (preds B4)
    --- bc 95t, fp 0, spOff 3 (Foo::getID)
  95: SetL L:0
    (05) ReqRetranslate<0,0> t1:StkPtr, t0:FramePtr
  no fallthrough

 B2<Unlikely>: [profCount=1]<Unlikely> (preds B1)
    (03) ReqRetranslate<0,0> t1:StkPtr, t0:FramePtr
  no fallthrough

-----------------------frozen blocks------------------------
 B9<Catch>: [profCount=1]<Unused> (preds B7)
    --- bc 105t, fp 0, spOff 3 (Foo::getID)
 105: IncDecS PostInc 0
    (26) BeginCatch
    (27) EndCatch<IRSPOff 0,UnwindOnly> t0:FramePtr, t1:StkPtr
  no fallthrough


-----------------------------------RegionDesc-----------------------------------
Region (1 blocks):
Block -8 Foo::getID@95 length 9 initSpOff 3 profTransID -1
  precondition: Local{0} :: Uninit (DataTypeBoxAndCountness)
  precondition: Stack{3} :: Int (DataTypeSpecific)
    95  SetL L:0
    97  PopC
    98  String "counter"
    103  Self 0
    105  IncDecS PostInc 0
    108  PopC
    109  CGetL L:0
    111  VerifyRetTypeC
    112  RetC

digraph RegionCFG {
 node[shape=box,style=filled]
 "B-8" [label="B -8\np: 0",fillcolor="#ffffff"]
}

Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.7233.log
Segmentation fault (core dumped)
```

### Expected result

```
int(0)
```

### More details

This issue affects HHAST and makes it unusable with HHVM 4.8 on Ubuntu 19.04. Reduced testcase provided below.

When building HHVM 4.8 from source, noticed that:
  - issue reproducible with GCC 8.3 (system default) and -DCMAKE_BUILD_TYPE=RelWithDebInfo (same compiler / flags than OSS packages)
  - issue NOT reproducible with GCC 8.3 and -DCMAKE_BUILD_TYPE={Debug,Release}
  - issue NOT reproducible with GCC 9.0 (official package) and -DCMAKE_BUILD_TYPE=RelWithDebInfo

Bisecting shows the issue started after this commit:

ecedcc96d6 Add NewObjRD as an optimizations for ReifiedName + NewObj

The testcase runs fine with `-v Eval.Jit=0` but GDB shows the segmentation fault actually happens in IR gen. Also the issue is not reproducible in Ubuntu 18.04.

If you think we are hitting a GCC optimizer bug with no reasonable workaround I can send a PR to build Ubuntu 19.04 package from GCC 9 and an other one to add this testcase.

Many thanks to @fredemmott for helping with debugging this, especially providing the reduced testcase and running GDB.

**Comment by fredemmott** [comment]
Traces with debug info: https://gist.github.com/fredemmott/921a14fdee32c73017d04959ee4dab11

**Comment by fredemmott** [comment]
Especially as it's *only* in RelWithDebInfo builds - not Release, not Debug - and not on any other platforms - I'm still leading towards toolchain issue.

I've asked @oulgen and @jano on the original diff (FB: D15540960) for their thoughts on this. It /does/ touch ir-gen, but only object constructors.

**Comment by aloiret** [comment]
Did some fresh builds from 69c94b298a8667a08badcc62b78bdf0436cdf805 with the supported compilers on Ubuntu 19.04 disco (GCC 7.4.0, 8.3.0 and 9.0.1), with the following configuration:

```
cmake -DCMAKE_INSTALL_PREFIX=/usr/local/ -DMYSQL_UNIX_SOCK_ADDR=/tmp/mysql.sock -DCMAKE_BUILD_TYPE=RelWithDebInfo .
```

For each compiler, did one build without code change and one with this patch (O2 -> O3, add -momit-leaf-frame-pointer):

```diff
--- a/CMake/HPHPCompiler.cmake
+++ b/CMake/HPHPCompiler.cmake
@@ -270,8 +270,8 @@ if (${CMAKE_CXX_COMPILER_ID} STREQUAL "Clang" OR ${CMAKE_CXX_COMPILER_ID} STREQU
   set(CMAKE_CXX_FLAGS_MINSIZEREL     "-Os -DNDEBUG")
   set(CMAKE_C_FLAGS_RELEASE          "-O3 -DNDEBUG")
   set(CMAKE_CXX_FLAGS_RELEASE        "-O3 -DNDEBUG")
-  set(CMAKE_C_FLAGS_RELWITHDEBINFO   "-O2 -g${GDB_SUBOPTION} -DNDEBUG")
-  set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2 -g${GDB_SUBOPTION} -DNDEBUG")
+  set(CMAKE_C_FLAGS_RELWITHDEBINFO   "-O3 -g${GDB_SUBOPTION} -DNDEBUG")
+  set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O3 -g${GDB_SUBOPTION} -DNDEBUG")
   set(CMAKE_C_FLAGS                  "${CMAKE_C_FLAGS} -W -Werror=implicit-function-declaration")
 
   mark_as_advanced(CMAKE_C_FLAGS_DEBUGOPT CMAKE_CXX_FLAGS_DEBUGOPT)
@@ -298,6 +298,7 @@ if (${CMAKE_CXX_COMPILER_ID} STREQUAL "Clang" OR ${CMAKE_CXX_COMPILER_ID} STREQU
   endforeach()
 
   foreach(opt ${RELEASE_CXX_OPTIONS})
+    set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELEASE} -${opt}")
     set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -${opt}")
   endforeach()
 
```

# GCC 7.4.0 results
## With -O2
### test/run
No failures

### test/run all
[47 failures](https://gist.github.com/aloiret/82a9aba5623e2fdf5e9b246d18d6704c) including [8 segfaults](https://gist.github.com/aloiret/1acf985a950c08894f5bc2ca9e62bf93). Some of the failures my be related to locales.

## With -O3 -momit-leaf-frame-pointer
### test/run
No failures

### test/run all
[48 failures](https://gist.github.com/aloiret/28efd9223f5763d402167a987fc7b0cb) including [8 segfaults](https://gist.github.com/aloiret/9fa74b8cf3175ae347c6b3daa9c9f137). Some of the failures my be related to locales.

## Differences

Failures from test/run all:
```diff
--- gcc-7-O2/hhvm/TEST-ALL/test-failureseWRRtY
+++ gcc-7-O3-momit/hhvm/TEST-ALL/test-failuresSN9i0H
@@ -45,3 +45,4 @@
 test/zend/good/ext/readline/tests/libedit_info_001.php
 test/zend/good/ext/readline/tests/libedit_write_history_001.php
 test/zend/good/ext/xsl/tests/bug53965.php
+test/zend/good/ext/zlib/tests/zlib_scheme_stat_basic2.php
```

Segfaults from test/run all:
```diff
--- gcc-7-O2/hhvm/TEST-ALL/segfaults
+++ gcc-7-O3-momit/hhvm/TEST-ALL/segfaults
@@ -1,8 +1,8 @@
-test/slow/func-ptr/func-convert.php 
+test/zend/good/ext/intl/tests/uconverter_oop_callback.php 
 test/slow/func-ptr/func-stringish.php 
+test/slow/func-ptr/func-convert.php 
 test/slow/func-ptr/func-cmp.php 
 test/slow/func-ptr/func-warn.php 
 test/slow/u_converter/2135.php 
 test/slow/func-ptr/func-cmp-warn.php 
 test/zend/good/ext/intl/uchar/tests/basic-functionality.php 
-test/zend/good/ext/intl/tests/uconverter_oop_callback.php 
```

# GCC 8.3.0 results
## With -O2
### test/run

Testsuite aborted after very few passes and numerous segfaults, and also the following error:
```
Warning: Unable to send message: Invalid argument in /home/ubuntu/gcc-8-O2/hhvm/hphp/test/run.php on line 1551
```

### test/run all

Unable to run

## With -O3 -momit-leaf-frame-pointer

Same as for -O2

# GCC 9.0.1 results
## With -O2
### test/run
[149 failures](https://gist.github.com/aloiret/8fb7cd5a57793805488b7ec34ba1f3cf) including [148 segfaults](https://gist.github.com/aloiret/e60f2aafb9e7e3558c919461852dcc7d)

72 of the 148 segfaulting tests did with this assertion failure:
```
-------------------------------Assertion Message--------------------------------
stack idx went negative: irSPOff: 0, fpRel: 0
-------------------------------Assertion Failure--------------------------------
hphp/runtime/vm/jit/frame-state.cpp:1460: HPHP::jit::irgen::StackState& HPHP::jit::irgen::FrameStateMgr::stackState(HPHP::jit::FPInvOffset): assertion `idx >= 0' failed.
```

### test/run all

Testsuite aborted after a log segfaults (but also a lot of passes) and following error:
```
Warning: Unable to send message: Invalid argument in /home/ubuntu/gcc-8-O2/hhvm/hphp/test/run.php on line 1551
```

## With -O3 -momit-leaf-frame-pointer

### test/run

[72 failures](https://gist.github.com/aloiret/36fe418930d1eb08c5f9a27ed3322410), all segfaults

### test/run all

[435 failures](https://gist.github.com/aloiret/f90124782e3aa75bda760e4bed9e05eb) including [417 segfaults](https://gist.github.com/aloiret/2d27a9e694817c3e454a0c63cd628bda)

1 of the 417 segfaulting tests did with this assertion failure:
```
-------------------------------Assertion Message--------------------------------
preventReturnToTC(0x7f36bd4bffc0): 0xffffffffffffffff isn't in TC
-------------------------------Assertion Failure--------------------------------
hphp/runtime/vm/bytecode.cpp:1741: void HPHP::unwindPreventReturnToTC(HPHP::ActRec*): assertion `jit::tc::isValidCodeAddress(savedRip)' failed.
```

## Differences

Failures from test/run:
```diff
--- gcc-9-O2/hhvm/TEST/test-failures1mErHp
+++ gcc-9-O3-momit/hhvm/TEST/test-failuresGjuY6f
-test/quick/Xhp.php   
-test/quick/Xhp2.php  
-test/quick/abstract_static_1.php
-test/quick/abstract_static_2.php
-test/quick/asm_fatal_await.hhas
 test/quick/asm_ret_type.hhas
 test/quick/builtin_recurse.php
-test/quick/class_abstract_final2.php
-test/quick/class_abstract_final4.php
-test/quick/class_abstract_final5.php
-test/quick/class_constant.php
 test/quick/class_exists_throw.php
-test/quick/closure_use_this.php
 test/quick/constructor_throw.php
 test/quick/continuation_inherit.php
-test/quick/ctor_param_promotion_abstract.php
-test/quick/ctor_param_promotion_generic.php
-test/quick/ctor_param_promotion_generic1.php
-test/quick/ctor_param_promotion_interface.php
-test/quick/ctor_param_promotion_redeclaration.php
-test/quick/ctor_param_promotion_trait.php
 test/quick/debug_backtrace_multiline.php
 test/quick/debugger/eval2.php
 test/quick/debugger/exception1.php
@@ -26,37 +10,15 @@   
 test/quick/dict/comparisons.php
 test/quick/dict/convert.php
 test/quick/dict/serialize.php
-test/quick/dv_ab.php 
-test/quick/dv_af.php 
-test/quick/dv_ai.php 
-test/quick/dv_as.php 
-test/quick/dv_ba.php 
-test/quick/dv_bf.php 
-test/quick/dv_bi.php 
-test/quick/dv_bs.php 
-test/quick/dv_i0.php 
-test/quick/dv_ia.php 
-test/quick/dv_ib.php 
-test/quick/dv_if.php 
-test/quick/dv_is.php 
-test/quick/dv_si.php 
-test/quick/dv_si_func.php
 test/quick/exception_handler.php
 test/quick/exception_many_locals.php
 test/quick/exceptions.php
 test/quick/exceptions4.php
-test/quick/exceptions5.php
-test/quick/exceptions6.php
 test/quick/exceptions7.php
 test/quick/exceptions8.php
-test/quick/exit.php  
-test/quick/experimental_mode_disallowed_without_hacksperimental_runtime_option.php
+test/quick/fc_enum_5.php
 test/quick/fc_enum_7.php
 test/quick/fc_enum_8.php
-test/quick/fc_enum_9.php
-test/quick/foreach-bad.php
-test/quick/func2.php 
-test/quick/func3.php 
 test/quick/hh_async_closure_return_type_2.php
 test/quick/hh_async_closure_return_type_3.php
 test/quick/hh_async_return_type_2.php
@@ -65,85 +27,46 @@   
 test/quick/hh_async_return_type_this_1.php
 test/quick/hh_async_return_type_this_2.php
 test/quick/hh_async_return_type_this_3.php
-test/quick/hh_bad_start.php
 test/quick/hh_closure_return_type_2.php
 test/quick/hh_closure_return_type_3.php
 test/quick/hh_closure_return_type_this_0.php
 test/quick/hh_closure_return_type_this_1.php
 test/quick/hh_closure_return_type_this_2.php
 test/quick/hh_closure_return_type_this_3.php
-test/quick/hh_numbers.php
+test/quick/hh_typehint1.php
 test/quick/hhir_cgetm_exceptions.php
 test/quick/hhir_eq_stack.php
 test/quick/hopt-translator_unwind.hhas
 test/quick/intercept.php
-test/quick/interface-bad-methodbody.php
-test/quick/interface_implements_interface.php
-test/quick/keyref_error.php
 test/quick/keyset/convert.php
-test/quick/memoize_lsb/memoize_lsb_non_static.php
-test/quick/memoize_lsb/memoize_lsb_on_function.php
 test/quick/method-non-object.php
-test/quick/method-non-object2.php
-test/quick/method_param_promotion_error.php
-test/quick/neg_iva.hhas
 test/quick/nested_vm_exceptions.php
 test/quick/nested_vm_exceptions2.php
 test/quick/no_arg_class_alias.php
 test/quick/nonnull/type-hint.php
 test/quick/nothing/type-hint.php
-test/quick/ns_existing_names_class.php
 test/quick/ns_invalid_func.php
 test/quick/ns_use_func.php
 test/quick/null/type-hint.php
 test/quick/obj-string-throw.php
-test/quick/on_list_assign.php
-test/quick/parse_fail_shapes.php
-test/quick/parse_fail_shapes2.php
-test/quick/parse_fail_shapes3.php
-test/quick/parse_fail_strict_hashbang_whitespace_start.php
-test/quick/parse_fail_type_constraint.php
-test/quick/parser_massive_add_exp.php
-test/quick/parser_massive_concat_exp.php
 test/quick/poly-torture.php
-test/quick/post_try_error.php
 test/quick/profile/setprofile-this.php
 test/quick/profile/setprofile_throw.php
 test/quick/raise_array_index_notice.php
-test/quick/reassign_this1.php
-test/quick/reassign_this2.php
-test/quick/reassign_this3.php
 test/quick/record-equal.php
 test/quick/record_decl_error.php
-test/quick/recurse-reentry.php
-test/quick/redeclared_function.php
-test/quick/redeclared_method.php
-test/quick/reserved_class1.php
-test/quick/reserved_class2.php
 test/quick/string_replace_overflow.php
 test/quick/surprise_throw.php
-test/quick/syntax-error-incl.php
-test/quick/syntax-error.php
 test/quick/too-few-args.php
-test/quick/toporder.hhas
 test/quick/tostring_throw.php
 test/quick/tostring_throw_setopl.php
-test/quick/trailing_comma_bad1.php
-test/quick/trailing_comma_bad2.php
-test/quick/trailing_comma_bad3.php
-test/quick/trailing_comma_bad4.php
-test/quick/trailing_comma_bad5.php
-test/quick/trailing_comma_bad6.php
-test/quick/traits2.php
 test/quick/translator_unwind.hhas
+test/quick/typechecks-obj.php
 test/quick/typehint_arraykey.php
 test/quick/typehint_number.php
 test/quick/unreachable-fpi-1.hhas
-test/quick/unset_static.php
 test/quick/vec/apc.php
 test/quick/vec/comparisons.php
 test/quick/vec/convert.php
 test/quick/vec/serialize.php
 test/quick/vector-unwind-decref.php
-test/quick/vgets.php 
-test/quick/xhp-malformed.php
```


For failing tests, segfaults may be hidden by /usr/bin/timeout. Saved all the build trees, logs and segfault stack traces in case it can help.

**Comment by fredemmott** [comment]
New backtrace from 4.23:

```
(gdb) bt
#0  raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x000055d5e5ed95dc in HPHP::bt_handler (sigin=<optimized out>, info=<optimized out>) at ./hphp/runtime/base/crash-reporter.cpp:270
#2  <signal handler called>
#3  HPHP::ArrayData::rval (k=<optimized out>, this=<optimized out>) at ./hphp/runtime/vm/jit/irgen-internal.h:357
#4  HPHP::detail::is_ts_bool (s=..., ts=<optimized out>) at ./hphp/runtime/base/type-structure-helpers-defs.h:50
#5  HPHP::is_ts_nullable (ts=<optimized out>) at ./hphp/runtime/base/type-structure-helpers-defs.h:80
#6  HPHP::jit::irgen::(anonymous namespace)::emitIsTypeStructWithoutResolvingIfPossible (env=..., ts=0xf7c0cd36a82bd600) at ./hphp/runtime/vm/jit/irgen-types.cpp:1083
#7  0x000055d5e6699e67 in HPHP::jit::irgen::(anonymous namespace)::handleIsResolutionAndCommonOpts (shouldDecRef=<synthetic pointer>: <optimized out>,
    done=<synthetic pointer>: <optimized out>, op=(unknown: 88), env=...) at ./hphp/runtime/vm/jit/irgen-types.cpp:1282
#8  HPHP::jit::irgen::emitIsTypeStructC (env=..., op=<optimized out>) at ./hphp/runtime/vm/jit/irgen-types.cpp:1305
#9  0x000055d5e6879671 in HPHP::jit::(anonymous namespace)::form_region (env=...) at ./hphp/runtime/vm/jit/region-tracelet.cpp:545
#10 0x000055d5e687ba8f in HPHP::jit::selectTracelet (ctx=..., kind=kind@entry=HPHP::jit::TransKind::Profile, maxBCInstrs=1347, inlining=inlining@entry=false)
    at ./hphp/runtime/vm/jit/region-tracelet.cpp:657
#11 0x000055d5e6866b89 in HPHP::jit::<lambda()>::operator() (__closure=<optimized out>) at ./hphp/runtime/vm/jit/region-selection.cpp:786
#12 HPHP::jit::selectRegion (context=..., kind=HPHP::jit::TransKind::Profile) at ./hphp/runtime/vm/jit/region-selection.cpp:795
#13 0x000055d5e67a5b5c in HPHP::jit::mcgen::retranslate (args=..., ctx=...) at ./hphp/runtime/vm/jit/mcgen-translate.cpp:462
#14 0x000055d5e79c584a in HPHP::jit::svcreq::(anonymous namespace)::getTranslation (args=...) at /usr/include/c++/8/ext/atomicity.h:96
#15 0x000055d5e79d3588 in HPHP::jit::svcreq::(anonymous namespace)::bindJmp (smashed=@0x7fff60757acf: false, trflags=..., req=HPHP::jit::REQ_BIND_JMP, destSk=...,
    toSmash=0x55d5ef17cb5b "\351Fd\213\006") at /usr/include/c++/8/bits/shared_ptr_base.h:731
#16 HPHP::jit::svcreq::handleServiceRequest (info=...) at ./hphp/runtime/vm/jit/service-request-handlers.cpp:283
#17 0x000055d5eb20009a in ?? ()
#18 0x0000000000000000 in ?? ()
```

Other threads are polling/waiting.
